### ISSUE TITLE
Bug with Spring Cloud Gateway

### ISSUE THREAD

**Issue by NomedXD** [micrometer-metrics/micrometer#5396] opened 2024-08-19 20:51 UTC
Bug according opened, but not replied issue https://github.com/spring-cloud/spring-cloud-gateway/issues/3184#issue-2039616302

In one word, correlation id is not added in Gateway logs after configuring maven dependencies, bit in other microservices everything works

It is also possible to provide any more configuration, if needed.

**Comment by jonatan-ivanov** [comment] 2024-08-19 21:30
Duplicate of https://github.com/spring-cloud/spring-cloud-gateway/issues/3184

**Closed** 2024-08-19 21:30 UTC
Labels: waiting-for-triage
