### ISSUE TITLE
No uri tag for requests with responses other than 404

### ISSUE THREAD

**Issue by alebar** [micrometer-metrics/micrometer#534] opened 2018-04-03 20:03 UTC
The `WebMvcTags.uri()` method protects us from blowing  up the cardinality of a `http.server.requests` metric by providing the `NOT_FOUND` value in case of requests that ended with the 404 responses.

But what if service is configured to return other status than 404 for not existing paths?
For example there can be server with general rule that every request without authentication header ends with 401 status.
Or - as a protection against the [forced browsing attack](https://www.owasp.org/index.php/Forced_browsing) - the server might return 403 to not give any hint about the existence of a queried resource.

It seems that `WebMvcTags` will try to return the path info of the request, possibly creating a new unique tag. This way an attacker could cause a memory leak (creating more and more timers) simply by sending a lot of random requests.

I was trying to provoke that in a sample spring boot application, but I was getting `null` for `request.getPathInfo()` so eventually the tag was always `root`.

If the issue is real then I have no idea how to fix it. Maybe we should always stick to `BEST_MATCHING_PATTERN_ATTRIBUTE` as the only reliable source of stable URL?

**Comment by jkschneider** [comment] 2018-04-03 20:54
We may need to add more statuses (like 401, 403) to cover the practical cases here.

The problem is that static resources never have a matching `BEST_MATCHING_PATTERN_ATTRIBUTE`.

**Comment by jkschneider** [comment] 2018-04-03 20:54
cc / @adriancole.

**Comment by jkschneider** [comment] 2018-04-03 21:00
The important thing is that we cover the common cases. We don't strictly have to be exhaustive about it. So if your service returns `418 - I'M A TEAPOT` where others would return a `403`, you can survive your own imagined cleverness by customizing the uri tag with your own `WebMvcTagsProvider`.

**Comment by alebar** [comment] 2018-04-03 21:17
Yes, the custom `WebMvcTagsProvider` seems to be the best way at the moment.
I was just wondering if we can get more out of `BEST_MATCHING_PATTERN_ATTRIBUTE` - in our case this attribute is only present for API endpoints, so null means an invalid uri. I didn't know about the static resources.

You can treat this issue as a question or a suggestion of a topic to think about. Maybe it's worth noticing in docs? To mention the `WebMvcTagsProvider` for teapots?

**Comment by volkanto** [comment] 2022-10-26 22:28
Hey hi guys, sorry for chip-in here, I have very similar question regarding `BEST_MATCHING_PATTERN_ATTRIBUTE` usage with `401` HTTP status. We were not aware before that unauthorized requests to the our application endpoints end up with `root` value for the `uri` tag. When we test the same API endpoints with an authenticated request, we are getting proper value for the `uri` tag, I couldn't understand why this is happening for unauthorized requests, is there any built-in solution to overcome this problem or should I handle that with a custom `WebMvcTagsProvider`?

**Comment by shakuzen** [comment] 2022-10-31 06:47
@volkanto There used to be Spring instrumentation in a `micrometer-spring-legacy` module in this repo. That code has since been moved to Spring and removed from here. Does the issue happen when using the latest versions of Spring Boot? If so, it is probably worth opening an issue in Spring Boot with a sample application that reproduces the issue. As far as I remember, if `BEST_MATCHING_PATTERN_ATTRIBUTE` is set, it should be used.

**Comment by shakuzen** [comment] 2022-10-31 06:50
Closing this issue because the mentioned instrumentation is no longer maintained in this repository. See [Spring Boot's documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.spring-mvc) for the latest related documentation.

**Closed by shakuzen** 2022-10-31 06:50 UTC
Labels: doc-update
