### ISSUE TITLE
Initialize metrics to zero at start up

### ISSUE THREAD

**Issue by MacyTech** [micrometer-metrics/micrometer#1604] opened 2019-09-26 15:13 UTC
We are using micrometer in our application. We want the metrics to initialize to zero at start up. Right now metrics only show when the first message is received. Is there anyway to default it to zero at start up of the application? We need this for both http metrics and custom metrics.

**Comment by mweirauch** [comment] 2019-09-26 18:58
Where do you want the metrics to be initalized to zero at startup? In your monitoring system?
When the application starts, they are always zerod within the application process.
Please leave a note what monitoring system backend - respectively which micrometer-registry-project you are using.

**Comment by shakuzen** [comment] 2021-03-31 07:01
Closing due to lack of requested feedback.

In addition to what @mweirauch mentioned, we cannot "zero" meters that haven't been registered yet. For example, HTTP server request metrics won't be registered until the request completes. And each request can potentially be a new meter (combination of tags). At startup, your application hasn't received any requests, so we don't have any HTTP server request metrics to zero.

If you would still like to pursue this, please help us understand your use case rather than describing the solution.

**Closed by shakuzen** 2021-03-31 07:01 UTC
Labels: question

**Comment by shakuzen** [comment] 2023-04-18 03:31
> no data available (because the endpoint is not working)

In practice, this isn't really an issue because typically at a minimum JVM/process/system metrics will be configured and available from shortly after application startup, whether there is any work done in the application or not.

> no requests yet received (the metric is not present in the list).

The problem is we do not know what requests we might receive or their outcomes. From that documentation:

> Most Prometheus client libraries (including Go, Java, and Python) will automatically export a 0 for you for metrics with no labels.

If we have meters with no labels, they most likely are registered on application startup. The problem for things like HTTP metrics is that we don't know what values of the tags (labels) will be ahead of time. And the Prometheus client does not allow registering the same metric name with a different set of labels, so we couldn't register the metric name without labels first and then register it with labels after. I suppose we could register a meter with tag values all equal to `UNKNOWN` but that seems odd as that will never be recorded subsequently. Is there existing Prometheus HTTP instrumentation that does that sort of thing?

**Comment by lucasvc** [comment] 2023-04-18 07:17
> > no data available (because the endpoint is not working)
> In practice, this isn't really an issue because typically at a minimum JVM/process/system metrics will be configured and available from shortly after application startup, whether there is any work done in the application or not.

I was not thinking on "startup", but in case that service was dead or prometheus endpoint did not respond (by any reason: misconfiguration, assigned JVM threads killed,..).

**Comment by shakuzen** [comment] 2023-04-18 09:06
I'm saying that should already be distinguishable because metrics will be registered on startup so if a response to a scrape request is received, it will contain *some* metrics, but perhaps not *all* metrics the scrape request will ever respond with.

**Comment by janeklb** [comment] 2024-04-04 15:32
I'd also like to have meters register themselves with 0s on startup.
My specific usecase is as follows:
- i want count sparse events (eg. when something fails)
- i want the metrics registry to store an explicit 0 value / want my timeseries data to have explicit 0s when things are not failing

I've been trying to achieve this using a counter without any luck (seems like all the counter implementations check for incrementSize > 0 anyway).

Is the correct approach to store things as a summary instead?
