### ISSUE TITLE
InfluxMeterRegistry - Support for sending data using UDP

### ISSUE THREAD

**Issue by cmallwitz** [micrometer-metrics/micrometer#1832] opened 2020-01-30 19:01 UTC
Hi 

I would be interested in an option to send data using UDP to InfluxDB and even willing to try to contribute some code. 
Questions: 
1) as far as I can tell there is no existing Influx UDP backend for mircometer-metrics, isn't it?
2) What should the config to trigger this be? I could see "influx.uri=udp://localhost:8089" although udp isn't really a URI schema...

Thanks
Christian

**Comment by izeye** [comment] 2020-01-30 23:07
@cmallwitz Thanks for opening an issue, but this seems to be a duplicate of https://github.com/micrometer-metrics/micrometer/issues/369. It would be better to continue the discussion there.

**Comment by shakuzen** [comment] 2020-01-31 04:19
Duplicates #369

**Closed by shakuzen** 2020-01-31 04:19 UTC

**Comment by shakuzen** [comment] 2020-01-31 04:21
@cmallwitz thank you for offering to help. Let's continue the discussion over on the preexisting issue. For reference, in our StatsD registry, we have a configuration option to select the protocol.
