### ISSUE TITLE
Kafka consumer metrics doesn't show all consumers.

### ISSUE THREAD

**Issue by manderson23** [micrometer-metrics/micrometer#1018] opened 2018-11-19 11:05 UTC
I have a Spring Boot 2.1.x application with multiple Kafka consumers. One with client.id `consumer1` and the other with client.id `consumer2`.

Via JMX I can view the metrics for each consumer however via `/actuator/prometheus` I only see entries for one consumer e.g. `kafka_consumer_join_time_avg_seconds{client_id="consumer1",} 0.0`

There are no metrics reported for `consumer2`.

**Comment by izeye** [comment] 2018-11-19 11:49
@manderson23 Thanks for the report. This seems a duplicate of #983.

**Closed by izeye** 2018-11-19 11:49 UTC
