### ISSUE TITLE
Missing metrics value from JvmGcMetrics

### ISSUE THREAD

**Issue by archellix** [micrometer-metrics/micrometer#3601] opened 2023-01-25 13:33 UTC
We are using Spring Boot (2.5.12) with Java 11 and Shenandoan GC
After upgrading from 1.1.3 to 1.7.9, metrics disappeared.

```
jvm.gc.max.data.size
jvm.gc.live.data.size
```

The fact is that Shenandoan clears weak references to the value of 
`io.micrometer.core.instrument.internal.DefaultGauge` 
and the result is NaN.
```
{
   labels: {
       "sensor": "jvm.gc.live.data.size"
   },
   "kind": "DGAUGE",
   "value": "NaN"
},
```

It looks like the problem is known and there is already a solution to it in the form of `io.micrometer.core.instrument.Gauge.Builder#strongReference`

but it is not possible to configure it somehow in `io.micrometer.core.instrument.binder.jvm.JvmGcMetrics`

## Some interest moment

In version 1.1.3 everything works fine, we replaced JvmGcMetrics from version 1.7.9 on 1.1.3 and the problems are gone.

## How we fixed that

We created our own MeterRegistry

```
public class CustomMeterRegistry extends MeterRegistry {

    @Override
    protected <T> Gauge newGauge(Meter.Id id, @Nullable T obj, ToDoubleFunction<T> valueFunction) {
        return new DefaultGauge<>(id, obj, new StrongReferenceGaugeFunction<>(obj, valueFunction));
    }
}
```
and added `StrongReferenceGaugeFunction` permanently

## What would we like
Since there is already a configuration for such a situation, we would like to use it somehow, but at the same time not to redo the entire `JvmGcMetrics`

Could use please help us? May be there is another better solution.

Thanks and good day.

**Comment by shakuzen** [comment] 2023-01-26 10:30
Weak references in gauges should only be an issue when the underlying object gets garbage collected because there are no more references to it. This should not happen for the mentioned metrics as long as a reference to `JvmGcMetrics` is maintained. When using Spring Boot, the auto-configuration will typically make `JvmGcMetrics` a bean, which will cause a reference to it to be maintained. Is that not happening in your application for some reason?

I tried to write a unit test to reproduce the behavior you mentioned, but this was not successful in reproducing the mentioned issue - the test passes. How easy is it to reproduce the issue for you? Could you write a unit test or provide a minimal sample project and instructions on how to reproduce it?

```java
@Test
void noRefCausesGaugesToDisappear() throws InterruptedException {
    // use a fresh registry, don't keep reference to JvmGcMetrics instance
    registry = new SimpleMeterRegistry();
    new JvmGcMetrics().bindTo(registry);
    System.gc();
    Thread.sleep(100);
    System.gc();
    assertThat(registry.find("jvm.gc.live.data.size").gauge().value()).isNotNaN();
    assertThat(registry.find("jvm.gc.max.data.size").gauge().value()).isNotNaN();
}
```

**Comment by archellix** [comment] 2023-01-31 12:11
Unfortunately, I can not do a test that would reproduce a similar situation. The problem can be reproduced stably only on our large and complex gateway. I guess, i need more time to research the problem in more detail. I will try to reproduce in some example.

PS
It's not entirely clear from your example what you mean. Did you change GC to Shenandoah or just run it on G1?
Why was Shenandoah GC removed from the title? The ticket only applies to this.

Thanks.

**Comment by shakuzen** [comment] 2023-02-06 05:13
I did run the test with Shenandoah, though it's not clear why the problem would be specific to a GC implementation. AFAIK behavior of `WeakReference` should be basically the same on any GC. I understand you may only be able to reproduce it when using Shenandoah with your application, but I think if it is possible to happen on Shenandoah, it is theoretically possible to happen on any GC implementation, unless the behavior is a bug in the GC. And any changes we make to fix this will be applicable regardless of GC used. If I'm wrong and this really is specific to expected difference in behavior with Shenandoah, we can add that back to the title. For now, I'd rather leave it more generic and perhaps others having the issue can find it and share the context in which they're seeing it.

**Comment by jonatan-ivanov** [comment] 2023-02-16 16:45
@archellix Is it possible that you can help us by checking two things?
- Is there any occurrence of `JvmGcMetrics` in you application code e.g.: do you register it on your own or Spring Boot creates a bean for you?
- Is it possible that you are not using Micrometer's `JvmGcMetrics` but a custom implementation registers the two disappearing gauges?
- What happens if you somehow keep a reference to `JvmGcMetrics` in your application?

**Comment by songxiaosheng** [comment] 2023-03-18 15:20
> I did run the test with Shenandoah, though it's not clear why the problem would be specific to a GC implementation. AFAIK behavior of `WeakReference` should be basically the same on any GC. I understand you may only be able to reproduce it when using Shenandoah with your application, but I think if it is possible to happen on Shenandoah, it is theoretically possible to happen on any GC implementation, unless the behavior is a bug in the GC. And any changes we make to fix this will be applicable regardless of GC used. If I'm wrong and this really is specific to expected difference in behavior with Shenandoah, we can add that back to the title. For now, I'd rather leave it more generic and perhaps others having the issue can find it and share the context in which they're seeing it.

if it  is  gc  the value will be "NaN", I think it  may  be other  reason

**Comment by marcingrzejszczak** [comment] 2023-12-20 16:40
There was no feedback since march. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-20 16:40 UTC
Labels: waiting for feedback, module: micrometer-core

**Comment by bambalooon** [comment] 2026-04-30 12:40
I've similar issue and it seems the root cause is that you init `liveDataSize = new AtomicLong();` in `bindTo` method, which in my case is called multiple times. So first time it inits to 0, and registers gauge for it, but then next call overrides `liveDataSize` field value to new AtomicLong and previous one can be garbage collected. Gauge isn't updated, because it already exists.
Other classes in this package like `JvmHeapPressureMetrics` have field initialized on class level so there is no issue with multiple calls to `bindTo`.
It applies to all fields in `JvmGcMetrics` class.

**Comment by jonatan-ivanov** [comment] 2026-05-01 19:06
@bambalooon That indeed can be a cause of seeing `NaN`, unfortunately if even if we initialize gauge state objects in the ctor, we still need the registry for initializing `GcMetricsNotificationListener`. I think we can collect them but it's a more significant change than initializing `AtomicLong` variables in the ctor.

I guess as a workaround doing this:
```java
new JvmGcMetrics().bindTo(registry1);
new JvmGcMetrics().bindTo(registry2);
```
instead of this:
```java
JvmGcMetrics jvmGcMetrics = new JvmGcMetrics();
jvmGcMetrics.bindTo(registry1);
jvmGcMetrics.bindTo(registry2);
```
should work.

Pease feel free to open a PR if you have a proposal to solve this.

**Comment by bambalooon** [comment] 2026-05-01 19:31
> [@bambalooon](https://github.com/bambalooon) That indeed can be a cause of seeing `NaN`, unfortunately if even if we initialize gauge state objects in the ctor, we still need the registry for initializing `GcMetricsNotificationListener`. I think we can collect them but it's a more significant change than initializing `AtomicLong` variables in the ctor.
> 
> I guess as a workaround doing this:
> 
> new JvmGcMetrics().bindTo(registry1);
> new JvmGcMetrics().bindTo(registry2);
> instead of this:
> 
> JvmGcMetrics jvmGcMetrics = new JvmGcMetrics();
> jvmGcMetrics.bindTo(registry1);
> jvmGcMetrics.bindTo(registry2);
> should work.
> 
> Pease feel free to open a PR if you have a proposal to solve this.

Thanks for the quick reply.
I don't control when bindTo is invoked so this solution doesn't work for me.
IMHO it's strange that you cannot init AtomicLong in the field like in other micrometer classes in this package.
```
private final liveDataSize = new AtomicLong();
```
This time I could just remove `prometheus-micrometer-registry` dependency, but this might not be a solution for everyone.

**Comment by jonatan-ivanov** [comment] 2026-05-01 20:44
>IMHO it's strange that you cannot init AtomicLong in the field like in other micrometer classes in this package.

I think I did not say we cannot initialize it, quite the opposite: "[...] even if we initialize gauge state objects in the ctor [...]". It is totally possible and it should be easy but this alone does not solve the issue, see the other parts of my comment.

>I don't control when bindTo is invoked so this solution doesn't work for me.

Are you using Spring Boot or any other framework? If so, you do have control over this, check the docs/auto-configuration.

**Comment by jonatan-ivanov** [comment] 2026-05-07 17:46
@bambalooon Do you have any updates on this? Did the above workaround work for you or not at all?
Are you using Spring Boot or any other frameworks?

**Comment by bambalooon** [comment] 2026-05-07 18:02
Hi, 
I use Spring Boot and we have massive corp project with few pom import dependencies. 
I've already wasted quite a bit investigating this issue and in my case I can affort to remove prometheus registry dependency so I've done it and everything works correctly.
I'm just informing you, because this one is quite annoying and someone else might have same problem in the future.

**Comment by jonatan-ivanov** [comment] 2026-05-08 20:55
If you don't need the Prometheus registry, please don't include it as a dependency regardless of this issue since even if nothing will scrape your Prometheus endpoint, having it will mean extra resource consumption (cpu and memory) because the Prometheus registry will keep records of your metrics.

I still think that the workaround above should work for Spring Boot app, but you need to override  what Boot does out of the box.
