### ISSUE TITLE
[Question] Possible unexpected behaviour when applying Meter to collector fails.

### ISSUE THREAD

**Issue by tgodinho** [micrometer-metrics/micrometer#2366] opened 2020-11-27 20:26 UTC
Hello guys,

I came across this behaviour when trying to register multiple meters with different set of tags.
Basically, I think that when we try to register a meter that fails the verification on line 414 (tags don't match), all the previously well-built meters will be scrapped; a direct consequence of returning `null` in `ConcurrentMap#compute`.

This behaviour caught me completely off guard. I was expecting the previous meters to remain untouched.
Is there any particular reason for this behaviour??

https://github.com/micrometer-metrics/micrometer/blob/def8d3d19d78f8b9aecaeb201e026a946583beec/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L405-L425

I know my use case is a bit messed up. I am basically overriding the [GuavaCacheBinder](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/GuavaCacheMetrics.java) to introduce counters for the reasons that led entries to be evicted. My approach was to replace the underlying eviction counter in the [CacheMeterBinder](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java) class with `N` counters with the same name but an additional `reason` tag.
It works great for the first cache, as I remove the old counter before adding the new ones. However, for the second cache, this behaviour causes the meters to be wiped out when the [CacheMeterBinder](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java) tries to register the old counter.

I'll have to play a bit with the API to see if I can get away with preventing the old meter to be registered in the first place.
Although, it is becoming clearer that this overriding approach might be troublesome in the future, specially when we start having multiple services registered in the same Prometheus instance.

BIG DISCLAIMER: I am a big noob, its basically my first day using this lib.

**Comment by shakuzen** [comment] 2021-01-25 06:32
Sorry for the delay in triaging this. It looks like this is the same as #2399 (meaning that one was a duplicate of this, actually), which we believe was fixed with #2400 to avoid the error. Note this comment https://github.com/micrometer-metrics/micrometer/issues/2399#issuecomment-764671514, though, which is that the different sets of labels will not show up in the scrape results currently. Pending some more exploration and testing, we're considering making those show up in the scrape results in the Micrometer 1.7 release timeframe, tentatively.
Duplicate of #2399

**Closed by shakuzen** 2021-01-25 06:32 UTC
Labels: duplicate, registry: prometheus
