### ISSUE TITLE
"system.cpu.usage" metric changed meaning after JDK upgrade

### ISSUE THREAD

**Issue by crmky** [micrometer-metrics/micrometer#2944] opened 2022-01-05 08:39 UTC
**Describe the bug**
Previously "system.cpu.usage" measures the system level CPU utilization even runs in a containerized environment. JDK changed its behavior in https://bugs.openjdk.java.net/browse/JDK-8265836 (https://github.com/openjdk/jdk8u/blob/master/jdk/src/solaris/classes/sun/management/OperatingSystemImpl.java#L82). Now behavior is very strange:
* If runs in a containerized environment with either quota or share applied (not the default 1024, refer to [this](https://github.com/openjdk/jdk8u/blob/master/jdk/src/linux/classes/jdk/internal/platform/cgroupv1/Metrics.java#L350)), it means container level CPU utilization.
* In other environment, it means system level CPU utilization.

**Environment**

 - Micrometer version: 1.3.20
 - Micrometer registry: prometheus
 - OS: Linux
 - Java version: openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

**To Reproduce**
How to reproduce the bug:
Runs application in a containerized environment with either quota or share set with:
* JDK 1.8.0_312+
* JDK 11.0.13+

**Expected behavior**
Since this is a JDK behavior change, I think Micrometer can only change metric description to match the behavior change.

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by jonatan-ivanov** [comment] 2022-01-05 19:07
System in `system.cpu.usage` always mean the "system" where your JVM is running in.
It can be a "native" Docker container, a Docker container inside a VM (Windows, MacOS), a VM (or a VM in a VM) or bare metal. Micrometer does not know about this and uses what the JVM tells it. The behavior of the JVM sounds pretty reasonable to me, I don't find it strange, in fact I found it strange before the fix and the JVM was not container-aware.

Right now the description of `system.cpu.usage` is
>The "recent cpu usage" for the whole system

What would you recommend instead of this?
Something like this?
>The "recent cpu usage" of the system the application is running in

Would you be open to create a PR?

**Comment by crmky** [comment] 2022-01-06 07:03
I would expect that metric to always measure at the same level, not sometimes at container level, sometimes at the system level (even if the applications are running inside a container). Currently most of our applications are running inside a container, we used to use this metric to measure the "background noise" which may impact application performance. After this JDK behavior change, I need to switch to use other metrics reported by ourselves.

The description looks good to me. I can create a PR for it.

**Comment by jonatan-ivanov** [comment] 2022-01-06 16:39
>I would expect that metric to always measure at the same level, not sometimes at container level, sometimes at the system level (even if the applications are running inside a container).

IMHO, sometimes this is not possible (e.g.: in a VM or in a container in a VM) and sometimes it is not practical (in a container). Please imagine that you have a cloud environment (let's say AWS) and you run your application in a VM (let's say on an EC2 instance). You will have no visibility on the physical machine that the EC2 is running on neither your application have. 
OpenJDK is Docker aware now and uses the container CPU/memory because that is the environment that limits it, not the host (or VM), please check these examples:

1. The JVM [sets](https://docs.oracle.com/en/java/javase/17/gctuning/ergonomics.html) the initial/max heap size based on the container memory limits. Setting this based on the host would be a mistake: let's say you have an EC2 instance that has 32GiB RAM and your container memory limit is 4GiB. The JVM will set the max heap to 1GiB (4/4) instead of 8GiB (32/4). Using the host memory (32GiB) and setting the max heap size based on it could lead to pretty bad consequences: the JVM would think the heap can grow to 8GiB but it can't. Also imagine this with multiple containers on the same instance
2. The JVM [sets](https://docs.oracle.com/en/java/javase/17/gctuning/ergonomics.html) the GC thread count, JIT compiler thread count, the common pool size (parallel stream, Fork/Join API, CompletableFuture) based on the CPU limitations of the container, the scenario is the same as in the case of memory above (except the memory limit is "hard" and leads to OOM kill while the CPU is "soft" and it leads to unnecessary throttling and resource drainage issues)

In your use case above, you need to install a "machine agent" on your hosts that does the host-level monitoring if you want to monitor your hosts.

I think modifying the description is a good idea, please go ahead and prepare a PR if you are up to. We can't really do anything with the behavior of `system.cpu.usage`, it is by design and the previous behavior in old OpenJDK versions was pretty dangerous.

**Comment by shakuzen** [comment] 2022-01-11 11:25
Thanks for the pull request. The updated description from #2969 will be included in the upcoming releases.

**Closed by shakuzen** 2022-01-11 11:25 UTC
Labels: type: task, module: micrometer-core
