### ISSUE TITLE
StatsdMeterRegistry unable to resolve dns updates. 

### ISSUE THREAD

**Issue by arohatgi** [micrometer-metrics/micrometer#2219] opened 2020-07-31 18:32 UTC
While running the statsD meter plugin, noticed that dns is not resolved. And even after dns update it keeps sending traffic to old dns. It is most probably due to host connection are not resolved and only when connection fails it recycles the connection. Ideally tcp client connection  should resolve the dns updates. 

>         TcpClient tcpClient = TcpClient.create()
>                 .host(statsdConfig.host())
>                 .port(statsdConfig.port())
>                 .handle((in, out) -> out
>                         .sendString(publisher)
>                         .neverComplete())
>                 .doOnDisconnected(connection -> connectAndSubscribe(tcpClientReference.get()));

Adding a dns resolver to  tcpClient should help resolve this.

_tcpClient.resolver(addressResolverGroup);_

**Comment by shakuzen** [comment] 2020-08-05 14:30
As far as I can tell, the Reactor Netty TcpClient will use a default resolver of `DefaultAddressResolverGroup`. Whatever the resolver, as far as my understanding, it will only be used when creating a new connection.

I'm reopening #1252 as I don't think it was ever resolved and it has some history on this feature request. I'll close this as a duplicate accordingly.
Duplicate of #1252

**Closed by shakuzen** 2020-08-05 14:30 UTC
