### ISSUE TITLE
How to record data between 0 and 1 using Histogram

### ISSUE THREAD

**Issue by ajain22** [micrometer-metrics/micrometer#2353] opened 2020-11-18 21:47 UTC
I am trying to capture data that lies between 0 and 1 using DistributionSummary. For doing so, I use below config,

DistributionStatisticConfig.builder()
			.percentilesHistogram(true)
			.maximumExpectedValue(1d)
			.minimumExpectedValue(0.001d)
			.serviceLevelObjectives(0.1,0.2,0.3,0.4,0.9,1)
			.expiry(Duration.ofMinutes(3))
                         .bufferLength(3)
			.build();

But when it always logs the data in the bucket le=1
What can i do so that the data like 0.20 gets logged in correct bucket i.e. from 0.3 to 1 ?

**Comment by shakuzen** [comment] 2021-03-26 11:57
Duplicate of #2341

**Closed by shakuzen** 2021-03-26 11:57 UTC
