### ISSUE TITLE
ElasticMeterRegistry: "failed to send metrics to elastic...only write ops with an op_type of create are allowed in data streams

### ISSUE THREAD

**Issue by cyrille-leclerc** [micrometer-metrics/micrometer#2286] opened 2020-10-09 17:18 UTC
I think I'm facing a problem related to https://github.com/micrometer-metrics/micrometer/issues/2255 .

## Context

* Spring Boot 2.3 application with Micrometer 1.5.5, Elasticsearch Meter Registry and Elasticsearch 7.9.2

```
management.metrics.export.elastic.host=http://localhost:9200
management.metrics.export.elastic.userName=***
management.metrics.export.elastic.password=***
```

## Error Description

Metrics are not sent to Elasticsearch and I get the following exception message:

```
2020-10-09 19:07:55.307 ERROR 10374 --- [trics-publisher] i.m.elastic.ElasticMeterRegistry         : 
failed to send metrics to elastic (sent 84 metrics but created 0 metrics): 
{"took":1315,"errors":true,"items":[
   {"index":{"_index":"metrics-2020-10","_type":"_doc","_id":null,"status":400,"error":
      {"type":"illegal_argument_exception","reason":"only write ops with an op_type of create are allowed in data streams"}}},
,...]}

```

My understanding is that the `metrics` index name, default index name used by the Elasticsearch Meter Registry, became the name of a datastream recently in Elasticsearch and should be handled differently.

**Comment by izeye** [comment] 2020-10-10 08:55
This seems to be a duplicate of #2255.

**Comment by shakuzen** [comment] 2020-10-12 06:55
Duplicate of #2255

**Closed by shakuzen** 2020-10-12 06:55 UTC
