### ISSUE TITLE
Actuator prometheus endpoint spring  stopped working after upgrading to 1.13

### ISSUE THREAD

**Issue by rohan-changejar** [micrometer-metrics/micrometer#5103] opened 2024-05-15 11:26 UTC
Actuator prometheus 

**Environment**
Production
Using this version https://mvnrepository.com/artifact/io.micrometer/micrometer-core/1.13.0
 - Micrometer version 1.13.
 - Micrometer registry prometheus 
 - OS: MacOs Sonoma
 - Java version: java 21.0.2 2024-01-16 LTS

How to reproduce the bug:
We upgraded the version of micrometer to 1.13 and this caused our actuator/prometheus endpoints to start failing. 
All other spring actuator endpoints continue to work, but this would throw an exception and fail.

**Expected behavior**
That this would continue to work as usual and metrics populated as expected

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by rohan-changejar** [comment] 2024-05-15 11:43
> What version of Spring Boot are you using? Typically, if you're using Spring Boot, you should allow its dependency management to manage the versions of dependencies unless you have a reason to override it. I believe Spring Boot 3.3.0 (scheduled to be released next week) will manage Micrometer dependencies to version 1.13.0.

We are using this version of spring `    id 'org.springframework.boot' version '3.2.5'`, do you see any correlation of this issue with this version? 

If it is related, would propose adding this as a warning on the migration guide. 

Let me know if I could be of any help here

**Comment by joethehoff** [comment] 2024-05-15 15:26
Same problem on my side using spring-boot 3.2.5
After upgrading to 1.13 there were no output at `localhost:9005/actuator/prometheus` anymore.
This are the management-props of application.properties
```
management:
  endpoint:
    health.enabled: true
    prometheus.enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: info, prometheus, health
  server:
    address: 0.0.0.0
    port: 9005
```
In sourecode we just use static Metrics-methods like this:
```
Metrics.counter("xxxx").increment();
```

**Comment by rohan-changejar** [comment] 2024-05-15 16:26
> @rohan-changejar If you can provide a link to code that reproduces the issue, that could be useful. Just a simple minimal product is fine.
> 
> Often when I try to create one, the underlying bug is revealed

Created a project demonstrating this issue,[]( https://github.com/rohan-changejar/demo-micrometer-bug).
You can use the main branch to reproduce the issue.
If you want to see the feature working on the previous version 
please refer the branch `[workingVersion](https://github.com/rohan-changejar/demo-micrometer-bug/tree/workingVersion)`


### on 1.12.6

<img width="1295" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/83759161/7025c139-83fe-4f91-a37a-19fe9e6a8569">


### on 1.13.0

<img width="1505" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/83759161/0359eee4-abb4-4b94-ae43-2b4149e0bf2b">

**Comment by ttddyy** [comment] 2024-05-15 17:50
@rohan-changejar Have you read the ["1.13 Migration Guide"](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide).
Also, this comment explains the background: https://github.com/micrometer-metrics/micrometer/issues/5093#issuecomment-2108940744

If you change the dependency from `micrometer-registry-prometheus` to `micrometer-registry-prometheus-simpleclient`, your sample works.

This is essentially a duplicate of https://github.com/micrometer-metrics/micrometer/issues/5093

**Comment by jonatan-ivanov** [comment] 2024-05-16 01:50
I would recommend letting Boot to set the version for libraries it has auto-configuration for (e.g. Micrometer). If you really want to migrate to Micrometer 1.13 with Bot 3.2 (btw 3.3 is coming next week with Micrometer 1.13 support), check Tadaya's comment, you need to change the name of the dependency when you change the version.

**Comment by jonatan-ivanov** [comment] 2024-05-16 01:50
Duplicate of https://github.com/micrometer-metrics/micrometer/issues/5093

**Closed by jonatan-ivanov** 2024-05-16 01:50 UTC
Labels: waiting for feedback

**Comment by shakuzen** [comment] 2024-05-16 08:46
I've added a [Frameworks section](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide#framework-compatibility) to the Migration Guide, including a sub-section for Spring Boot. Could folks who ran into this issue give us feedback on if those sections in the guide would have sufficiently explained the issue faced here? @rohan-changejar @joethehoff @IlyaLisov

**Comment by IlyaLisov** [comment] 2024-05-16 08:50
@shakuzen It is good explained and I found this really helpful. I think that sometimes some devs upgrading dependencies with minor/patch changes without any thoughts, so it could lead to such issues if there are no info in release notes
Thank you again! You helped me
