### ISSUE TITLE
Common tags duplicates meter tags.

### ISSUE THREAD

**Issue by ArtyomGabeev** [micrometer-metrics/micrometer#1019] opened 2018-11-19 16:54 UTC
Configuring common tags on registry level with combination of meter metrics leads to tags duplication.
Steps to reproduce:
1. Configure common metrics though meter registry config
2. Register metric with additional tags
3. Check registered metric id

The issue occurs in MeterFilter.commonTags which concatenates metric tags twice:
**meter tags + meter tags + common tags**

Issue found when I've tried to remove such metric from registry.
Removal logic applies all MeterFilters again, which leads to tags duplication again and break hashCode contract of Tags.class.

Example:
`
       
        SimpleMeterRegistry registry = new SimpleMeterRegistry();

        registry.config().commonTags("common-key", "common-value");

        Gauge gauge = Gauge.builder("test-gauge", () -> 0L)
                .tags("key", "value")
                .register(registry);

        System.out.print(gauge.getId());

        registry.remove(gauge);

        Assert.isTrue(registry.getMeters().isEmpty(), () -> "Registry is not empty");

`
Output:
> MeterId{name='test-gauge', tags=[tag(common-key=common-value),tag(key=value),tag(key=value)]}
> Exception in thread "main" java.lang.IllegalArgumentException: Registry is not empty

**Comment by izeye** [comment] 2018-11-19 22:52
@ArtyomGabeev Thanks for the report. This is a duplicate of #978.

**Closed by izeye** 2018-11-19 22:52 UTC

**Comment by tommyk-gears** [comment] 2020-11-25 20:04
I believe this issue is still valid and not really a duplicate of #978, `MeterFilter#commonTags` looks like this;

```java
    static MeterFilter commonTags(Iterable<Tag> tags) {
        return new MeterFilter() {
            @Override
            public Meter.Id map(Meter.Id id) {
                return id.withTags(Tags.concat(tags, id.getTagsAsIterable()));
            }
        };
    }
```

But, `Meter.Id#withTags` **concatenates** the provided tags to the existing tags. The code in `MeterFilter#commonTags` seems to assume that `Meter.Id#withTags` **replaces** the existing tags with the provided tags, hence doing an external concatenation.

Now, the tag deduplication works and hides the duplicate tags - but this thing just generates lots of duplicate tags (one duplicate per common tag, for each `Meter.Id` basically). Maybe not a big deal, but the solution is really simple, just remove the `Tags.concat` call from `MeterFilter#commonTags`;

```java
    static MeterFilter commonTags(Iterable<Tag> tags) {
        return new MeterFilter() {
            @Override
            public Meter.Id map(Meter.Id id) {
                return id.withTags(tags);
            }
        };
    }
```

**Comment by izeye** [comment] 2020-11-26 00:25
@tommyk-gears Thanks for the comment. The proposed change breaks the following test:

https://github.com/micrometer-metrics/micrometer/blob/133d359406054fb9afe08d0c6ff0c4288118caf5/micrometer-core/src/test/java/io/micrometer/core/instrument/composite/CompositeMeterRegistryTest.java#L144-L158

Looking at the test, the current arrangement seems to be intentional.

**Comment by tommyk-gears** [comment] 2020-11-26 11:57
Thanks for quick feedback! I should have executed some unit tests before suggesting a code change...

Anyway, as far as I understand we basically need to **prepend** the common tags in the filter in order for deduplication to filter out the correct tag in case of duplicates (deduplication keeps the *last* tag in the group if there ar duplicate keys), and `Meter.Id#withTags` **appends** the given tags which is why the test fails with my suggested change.

Wouldn't it be enough to use `replaceTags` + `concat` rather than `withTags` + `concat` in `commonTags` then?;
```java
    static MeterFilter commonTags(Iterable<Tag> tags) {
        return new MeterFilter() {
            @Override
            public Meter.Id map(Meter.Id id) {
                return id.replaceTags(Tags.concat(tags, id.getTagsAsIterable()));
            }
        };
    }
```

**Comment by izeye** [comment] 2020-11-26 12:23
@tommyk-gears Thanks for the suggestion. It looks good to me.

**Comment by izeye** [comment] 2020-12-05 00:49
I created https://github.com/micrometer-metrics/micrometer/pull/2370 to apply the suggestion from @tommyk-gears above.
