### ISSUE TITLE
HTTP server metrics in Apache CXF application show uri as UNKNOWN

### ISSUE THREAD

**Issue by catia-talend** [micrometer-metrics/micrometer#4571] opened 2024-01-15 14:51 UTC
**Describe the bug**
URI tag is always UNKNOWN for http_server_requests. cxf_server_requests are working fine, but not http_server_requests.

**Environment**
 - Micrometer version: 1.12.0
 - Micrometer registry: 1.12.0
 - Apache CXF: 4.0.3
 - Spring Boot: 3.1.1
 - Java version: openjdk version "17.0.2" 2022-01-18

**To Reproduce**
I have attached a [pet project](https://github.com/micrometer-metrics/micrometer/files/13829036/example.zip) to reproduce the issue. This example project is based on https://github.com/apache/cxf/tree/main/distribution/src/main/release/samples/jax_rs/spring_boot .

Run:
```
curl -s http://127.0.0.1:8080/services/sayHello/world
Hello world, Welcome to CXF RS Spring Boot World!!!

curl -s http://127.0.0.1:8080/services/notFound


curl -s http://127.0.0.1:8080/actuator/prometheus | grep requests_seconds_count
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 1.0
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="UNKNOWN",} 1.0
cxf_server_requests_seconds_count{exception="None",method="GET",operation="sayHello",outcome="SUCCESS",status="200",uri="/services/sayHello/{a}",} 1.0
```

**Expected behavior**
The URI should not be UNKNOWN for http_server_requests. An example:

```
curl -s http://127.0.0.1:8080/services/sayHello/world
Hello world, Welcome to CXF RS Spring Boot World!!!

curl -s http://127.0.0.1:8080/actuator/prometheus | grep requests_seconds_count
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="/services/sayHello/{a}",} 1.0
cxf_server_requests_seconds_count{exception="None",method="GET",operation="sayHello",outcome="SUCCESS",status="200",uri="/services/sayHello/{a}",} 1.0
```

**Additional context**
This problem was originally described [in this issue](https://github.com/micrometer-metrics/micrometer/issues/1364) . It dates from 2019 and although it has recent activity, the original poster has not provided more details.

**Comment by shakuzen** [comment] 2024-01-16 10:32
Thanks for the sample project to reproduce the issue. The `http.server.requests` metrics are coming from the Spring Framework observation instrumentation, whereas the `cxf.server.requests` metrics are coming from the CXF metrics instrumentation. I'm not sure why the `uri` is always unknown for the Spring Framework instrumentation in this case. Perhaps @bclozel has an idea.
There are two things (CXF's `MicrometerMetricsProvider` and Spring Framework) instrumenting the requests, and typically you would only want one because it is extra cost to instrument multiple times.

**Comment by bclozel** [comment] 2024-01-16 10:43
I think this is expected, as `http.server.requests` are meant to track Spring web endpoints - in this case, the application uses CXF `jakarta.ws.rs.*` so there is no way for the Spring Framework instrumentation to know about the mapped route pattern. `cxf.server.requests` probably has its own dedicated instrumentation that knows about CXF endpoints.

If this application is only using CXF for web endpoints, I would suggest disabling web observations in Spring.

**Comment by catia-talend** [comment] 2024-01-16 11:29
Thank you for the feedback. On the sample project, we added both (Spring and CXF) to show the discrepancies.
However for our real case, we absolutely need the Spring one, as we have both CXF endpoints and Spring (actuator).

**Comment by jonatan-ivanov** [comment] 2024-02-07 01:19
So if CXF handles the requests, would not make sense disabling the observability support in framework and use the one in CXF?

**Comment by EusebiuDev** [comment] 2024-02-08 13:40
We ran exactly into the same problem after upgrading vom spring boot 2.7.7 to 3.2.2. We are also using Spring and CXF endpoints, so we need the observability for both frameworks.
This also worked well bevor upgrading from the version mentioned above.

Environment **before** the upgrade

Micrometer version: 1.9.6
Micrometer registry: 1.9.6
Apache CXF: 3.5.5
Spring Boot: 2.7.7
Java version: temurin openjdk 17

Environment **after** the upgrade

Micrometer version: 1.12.2
Micrometer registry: 1.12.2
Apache CXF: 4.0.3
Spring Boot: 3.2.2
Java version: temurin openjdk 21

**Comment by catia-talend** [comment] 2024-02-08 13:55
> So if CXF handles the requests, would not make sense disabling the observability support in framework and use the one in CXF?

Because we are using Spring and CXF endpoints, we need the observability for both.

**Comment by bclozel** [comment] 2024-02-08 14:09
I don't think both can be applied anymore under the same name. Essentially, there is a duplicate instrumentation under the same metric name.
The only alternative would be to configure the Spring MVC instrumentation under one observation name, say `spring.http.server.requests` and the CXF one under `http.server.requests`. There is a similar issue with Jersey https://github.com/spring-projects/spring-boot/issues/39294

**Comment by catia-talend** [comment] 2024-02-19 16:06
Apache CXF group did a fix for this same issue last week. We'll upgrade CXF when the new version is released and monitor this issue.
Thank you.

**Comment by izeye** [comment] 2024-02-29 13:42
As @catia-talend said above, this seems to have been resolved via https://issues.apache.org/jira/browse/CXF-8963 and https://github.com/apache/cxf/pull/1671.

**Comment by jonatan-ivanov** [comment] 2024-03-01 01:04
Let me close the issue then, please let us know if you want us to reopen.

**Closed by jonatan-ivanov** 2024-03-01 01:04 UTC
Labels: waiting for feedback, feedback-reminder
