### ISSUE TITLE
StepMeterRegistry CountAtBucket values does not match timer.count.

### ISSUE THREAD

**Issue by jrask** [micrometer-metrics/micrometer#1070] opened 2018-12-14 15:06 UTC
We are seeing some really weird things in our system and here is a gist that boils this down. 

This example class uses SimpleMeterRegistry and a timer using sla:s. All durations are within the sla:s and therefor the value of the last bucket should match the timer.count value?

https://gist.github.com/jrask/52c70475ac744af56f88e43fab80a7c9

Here are some sample outputs

Timer.max is within SLA so,
**Why is the last CountAtBucket != Timer.count? I this expected behaviour**
````
Timer.builder("test__no__tag")
    .sla(Duration.ofMillis(100), Duration.ofMillis(200))

Timer.name, Timer.max,  "CountAtBucketValues",   Timer.count / HistogramSnapshot.count

test_with_tag, , max:198.0, bucket: 100.0 = 82.0, bucket: 200.0 = 159.0, Count:163/163
test_with_tag, , max:198.0, bucket: 100.0 = 84.0, bucket: 200.0 = 159.0, Count:163/163
test_with_tag, , max:198.0, bucket: 100.0 = 74.0, bucket: 200.0 = 158.0, Count:162/162
test__no__tag, , max:198.0, bucket: 100.0 = 251.0, bucket: 200.0 = 485.0, Count:488/488
````

**Comment by jkschneider** [comment] 2018-12-14 16:55
It believe this is a duplicate of https://github.com/micrometer-metrics/micrometer/issues/998.

**Closed** 2018-12-14 16:55 UTC
Labels: duplicate
