### ISSUE TITLE
Stackdriver type inferencing.

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#2160] opened 2020-06-19 13:11 UTC
> failed to send metrics to Stackdriver com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: Value type for metric custom.googleapis.com/jvm/classes/loaded must be INT64, but is DOUBLE.: timeSeries[42]; Value type for metric custom.googleapis.com/jvm/memory/committed conflicts with the existing value type (INT64).: timeSeries[2,3,5,12,13,26,31,76]; Value type for metric custom.googleapis.com/jvm/memory/used conflicts with the existing value type (INT64).: timeSeries[8,11,29,49,68,73,75,82]; Value type for metric custom.googleapis.com/jvm/threads/live must be INT64, but is DOUBLE.

Should we always force to a double the initial publish?

**Comment by jkschneider** [comment] 2020-06-19 13:11
https://micrometer-metrics.slack.com/archives/C662HUJC9/p1592556714328000

**Comment by VinodReddyE** [comment] 2020-06-26 10:13
@jkschneider  anyone started looking into it. we can do anything from stackdriver end?

**Comment by jkschneider** [comment] 2020-06-27 01:38
@VinodReddyE Haven't picked it up myself yet. Probably a fairly trivial fix in Micrometer just to always force to a double? Or Stackdriver could relax its constraint. Not sure what the storage/cost ramifications if any are in Stackdriver of integer vs. double.

**Comment by VinodReddyE** [comment] 2020-06-27 01:46
can we override any particular method and forced to double?  the challenge is we are not facing this issue in the test environment. the production we are facing this issue. any way to reproduce this. I enable the trace in a test environment to observe that double value. is stack driver its expecting int64?

**Comment by VinodReddyE** [comment] 2020-06-27 04:27
Not sure on stackdriver end. we first try to fix in the micrometer to force as double.

**Comment by VinodReddyE** [comment] 2020-06-29 15:46
createMetricDescriptorIfNecessary method we need to force the metric value type to Double initially if the next metric pushes INT64 also it will work. Strackdriver side I will try to delete the metric and will check.

**Comment by VinodReddyE** [comment] 2020-06-30 11:25
@jkschneider  issue got resolved in our end. I have deleted the metrics descriptor that is created with INT64. now its created with DOUBLE. permanent fix whoever newly using it should be double initially while creating descriptor.

**Comment by marcingrzejszczak** [comment] 2023-12-20 11:44
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-20 11:44 UTC
Labels: bug, registry: stackdriver
