### ISSUE TITLE
KafkaMetrics prevents the application from otherwise exiting

### ISSUE THREAD

**Issue by lyogev** [micrometer-metrics/micrometer#2301] opened 2020-10-22 05:52 UTC
I have the following application:
```java
@SpringBootApplication
public class Application {
	public static void main(String[] args) throws InterruptedException {
		SpringApplication.run(Application.class, args);
	}

	@Bean
	public Consumer<KStream<String, String>> consume() {
		return s -> {
			s.foreach((key, value) -> {
				throw new RuntimeException();
			});
		};
	}
}
```

As soon as I add to my gradle.build:
```gradle
 implementation 'org.springframework.boot:spring-boot-starter-actuator'
```

The application never exits.

This appears to be related to this:
> The issue is because Micrometer starts a non-daemon task scheduler in `KafkaMetrics`.
> That scheduler is stopped when the KafkaMetrics is closed (when the application context is stop()ped).
> The problem is, from a Spring perspective, the application is still running (the context is never stopped and the metrics never closed).
> Ultimately, perhaps, the fix needs to go in micrometer to use a daemon thread for its scheduler.

_Originally posted by @garyrussell in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/974#issuecomment-710640748_

**Comment by shakuzen** [comment] 2020-10-22 10:22
Could someone provide a minimal sample that I can run?

**Comment by garyrussell** [comment] 2020-10-22 14:13
Any code that creates a `KafkaMetrics` on the main thread and the main thread exits without closing the metric will exhibit the behavior, but here is the actual code that exhibits the behavior with spring cloud stream and Kafka Streams:

The commented-out code is the work-around:

```java
@SpringBootApplication
public class Application {

	private static final CountDownLatch latch = new CountDownLatch(1);

	public static void main(String[] args) throws InterruptedException {
		ConfigurableApplicationContext ctx = SpringApplication.run(Application.class, args);
//		latch.await();
//		ctx.close();
	}

//	@Bean
//	public StreamsBuilderFactoryBeanCustomizer customizer() {
//		return fb -> {
//			fb.setUncaughtExceptionHandler((thread, throwable) -> {
//				latch.countDown();
//			});
//		};
//	}

	@Bean
	public Consumer<KStream<String, String>> consume() {
		return s -> {
			s.foreach((key, value) -> {
				throw new RuntimeException();
			});
		};
	}

}
```
On start.spring.io, select `Cloud Stream` and `Spring for Apache Kafka Streams` - but here is the pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.4.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>soby2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>soby2</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by shakuzen** [comment] 2020-10-23 02:04
Thank you for the thorough description, @garyrussell. I was able to reproduce with that and confirm the proposed fix indeed resolves it.

**Closed** 2020-10-23 02:17 UTC
Labels: bug

**Comment by lyogev** [comment] 2020-11-05 11:01
Just tested this with micrometer 1.6.0 and it's still not working, still the application hangs before exit.

**Comment by garyrussell** [comment] 2020-11-05 18:11
@lyogev You (or something) must have started some other non-daemon thread(s). I just tested the application above with 1.6.0 and can confirm that it exits because the micrometer threads are now daemons...

<img width="347" alt="Screen Shot 2020-11-05 at 1 09 01 PM" src="https://user-images.githubusercontent.com/483832/98279668-3cad9200-1f68-11eb-890d-565604dd3f54.png">

Run your app in a debugger to figure out which non-daemon thread(s) are preventing the JVM from shutting down.
