### ISSUE TITLE
KafkaMetrics bindTo() method takes too long to return when many consumers are running

### ISSUE THREAD

**Issue by ivan-pronin** [micrometer-metrics/micrometer#2628] opened 2021-06-01 14:24 UTC
We have a microservice that creates around 50 consumers at start up, tech stack is spring-boot + spring-cloud-stream (kafka-client 2.4.1).
After upgrading **spring-boot**  from 2.2.7 (old) to 2.3.4 (new) service start up time increased drastically (on stage environments as well as on production): from ~130  seconds (on stage) to ~180+ seconds. It's ~50% increase in start up time and often it could hit 100%+ increase. It was unacceptable for our deployment pipeline: with 5 service instances overall deployment could took more than 30 minutes.
Long investigations showed that the reason was in metrics - e.g. fully excluding all metric libraries (including micrometer) from service helped to return start up time to normal values on spring-boot 2.3.4. 

Profiling showed that issue was in **io.micrometer.core.instrument.binder.kafka.KafkaMetrics#bindTo()** method:
* spring-boot-2.2.7 >>
![Spring-boot-2 2 7-kafka-2 4 1](https://user-images.githubusercontent.com/13690690/120331492-7f64fc00-c2f6-11eb-83f9-87b4934a3982.png)
* spring-boot-2.3.4 >>
![Spring-boot-2 3 4-kafka-2 4 1](https://user-images.githubusercontent.com/13690690/120331504-81c75600-c2f6-11eb-98ce-1ae27eabddb4.png)

* in old version DefaultKafkaConsumerFactory.createKafkaConsumer() method triggered init() method on KafkaConsumer and everything was fine
* in new version **MicrometerConsumerListener** was added with **KafkaClientMetrics.bindTo()** inside it. Assuming kafka-clients 2.4.1 are the same in both configurations, **bindoTo()** method is ~10 times longer than **KafkaConsumer.init()**. And within **bindTo()** its **checkAndBindMetrics(registry)** which causes such time degradation. 
* In practice, the more consumers are added, the more this time degradates. E.g. with 10 consumers our service started up quickly as before, but adding 30 + consumers slowed down start up greatly.

To showcase this behaviour I've created a PR with integration test https://github.com/micrometer-metrics/micrometer/pull/2629: io.micrometer.core.instrument.binder.kafka.**KafkaClientMetricsIntegrationTest**#measureConsumerBindingsTime() . Test starts up increasing number (from 50 to 800) of kafka consumers  with metrics and binds them to registry. Then it just prints to the console test's iteration time. The more consumers are binded, the longer it takes for new consumers to bind. This snowballs very quickly after 400+ consumers. This number may seem unrealistic, but it's just for integration test. In real application this happens on a couple of dozens of consumers.

To prove my initial thoughts on reasons of long bindTo() method execution, I've also created simple io.micrometer.core.instrument.binder.kafka.ScheduledCheckingKafkaMetrics class with commented out //checkAndBindMetrics(registry); . This way all meters binding will happen in scheduled executor, so I've called it "scheduled" - in contrast current KafkaMetrics implementation I've called "blocking"

And this proved my suggestions. Below is the list of test results for "**blocking**" metrics:
* Blocking: Total time taken per 50 consumers: PT0.919927S
* Blocking: Total time taken per 100 consumers: PT2.010049S
* Blocking: Total time taken per 200 consumers: PT8.541621S
* Blocking: Total time taken per 400 consumers: PT41.586698S
* Blocking: Total time taken per 800 consumers: PT4M38.136353S

In contrast, results for "**scheduled**" metrics:
* Scheduled: Total time taken per 50 consumers: PT0.765914S
* Scheduled: Total time taken per 100 consumers: PT0.854959S
* Scheduled: Total time taken per 200 consumers: PT3.723467S
* Scheduled: Total time taken per 400 consumers: PT12.362964S
* Scheduled: Total time taken per 800 consumers: PT1M25.222222S

Scheduled works much faster on 200+ consumers, but I was surprised that it was "not so fast". Actually, 1m 25 seconds is not what I expected from "async" non-blocking metrics. 
1. So, the **first issue** I see here is blocking nature of bindTo() method with **long executing of checkAndBindMetrics()**:  it's long execution can also be seen on screenshot. 
2. The **second** issue causes my "scheduled" metrics bindTo() method work also slowly with big consumers number. 

And 2nd reason is the **scheduler**: a new scheduler (single-threaded thread pool) is created per each metrics. So, with 200 consumers we have 200 different thread pools, which create new Thread objects and compute for resources. I've addressed this issue by creating shared thread pool: **io.micrometer.core.instrument.binder.kafka.ExecutorsService** and reusing it inside each metrics type. 

Below are results for "blocking" metrics on shared thread pool:
* Blocking: Total time taken per 50 consumers: PT0.674623S
* Blocking: Total time taken per 100 consumers: PT2.138005S
* Blocking: Total time taken per 200 consumers: PT7.204625S
* Blocking: Total time taken per 400 consumers: PT38.399049S
* Blocking: Total time taken per 800 consumers: PT4M43.48501S
For blocking it shows around 10% increase in performance. 

* Scheduled: Total time taken per 800 consumers: PT0.993452S 
For less consumers count results are similar: within milliseconds. This looks what can be expected from "async"non-blocking method. This fully makes bindTo() non-blocking

Sorry for such a long description, but I've tried to explain my thinking steps, tests and results.

## I see **2 main issues in current KafkaMetrics implementation**:
1.  Blocking nature of bindTo() method with some heavy computations inside checkAndBindMetrics(). My suggestion is either remove it completely by default - and scheduler will register all meters eventually, or create some property to exlude this method execution from bindTo(). This is the main blocker for our service to upgrade to spring-boot-3. Please, provide ability in micrometer to skip **checkAndBindMetrics()**  execution in **bindTo()**
1. Refactor schedulers implementation to reuse one shared thread pool

Thanks!

**Comment by ivan-pronin** [comment] 2021-07-26 11:31
Gyus, anyone plz take a look? @jonatan-ivanov @shakuzen

**Comment by vpanteleev** [comment] 2021-07-26 11:38
UP

Have a similar issue on my project, decided to rollback to the old spring-boot.

**Comment by jonatan-ivanov** [comment] 2021-08-28 01:11
@ivan-pronin Thank you for submitting this issue and for the investigation too!
I checked it and with a lot of consumers, I'm getting similar behavior.

I think this is because of two reasons:
1. The meter binder creates a lot of meters (87 per consumer so 100 will create 8700 meters while 400 will create 34800 meters)
2. The implementation of the meter binder is not optimal (partly because of kafka metrics)

Please take a look at this PR: https://github.com/micrometer-metrics/micrometer/pull/241 It improved a lot on the meter binder for me, here are some rough numbers only to see the magnitude of the duration before vs. after the change (not a perf tests):

```
100 (8700   meters):  ~1900ms vs.  ~650ms
200 (17400  meters):  ~6600ms vs. ~1000ms
300 (26100  meters): ~13700ms vs. ~1700ms
400 (34800  meters): ~23600ms vs. ~2000ms
```

**Comment by jonatan-ivanov** [comment] 2021-08-31 02:19
With https://github.com/micrometer-metrics/micrometer/pull/2416 being merged, could you please check if you still see this issue using the latest snapshots?

**Closed by jonatan-ivanov** 2021-08-31 02:19 UTC

**Comment by shakuzen** [comment] 2021-08-31 03:48
Duplicate of #2415

**Comment by ivan-pronin** [comment] 2021-09-10 07:51
@jonatan-ivanov  thank you very much for the fix - yes, it helped to bootstrap our service on the latest snapshot.
In the meantime, however, we've used another fix - with  ```MeterFilter``` we've excluded 28 consumer metrics and 19 producer metrics like this:
```
    @Bean
    public MeterFilter producerMetricFilter19() {
        return MeterFilter.denyMetricFor("kafka.producer.waiting.threads");
    }
```
Filtering out those metrics also helped.
We've waiting for this fix to be released!

**Comment by jonatan-ivanov** [comment] 2021-09-10 17:52
@ivan-pronin This should be released  mid next-week (15th Sept).
We are planning to look into the meters that are created by the binders too since it is blindly creating a Meter for every kafka Metrics resulting 165 (78+87) Meters in case of one consumer + one producer.
