### ISSUE TITLE
Make annotation MeterTag Repeatable

### ISSUE THREAD

**Issue by Sloggy** [micrometer-metrics/micrometer#5603] opened 2024-10-23 12:12 UTC
***Context***
Annotation `@MeterTag` can be used on method parameters in order to define tags on `@Timed` annotation.

***Issue***
Problem is `@MeterTag` is not Repeatable (cf `@Repeatable`), so, it is not possible to get more than one tag from the same parameter.

Exemple : My method take one parameter and I want to get 2 tags from it :

```java
@Timed("app.my.meter")
public void execute(
   @MeterTag(key = "foo", resolver = "FooResolver.class")
   @MeterTag(key = "bar", resolver = "BarResolver.class")
   Data data
) {
   //...
}
```

**Comment by jonatan-ivanov** [comment] 2024-10-23 21:22
I think this is a
Duplicate of https://github.com/micrometer-metrics/micrometer/issues/4081

Please let us know if you disagree and we can reopen if needed.

**Closed by jonatan-ivanov** 2024-10-23 21:22 UTC
Labels: waiting-for-triage
