### ISSUE TITLE
Why is the metric `jvm_gc_pause_seconds_count` missing in OpenJDK 11?

### ISSUE THREAD

**Issue by peterpilgrim** [micrometer-metrics/micrometer#2837] opened 2021-10-20 11:42 UTC
This is probably not a bug more of an investigation.

I asked on Twitter, but realised quickly it was better to ask my questions here

@micrometerio
 Question for you: `JvmGcMetrics.java` and OpenJDK 11 + is there a reason, why "jvm.gc.pause" does not get reported anymore? I am trying to track down the actual JMX instrumentation records 

For context, I am looking to connect to Prometheus so that Prom QL executes the following:

```
rate(jvm_gc_pause_seconds_sum{namespace="$namespace", instance="$instance"}[1m])/rate(jvm_gc_pause_seconds_count{namespace="$namespace", instance="$instance"}[1m])  
```

I don't see the metrics at all `jvm_gc_pause_seconds_count`  generated in the controller / servlet output. So I conclude `JvmGcMetrics.java` is not picking up the GC JMX instrumentation beans ie. notifications at all.

My current code uses the current form

```java
   new JvmGcMerics().bindTo(registry)
```

In JDK 11 the G1 collector is favoured (JDK 17 I already know this is the default), old CMS collectors are deprecated. I immediately wonder if this was simple case of the collector changing across the GC implementations / infrastructure and environment. 

From reading code, `JvmGcMetrics` is looking into JMX Beans, can somebody point me to a decent example?

Thanks I know you are all busy guys (and gals).

**Comment by peterpilgrim** [comment] 2021-11-05 12:13
I can't give you the application. I can tell you our environment

```
❯ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

secret project on  feature/ACME-276 [$] via 🐳 default via ☕ v11.0.11 on ☁️  (eu-west-2) 
❯ uname -a
Darwin AMBGB000222 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

I used this JVM properties

```
-Xmx2560m  -Dcom.sun.management.jmxremote=true  -Djava.rmi.server.hostname=127.0.0.1  -Dcom.sun.management.jmxremote.port=6006  -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.local.only=false   -verbose:gc -Xloggc:/tmp/liferaygc1.log -XX:+PrintGCDetails  
```

So we are using the G1 garbade collector.

I would to have some example JMX bean code that reveals the collector information for the GC. I could then run in it a thread similar to this:

```java

            final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
            executorService.scheduleAtFixedRate( ()-> {
                System.out.printf("%s Execute System.gc()\n", new Date());
                System.gc();
            }, 15, 15, TimeUnit.SECONDS);

```

I just don't see these metrics reported.

**Comment by shakuzen** [comment] 2021-11-05 12:26
No need to share your exact application, but if we can't otherwise figure it out, we will need some code that reproduces the issue, ideally in as minimal of a sample application as possible. Do you have the same issue if you make a new project that is as minimal as possible?

Is there anything in the logs like `GC notifications will not be available`?

**Comment by SimSonic** [comment] 2021-11-19 09:48
Hi!
I've created [this issue](https://github.com/spring-projects/spring-boot/issues/28742) but has been redirected to your project.
Should I create separate bug or this seems to be bound with current issue?

**Comment by shakuzen** [comment] 2021-11-23 08:45
@SimSonic I don't think it's related to this issue. Please make a separate issue. Though from a quick look, I would say to make sure that Micrometer is returning 0 values where you see the graph going to zero and it isn't failed scrapes from Prometheus combined with the graphs treating null as zero.

**Comment by SimSonic** [comment] 2021-11-23 09:06
@shakuzen No, zeros are returned from `/actuator/prometheus` endpoint.

Ok, I'll create it later.

**Comment by peterpilgrim** [comment] 2021-11-23 10:57
I don't see anything like `GC Notifications will not be available` at all in the logs. 

```
/Users/m_agicuser/.sdkman/candidates/java/11.0.11.hs-adpt/bin/java -Dcatalina.base=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17 -Dcatalina.home=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17 -Dfile.encoding=UTF8 -Djava.io.tmpdir=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/temp -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Duser.timezone=GMT -Xmx2560m -Dcom.sun.management.jmxremote=true -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=6006 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -verbose:gc -Xloggc:/tmp/liferaygc1.log -XX:+PrintGCDetails -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=60538:/Applications/IntelliJ IDEA.app/Contents/bin -classpath /Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/bin/bootstrap.jar:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/bin/tomcat-juli.jar:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/bin/commons-daemon.jar org.apache.catalina.startup.Bootstrap start
[0.005s][warning][gc] -Xloggc is deprecated. Will use -Xlog:gc:/tmp/liferaygc1.log instead.
[0.005s][warning][gc] -XX:+PrintGCDetails is deprecated. Will use -Xlog:gc* instead.
[0.014s][info   ][gc] Using G1
[0.666s][info   ][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 25M->6M(256M) 5.214ms
23-Nov-2021 10:43:36.670 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [359] milliseconds
[0.881s][info   ][gc] GC(1) Pause Young (Concurrent Start) (Metadata GC Threshold) 22M->10M(256M) 4.772ms
[0.881s][info   ][gc] GC(2) Concurrent Cycle
[0.887s][info   ][gc] GC(2) Pause Remark 11M->11M(256M) 1.323ms
[0.889s][info   ][gc] GC(2) Pause Cleanup 11M->11M(256M) 0.061ms
[0.890s][info   ][gc] GC(2) Concurrent Cycle 9.138ms
[1.052s][info   ][gc] GC(3) Pause Young (Normal) (G1 Evacuation Pause) 21M->11M(256M) 5.604ms
[1.514s][info   ][gc] GC(4) Pause Young (Normal) (G1 Evacuation Pause) 67M->24M(256M) 6.019ms
Loading jar:file:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.liferay.petra.reflect.ReflectionUtil (file:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/lib/ext/com.liferay.petra.reflect.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of com.liferay.petra.reflect.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading jar:file:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
Loading file:/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/portal-ext.properties
2021-11-23 10:43:38.524 INFO  [main][PortalContextLoaderListener:139] JVM arguments: -Dcatalina.base=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17 -Dcatalina.home=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17 -Dfile.encoding=UTF8 -Djava.io.tmpdir=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/temp -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/Users/m_agicuser/Projects/ACME/ned/ACME-analytics-tool-liferay/bundles/liferay-ce-portal-7.3.0-ga1/tomcat-9.0.17/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Duser.timezone=GMT -Xmx2560m -Dcom.sun.management.jmxremote=true -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=6006 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -verbose:gc -Xloggc:/tmp/liferaygc1.log -XX:+PrintGCDetails -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=60538:/Applications/IntelliJ IDEA.app/Contents/bin
[2.779s][info   ][gc] GC(5) Pause Young (Normal) (G1 Evacuation Pause) 170M->29M(256M) 6.218ms
[2.803s][info   ][gc] GC(6) Pause Young (Normal) (G1 Evacuation Pause) 170M->29M(256M) 5.041ms
[2.820s][info   ][gc] GC(7) Pause Young (Normal) (G1 Evacuation Pause) 177M->29M(256M) 2.662ms
[2.837s][info   ][gc] GC(8) Pause Young (Normal) (G1 Evacuation Pause) 177M->29M(256M) 2.184ms
[2.853s][info   ][gc] GC(9) Pause Young (Normal) (G1 Evacuation Pause) 177M->29M(256M) 2.617ms
[3.105s][info   ][gc] GC(10) Pause Young (Normal) (G1 Evacuation Pause) 179M->43M(256M) 11.004ms
[4.449s][info   ][gc] GC(11) Pause Young (Concurrent Start) (Metadata GC Threshold) 182M->87M(308M) 33.203ms
[4.449s][info   ][gc] GC(12) Concurrent Cycle
[4.473s][info   ][gc] GC(12) Pause Remark 88M->87M(308M) 2.444ms
[4.489s][info   ][gc] GC(12) Pause Cleanup 88M->88M(308M) 0.092ms
[4.490s][info   ][gc] GC(12) Concurrent Cycle 41.566ms
2021-11-23 10:43:40.487 INFO  [main][DialectDetector:159] Using dialect org.hibernate.dialect.PostgreSQLDialect for PostgreSQL 13.3
2021-11-23 10:43:40.536 INFO  [main][DBInitUtil:171] Create tables and populate with default data
```

Everything looks tickety boo with these JVM arguments to our Liferay Application: 

```
-Xmx2560m  -Dcom.sun.management.jmxremote=true  -Djava.rmi.server.hostname=127.0.0.1  -Dcom.sun.management.jmxremote.port=6006  -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.local.only=false   -verbose:gc -Xloggc:/tmp/liferaygc1.log -XX:+PrintGCDetails  
```

**Comment by jonatan-ivanov** [comment] 2021-11-24 00:43
@peterpilgrim Could you please create a minimal sample app that can repro the issue so that we can troubleshoot this?

**Comment by peterpilgrim** [comment] 2021-11-24 21:32
This is a liferay application. It is proprietary, so for us it definitely the wrong approach. 
What I need a sample JMX example that I can run inside my application? Or point me to the correct JMX resources so I can dig deeper please.

**Comment by jonatan-ivanov** [comment] 2021-11-24 22:13
I did not ask for your proprietary application, I asked for a new, _minimal_ sample. A simple and minimal (maven/gradle) project that can reproduce the issue.

This is important and it can be as simple as `new JvmGcMerics().bindTo(registry)` in a psvm app in a new repo or a failing test in Micrometer or a new Sample in our samples, something that we can debug and narrow down the problem.

**Comment by shakuzen** [comment] 2021-11-25 04:53
> This is a liferay application.

Could you take a liferay sample application that is openly available, add Micrometer to it, and see if it has the same issue you're seeing in your application? I came across [this liferay-blade-samples repo](https://github.com/liferay/liferay-blade-samples), but I'm not familiar with Liferay. If you can reproduce the issue by adding Micrometer to a sample like one of the ones in that repo and share instructions on how to run it, it will be much easier for us to investigate.

**Comment by peterpilgrim** [comment] 2021-11-30 11:41
Ok ok. I will take a look at this. I might be awhile ...

**Comment by apadigal** [comment] 2022-04-26 09:55
Any chance, this been resolved? I have the same issue that I can't see the pause count in micrometer Prometheus  endpoint.

**Comment by shakuzen** [comment] 2022-04-26 10:03
@apadigal if you can provide a sample application that we can run to reproduce the issue, we can probably find the cause, but so far we have not been able to reproduce it.

**Comment by kuldeepjain** [comment] 2022-05-24 19:24
I see the same issue, don't see `jvm_gc_pause_seconds_count`. I don't have a minimal setup reproducing it though.

**Comment by jonatan-ivanov** [comment] 2022-05-25 20:57
**Could you please try if the code below produces any outputs for you?**

It needs Micrometer at least 1.9.0 (so we can ensure it is up to date) and it should print out 20+ lines if the metric is missing (so that we can ensure that a minimal sample works on your JVM).

**If this sample produces any outputs, please let us know in the comments.**
(You might want to run it a few times if you see any outputs since `System.gc()` might not trigger the GC.)

**If it does not produce any outputs, the metric is there and everything works as expected.**
If you have an app though where you cant see the metric, could you please provide us a minimal sample project in a GitHub repo that can reproduce this issue so we can investigate this further and ensure any fix is working properly for your use case?

```java
import java.lang.management.GarbageCollectorMXBean;
import java.lang.management.ManagementFactory;
import java.util.Arrays;
import java.util.List;

import io.micrometer.core.instrument.binder.jvm.JvmGcMetrics;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;

public class Demo {
    public static void main(String[] args) throws InterruptedException {
        SimpleMeterRegistry registry = new SimpleMeterRegistry();
        new JvmGcMetrics().bindTo(registry);
        System.gc();
        Thread.sleep(3_000);

        if (!registry.getMetersAsString().contains("jvm.gc.pause")) {
            System.out.println(registry.getMetersAsString());

            System.getProperties().entrySet().stream()
                .filter(entry -> String.valueOf(entry.getKey()).contains("java"))
                .forEach(System.out::println);

            List<GarbageCollectorMXBean> gcMXBeans = ManagementFactory.getGarbageCollectorMXBeans();
            for (int i = 0; i < gcMXBeans.size(); i++) {
                GarbageCollectorMXBean gcMXBean = gcMXBeans.get(i);
                System.out.println("gc." + i + ".name=" + gcMXBean.getName());
                System.out.println("gc." + i + ".objectName=" + gcMXBean.getObjectName());
                System.out.println("gc." + i + ".collectionCount=" + gcMXBean.getCollectionCount());
                System.out.println("gc." + i + ".collectionTime=" + gcMXBean.getCollectionTime());
                System.out.println("gc." + i + ".memoryPoolNames=" + Arrays.toString(gcMXBean.getMemoryPoolNames()));
            }
        }
    }
}
```

**Comment by peterpilgrim** [comment] 2022-05-27 15:58
I ran this version on my local MBP with OpenJDK Temurin
```
 11.0.14      | tem     | local only | 11.0.14-tem
```
My version of the program is:

```java
package uk.gov.hmpo.investigation;

import java.lang.management.GarbageCollectorMXBean;
import java.lang.management.ManagementFactory;
import java.util.Arrays;
import java.util.List;

import io.micrometer.core.instrument.binder.jvm.JvmGcMetrics;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;

public class InstrumentationGCPauseDemo {
    public static void main(String[] args) throws InterruptedException {
        SimpleMeterRegistry registry = new SimpleMeterRegistry();
        new JvmGcMetrics().bindTo(registry);

        System.out.println("======================================================================");
        System.out.println("Suggest running Garbage Collector");
        System.gc();
        System.out.println("sleep ....");
        Thread.sleep(3_000);
        System.out.println("======================================================================");
        System.out.println(registry.getMetersAsString());
        System.out.println("======================================================================");

        if (!registry.getMetersAsString().contains("jvm.gc.pause")) {

            System.out.println("Does not contain jvm.gc.pause");

            System.getProperties().entrySet().stream()
                    .filter(entry -> String.valueOf(entry.getKey()).contains("java"))
                    .forEach(System.out::println);

            List<GarbageCollectorMXBean> gcMXBeans = ManagementFactory.getGarbageCollectorMXBeans();
            for (int i = 0; i < gcMXBeans.size(); i++) {
                GarbageCollectorMXBean gcMXBean = gcMXBeans.get(i);
                System.out.println("gc." + i + ".name=" + gcMXBean.getName());
                System.out.println("gc." + i + ".objectName=" + gcMXBean.getObjectName());
                System.out.println("gc." + i + ".collectionCount=" + gcMXBean.getCollectionCount());
                System.out.println("gc." + i + ".collectionTime=" + gcMXBean.getCollectionTime());
                System.out.println("gc." + i + ".memoryPoolNames=" + Arrays.toString(gcMXBean.getMemoryPoolNames()));
            }
        }
    }
}


```

I get this output 

```
> Task :InstrumentationGCPauseDemo.main()
16:55:41.507 [main] DEBUG io.micrometer.core.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
======================================================================
Suggest running Garbage Collector
sleep ....
======================================================================
jvm.gc.live.data.size(GAUGE)[]; value=2074184.0 bytes
jvm.gc.max.data.size(GAUGE)[]; value=4.294967296E9 bytes
jvm.gc.memory.allocated(COUNTER)[]; count=7340032.0
jvm.gc.memory.promoted(COUNTER)[]; count=2074184.0
jvm.gc.pause(TIMER)[action='end of major GC', cause='System.gc()']; count=1.0, total_time=0.007 seconds, max=0.007 seconds
======================================================================
```

So obviously the metric is there. I guess is it pausing stuff. We need a longer running program. 

I had another thought: is this a JVM flag issue?  https://chriswhocodes.com/

**Comment by jonatan-ivanov** [comment] 2022-05-27 20:46
@peterpilgrim Thank you for trying this out. In order to narrow down the difference between you app in prod and your local demo, I have a few ideas:
- Try to start your liferay app locally
- Try to trigger GC manually on your liferay app
- Try to run your demo app using the same JVM, same OS, same JVM args
- Check if `JvmGcMetrics` is bound the registry, also check if it is bound to the right registry (you might have multiple ones)
- You are running on OpenJDK HotSpot, right? So no Graal/SubstrateVM or any other native solutions?

**Comment by owaiscs001** [comment] 2023-11-28 08:28
@jonatan-ivanov I'm facing the same issue I tried the above program and it produced an output. I'm using Micrometer 1.9.16.
Maybe some JVM args are missing. Can you provide some help here, what to do next?

System.out.println(registry.getMetersAsString()); This is empty.

Other parameters are giving the below value: 
i 1, gcMXBean.getName() G1 Old Generation, gcMXBean.getObjectName() java.lang:type=GarbageCollector,name=G1 Old Generation, gcMXBean.getCollectionTime() 12801, Arrays.toString(gcMXBean.getMemoryPoolNames()) [G1 Eden Space, G1 Survivor Space, G1 Old Gen]

**Comment by shakuzen** [comment] 2023-11-29 02:13
@owaiscs001 ideally if you could provide a minimal sample application with instructions on how to run it to reproduce the issue, we could likely find the cause. Without that, it's not so easy to say. What JRE are you using? What arguments are you passing? Are you running the application in an application server? If so, which?

**Comment by owaiscs001** [comment] 2023-11-29 05:35
I have a spring boot application running on the Kubernetes cluster.
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
java VM: HotSpot
Spring boot version: 2.7.17

JVM parameters I pass in the application:
-XX:+UseStringDeduplication  -XX:+AlwaysPreTouch -Xloggc:/tmp/app_gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/app_heap_dump.bin 

Since my application size is large and even needs many things to run a sample program. I was hoping to get something to try, which can help in narrowing the issue.

Any help here would be appreciated.

**Comment by owaiscs001** [comment] 2023-11-29 06:59
Also, I'm able to fetch  jvm_gc_overhead_percent metric. But below three metrics are not available:
jvm_gc_collection_seconds_count
jvm_gc_collection_seconds_sum
jvm_gc_collection_seconds

**Comment by shakuzen** [comment] 2024-10-04 02:14
@owaiscs001 based on the information provided, the only reason I can think for the metrics to be missing would be there hasn't been a GC since the metrics were registered or the runtime (JVM) you are using does not support the GC notification events. I think unfortunately without something we can reproduce, we aren't going to be able to get to the bottom of this. If someone can provide a minimal sample we can run to reproduce the issue, we can reopen and investigate further, but I will close the issue for now.

**Closed by shakuzen** 2024-10-04 02:14 UTC
Labels: bug, module: micrometer-core, feedback-provided
