### ISSUE TITLE
LogbackMetrics break down when triggered ContextRefresher#refresh()

### ISSUE THREAD

**Issue by 879913935** [micrometer-metrics/micrometer#2427] opened 2021-02-05 02:04 UTC
Normally, LogbackMetrics add an MetricsTurboFilter to LoggerContext, so LOGGER.xxx() can record log count.

But when SpringCloud ContextRefresher#refresh() triggered,  **TurboFilter was removed!**

ContextRefresher#refresh() -> ... -> LogbackLoggingSystem#stopAndReset(LoggerContext loggerContext)

-> LoggerContext#stop() -> LoggerContext#reset() ->  **LoggerContext#resetTurboFilterList()**

So once the context refresh event was triggered, LogbackMetrics is break down, the metrics  **logback_events_total**  exposed by  **/actuator/prometheus**  is never changed unless restart.

**Comment by izeye** [comment] 2021-02-06 23:55
This seems to be a duplicate of https://github.com/micrometer-metrics/micrometer/issues/564.

**Comment by jonatan-ivanov** [comment] 2021-02-08 21:28
@879913935 I'm closing this since from #564, it seems it is not an issue with micrometer.
Could you please upgrade to the [latest spring-cloud ](https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-dependencies) and try this again? if it still an issue, please check the connected issue in #564 or create a new one for spring-cloud-commons.

**Closed by jonatan-ivanov** 2021-02-08 21:28 UTC

**Comment by wuguanyu** [comment] 2021-11-12 09:26
> LogbackLoggingSystem

ContextRefresher#refresh() -> ... -> LogbackLoggingSystem#stopAndReset(LoggerContext loggerContext)

... Can we see detail ?

**Comment by wuguanyu** [comment] 2021-11-12 10:08
![wecom-temp-da975f7e8db2bf6261b95edfb72c00b8](https://user-images.githubusercontent.com/24486917/141449562-c20d7ef4-1afe-48a6-a915-40963e60e75a.png)
