### ISSUE TITLE
Support for removing a Meter from the MeterRegistry

### ISSUE THREAD

**Issue by adoelger** [micrometer-metrics/micrometer#368] opened 2018-01-25 11:41 UTC
Support for removing a Meter from the MeterRegistry. Like DropWizard Metrics -> MetricRegistry.remove().

**Comment by jkschneider** [comment] 2018-01-25 14:14
@adoelger I think this is just now becoming possible. Originally, Prometheus had a strong opinion about never removing metrics during a running app. That is no longer true in Prometheus 2.

There is something else driving this change, which is _cost_ in CloudWatch. See #303.

**Comment by jkschneider** [comment] 2018-02-14 15:26
Whenever we tackle this, remember that some implementations (like Timers with percentiles in the Dropwizard implementation) generate nested meters. Somehow there would have to be an association drawn between meters like this so that when we remove the Timer meter, we also remove the Gauges representing its percentiles.

**Comment by jkschneider** [comment] 2018-10-11 20:19
Duplicate of #479.

**Closed by jkschneider** 2018-10-11 20:19 UTC
