### ISSUE TITLE
Micrometer Timer

### ISSUE THREAD

**Issue by 595979101** [micrometer-metrics/micrometer#1064] opened 2018-12-10 03:24 UTC
I used springboot2.1 actuator to collect Timer data.But at one point the number of calls increased by more than a billion.But that's impossible.Another phenomenon is that this Timer is the only one with problems, and the accident occurred when Prometheus called the Prometheus/Prometheus interface without data. After that, the data exploded and increased for about 5 minutes.Can you help me analyze this problem?thank you
![image](https://user-images.githubusercontent.com/38642570/49709129-dcbfeb00-fc6d-11e8-9cdd-961d599e781c.png)

![image](https://user-images.githubusercontent.com/38642570/49709188-1d1f6900-fc6e-11e8-8b50-609d2569934b.png)

**Comment by shakuzen** [comment] 2019-03-22 06:27
Duplicate of #844

**Closed by shakuzen** 2019-03-22 06:27 UTC
Labels: duplicate

**Comment by Staniel** [comment] 2021-07-29 03:02
Hi, I am recently starting to use Micrometer in my Java app('micrometer-registry-jmx', version: '1.7.0'), and I have been constantly observing huge spike on oneMinuteRate metrics everytime when the cluster is re-deployed. I have 100 instances running in a cluster and reporting metrics using Timer, the one minute rate sum is generally ~200, however when re-deployed, the spike could reach 1B. With some research I come to this thread but it seems the default pause detector is already changed. Is there anything else could cause this symptom?

**Comment by shakuzen** [comment] 2021-07-29 03:42
> Is there anything else could cause this symptom?

Not that we're aware of. Feel free to open a new issue with details, though it sounds like it may be hard to reproduce.
