### ISSUE TITLE
spring-boot-actuator io.micrometer.core.instrument.MeterRegistry#meterMap OOM

### ISSUE THREAD

**Issue by youzipi** [micrometer-metrics/micrometer#1117] opened 2019-01-03 08:53 UTC
I got OOM when using `spring-boot-admin`
after I analyze the heap dump.
I found the problem is the SimpleMeterRegistry.meterMap fill the memory and after many times GC, the map content still alive.

![](https://user-images.githubusercontent.com/5629307/50582024-229d5700-0e9a-11e9-9e16-179d61bbe662.png)

![image](https://user-images.githubusercontent.com/5629307/50628280-695e8000-0f72-11e9-8fe9-45eafe418174.png)

![image](https://user-images.githubusercontent.com/5629307/50628558-86e01980-0f73-11e9-8a4e-79a5fcaf08f9.png)

I only found one way to clear the meterMap here: `io.micrometer.core.instrument.MeterRegistry#close`

```java
       /**
     * Closes this registry, releasing any resources in the process. Once closed, this registry will no longer
     * accept new meters and any publishing activity will cease.
     */
    @Override
    public void close() {
        if (closed.compareAndSet(false, true)) {
            synchronized (meterMapLock) {
                for (Meter meter : meterMap.values()) {
                    meter.close();
                }
            }
        }
    }
```
In `org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter`, the ·registry` not 
call `close` and from the name `MetricsWebFilter` I think it won't be destoried until the server close.

related code:
```java
	private void success(ServerWebExchange exchange, long start) {
		Iterable<Tag> tags = this.tagsProvider.httpRequestTags(exchange, null);
		this.registry.timer(this.metricName, tags).record(System.nanoTime() - start,
				TimeUnit.NANOSECONDS);
	}
```
I wonder where and when the `timer` here be released?
I do not start a spring-boot-admin-server.
I assume that the timer not be consumed because there is no server side to fetch it ? or there is a strategy  to clear these timer?

more snapshot in my notes:
https://github.com/youzipi/notes/issues/3

## environment
spring-boot-admin-client  2.0.1
spring-boot-actuator  2.0.0 RELEASE
micrometer-core  1.0.1

**Comment by izeye** [comment] 2019-01-03 09:46
This might be a duplicate of https://github.com/spring-projects/spring-boot/issues/12685 which has been resolved in Spring Boot 2.0.1.RELEASE.

@youzipi Could you try Spring Boot 2.0.7.RELEASE which is the latest version in the 2.0.x line?

**Comment by youzipi** [comment] 2019-01-09 07:45
tks
It's a problem with `spring-boot-actuator` and `spring-cloud-gateway`, have no business with micrometer.

The https://github.com/spring-projects/spring-boot/issues/12685 's PR do not solve the probloem completely.

I create an issue in spring-boot project , and it has been solved.
related issue and PR here:
https://github.com/spring-projects/spring-boot/pull/15609

someone with same problem leaded to here can go to above link for solution and discussion.

issue should be closed @izeye

**Comment by izeye** [comment] 2019-01-09 09:08
@youzipi Thanks for letting us know. Closing

**Closed by izeye** 2019-01-09 09:08 UTC
Labels: question
