### ISSUE TITLE
DatadogMeterRegistry didn't send the correct counter metric's value when close registry earlier than the 'step'

### ISSUE THREAD

**Issue by phucnh** [micrometer-metrics/micrometer#1548] opened 2019-08-18 17:06 UTC
When the `DatadogMeterRegistry` is closed earlier than `DatadogConfig#step`, seems that the counter's value is not set correctly.

For example:
- I init the DatadogConfig with `step` is 10 seconds (Flushing metric interval)
- I define a `DatadogMeterRegistry` and create a `counter`
- Increment `counter` by `counter.increment()`
- Wait 1 second and call `registry.close()`
- The `counter` that is published with value is `0.0` (But I think the published value should be `1.0`)

The example code is as follows:

```java
package com.example;

import io.micrometer.core.instrument.Clock;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.datadog.DatadogConfig;
import io.micrometer.datadog.DatadogMeterRegistry;
import java.time.Duration;
import java.util.concurrent.TimeUnit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.LoggerContext;

class DatadogMeterRegistryTest {
    private final static Logger logger = LoggerFactory.getLogger(DatadogMeterRegistryTest.class);

    public static void main(String args[]) throws InterruptedException {
        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
        loggerContext.getLogger("root").setLevel(Level.TRACE);

        final DatadogConfig config = new DatadogConfig() {
            @Override
            public boolean enabled() {
                return true;
            }

            @Override
            public String apiKey() {
                return "my-api-key";
            }


            @Override
            public String applicationKey() {
                return "my-application-key";
            }

            @Override
            public String get(String k) {
                return null; // accept the rest of the defaults
            }

            @Override
            public Duration step() {
                return Duration.ofSeconds(10);
            }
        };

        MeterRegistry registry = new DatadogMeterRegistry(config, Clock.SYSTEM);

        Counter counter = registry.counter("my.counter.sample");

        counter.increment(3);
        System.out.println("counter value is: " + counter.count());

        Thread.sleep(1 * 1000); // Wait 1 second

        System.out.println("Closing registry...");
        registry.close();
        System.out.println("After close registry, counter value is: " + counter.count());
    }
}
```

The execution result is:
```console
[info] Running com.example.DatadogMeterRegistryTest 
16:56:13.937 [run-main-3d] INFO io.micrometer.datadog.DatadogMeterRegistry - publishing metrics to datadog every 10s
counter value is: 0.0
Closing registry...
16:56:14.960 [run-main-3d] TRACE io.micrometer.datadog.DatadogMeterRegistry - sending metrics batch to datadog:
{"series":[{"metric":"my.counter.sample","points":[[1566147374, 0.0]],"tags":["statistic:count"]}]}
16:56:16.028 [run-main-3d] DEBUG io.micrometer.datadog.DatadogMeterRegistry - successfully sent 1 metrics to datadog
After close registry, counter value is: 0.0
[success] Total time: 4 s, completed Aug 18, 2019 4:56:17 PM
```

Sent value is `"metric":"my.counter.sample","points":[[1566147374, 0.0]]`

**Comment by shakuzen** [comment] 2021-03-25 08:28
This is currently expected behavior and is not limited to the DatadogMeterRegistry. It affects StepMeterRegistry implementations in general. It is documented where [client-side rate aggregation](https://micrometer.io/docs/concepts#_client_side) is described. If you have suggestions for how we could improve the documentation, please let us know, though.

Although this issue was created earlier and usually we defer to the older issue, I am marking this as a duplicate of #1882 since that is more generic and covers this as well. We understand there is a gap existing for these types of short-lived applications and we will take a look at what to do about that in the future.
Duplicate of #1882

**Closed by shakuzen** 2021-03-25 08:28 UTC
Labels: registry: datadog
