### ISSUE TITLE
Requirement: I want to send the function link or function call link of the page to elastic. How would I code that?

### ISSUE THREAD

**Issue by ymwfish** [micrometer-metrics/micrometer#3840] opened 2023-05-15 08:44 UTC
Requirement: I want to send the function link or function call link of the page to elastic. How would I code that?

**Comment by bclozel** [comment] 2023-05-15 09:21
Closing as a duplicate of #3838 - let's keep the discussion there, we can rephrase and edit the existing issue if needed.

**Closed by bclozel** 2023-05-15 09:21 UTC
Labels: waiting-for-triage
