### ISSUE TITLE
Unable to calculate 95 percentile latency correctly using TimeWindowPercentileHistogram 

### ISSUE THREAD

**Issue by lokendramani** [micrometer-metrics/micrometer#4080] opened 2023-09-13 09:06 UTC
**Describe the bug**
I have a requirement to record latency of my API, and for every minute I need to check 95 percentile latency,
I am using micrometer Timer for this, but I am not sure whether its resetting recorded value for every minutes as when I ran the load, every time I am getting same value for percentile, this is case both when I am using Cumulative or Step Timer.
One more thing for this purpose am I using micrometer correctly means should it not be used for this use case? as when I checked source code internally it uses TimeWindowPercentileHistogram class (I am using SimpleMeterRegistry) and a Note is written like below:
NOTE: This class is intended for internal use as an implementation detail. You should not compile against its API. Please contact the project maintainers if you need this as public API.
If either this documentation is wrong or how can I use this?
I am using below version
 <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-core</artifactId>
      <version>1.11.2</version>
    </dependency>

**Environment**

 - Micrometer version 1.11.2
 - Micrometer registry SimpleMeterRegistry
 - OS: Windows
 - Java version: openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.372-b07, mixed mode)

**To Reproduce**
How to reproduce the bug:

Create a Timer using SimpleMeterRegistry.
Record random latency for 5 minutes 
calculate 95 percentile latency every minute using nano second time unit.
check the value, it should not be same every minute.
**Expected behavior**
Able to calculate percentile every minute using TimeWindowPercentileHistogram.

**Additional context**
NA

**Comment by jonatan-ivanov** [comment] 2023-09-13 21:32
Thank you for the issue.
Micrometer can compute percentiles for you but unfortunately your repro steps are not really something I could use to reproduce the issue since it's not clear ho you record the data and what data you record. Could you please provide a minimal sample project to reproduce this issue so we can more easily investigate and ensure any fix is working properly for your use case?

This is what I tried and what seems to be working for me:
```java
public class PercentilesDemo {
    private static final SimpleMeterRegistry registry = new SimpleMeterRegistry();
    private static final ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(1);

    public static void main(String[] args) throws InterruptedException {
        executorService.scheduleAtFixedRate(PercentilesDemo::printRegistry, 0, 60, TimeUnit.SECONDS);

        Timer timer = Timer.builder("test")
            .publishPercentiles(0.95)
            .register(registry);

        for (int i = 0; i < 300; i++) {
            int simulatedDuration = (int)(Math.random() * 100) + Math.floorDiv(i, 60) * 100;
            timer.record(Duration.ofMillis(simulatedDuration));
            Thread.sleep(1_000);
        }

        printRegistry();
        executorService.shutdownNow();
    }

    private static void printRegistry() {
        System.out.println("Registry state at " + OffsetDateTime.now());
        System.out.println(registry.getMetersAsString());
        System.out.println();
    }
}
```

What the code does: it records a random latency at every second and prints out the contents of the registry at the end of every minute for 5 minutes. In order to be able to see that percentiles are changing the random value is not form the same interval for the whole lifecycle of the demo. That would defeat the purpose of it, since for example if I generate enough numbers randomly from the `[1,100]` interval, the 95%'ile will always be ~95. :)

So what I'm doing in the first minutes I'm picking from the [0,100) interval then in the second minute from the [100,200) interval and so on till [400,).

With this, I should get these numbers:
- 1st minute: ~ 95ms
- 2nd minute: ~195ms (probably less because the time window is 3 minutes not 1)
- 3rd minute: ~295ms (probably less because the time window is 3 minutes not 1)
- 4th minute: ~395ms (probably less because the time window is 3 minutes not 1)
- 5th minute: ~495ms (probably less because the time window is 3 minutes not 1)

This is the an example results I got:
```
Registry state at 2023-09-13T14:11:31.838874-07:00
test(TIMER)[]; count=60.0, total_time=2.798 seconds, max=0.098 seconds
test.percentile(GAUGE)[phi='0.95']; value=0.096436224 seconds

Registry state at 2023-09-13T14:12:31.842330-07:00
test(TIMER)[]; count=120.0, total_time=11.585 seconds, max=0.196 seconds
test.percentile(GAUGE)[phi='0.95']; value=0.18874368 seconds

Registry state at 2023-09-13T14:13:31.841395-07:00
test(TIMER)[]; count=180.0, total_time=26.497 seconds, max=0.297 seconds
test.percentile(GAUGE)[phi='0.95']; value=0.29360128 seconds

Registry state at 2023-09-13T14:14:31.842840-07:00
test(TIMER)[]; count=240.0, total_time=47.468 seconds, max=0.397 seconds
test.percentile(GAUGE)[phi='0.95']; value=0.385875968 seconds

Registry state at 2023-09-13T14:15:31.847951-07:00
test(TIMER)[]; count=300.0, total_time=74.403 seconds, max=0.496 seconds
test.percentile(GAUGE)[phi='0.95']; value=0.486539264 seconds
```
This seems ok to me. Please also keep a couple of things in mind:
- Client side percentiles are approximated using HdrHistogram, they might not be 100% accurate.
- Calculation are based on a time window: default expiry is 1 minute, default  buffer length is 3 so the window is 3 minutes, See my notes above and the docs https://micrometer.io/docs/concepts#_timers
- You can change the buffer length and expiry: `distributionStatisticBufferLength` and `distributionStatisticExpiry` respectively.

With this, let me close this issue. Let us know if I misunderstood something and you have a minimal sample project to reproduce this issue and we can reopen.

**Closed by jonatan-ivanov** 2023-09-13 21:32 UTC
Labels: waiting-for-triage

**Comment by lokendramani** [comment] 2023-09-14 06:06
As you mentioned below point
 - Calculation are based on a time window: default expiry is 1 minute, default buffer length is 3 so the window is 3 minutes,
 - This calculation means micrometer holds samples for 3 minutes and then calculates, in other words its kind of sliding window of 3 minutes. (As I am unable to find this behavior in documentation).
 - To reduce this to one minute approx then I should decrease default expiry?
 - instead of registry.getMetersAsString() method like in your example what direct method to get percentile value only. I am using below approach:
 ValueAtPercentile[] valueAtPercentiles = timer.takeSnapshot().percentileValues();
System.out.println(valueAtPercentiles[0].percentile()+"th Percentile: " + valueAtPercentiles[0].value(TimeUnit.NANOSECONDS));

**Comment by jonatan-ivanov** [comment] 2023-09-14 16:26
>To reduce this to one minute approx then I should decrease default expiry?

Yes, but you can play both with buffer length and expiry parameters, the two together should produce the time window.

>instead of registry.getMetersAsString() method like in your example what direct method to get percentile value only. I am using below approach: ...

For testing purposes (printing out the values) it does not matter (`getMetersAsString` seems much more convenient to me though) but please do not use Simple registry to feed production systems (it's for testing/troubleshooting metrics purposes).

**Comment by lokendramani** [comment] 2023-09-15 07:11
As I explained in my use case I am not feeding any monitoring system, again I am explaining my use case:
1. Record latency of API
2. Parallel thread will run as a scheduled job which will run in every minute and calculate 95 percentile 
3. if it breached some threshold then I need to take some action
So for this purpose should I not use SimpleMeterRegistry, if not then how can I utilize micrometer in this case. I have read in your code also that if I will prometheusRegistry then I will not be able to choose percentile.

**Comment by jonatan-ivanov** [comment] 2023-09-15 18:25
You should use a metrics backend for this, Micrometer [supports many of them](https://micrometer.io/docs).

>if I will prometheusRegistry then I will not be able to choose percentile.

I don't get this. You can use client-side approximated percentiles with Prometheus and you can also publish histograms and calculate percentiles on the server side (that way you can aggregate data too).
