### ISSUE TITLE
Statsd daemon stopping/starting during application startup stops metrics from working

### ISSUE THREAD

**Issue by adam-yorwerth** [micrometer-metrics/micrometer#1884] opened 2020-03-06 15:42 UTC
We have tried to reproduce this issue locally, and will keep trying and update once we get there, but the manual steps we have done to reproduce are:

- start application that is producing micrometer metrics
- during startup, rapidly start/stop the statsd daemon
- once startup has completed, let the statsd daemon run
- metrics no longer work, and can only be recovered by restarting the application

We had hoped release 1.4.0 would fix this, but testing with the snapshot release proved this to still be broken.

**Comment by shakuzen** [comment] 2020-03-08 01:59
Unfortunately, I'm not able to reproduce this on my MacBook with a sample app using 1.4.0-SNAPSHOT and either UDP or TCP protocol. Perhaps make sure you are using the latest snapshots and share more information about the environment you are seeing this happen in.

>     * during startup, rapidly start/stop the statsd daemon

Not that it necessarily should matter, but why would you start and stop the daemon during startup?

**Comment by adam-yorwerth** [comment] 2020-03-11 14:25
We're running both the application and the statsd daemon as docker containers on a large number of distributed devices, so we see edge cases like this fairly often. The only way we have been able to reproduce so far is starting/stopping the statsd container in a loop while the application starts, and then allowing statsd to run once started. Metrics are only returned once the application is restarted.

**Comment by shakuzen** [comment] 2020-03-11 16:14
If you can turn up logging level (probably specifically for the reactor-netty package `reactor.netty`) to DEBUG or even TRACE while reproducing it, you might have some logs that help lead us to the cause. If you don't get to it, I can try to do this after the 1.4 release, as I don't have a good way to reproduce it setup right now.

**Comment by jkschneider** [comment] 2020-05-07 20:17
I think this was fixed by https://github.com/micrometer-metrics/micrometer/issues/1843.

**Closed by jkschneider** 2020-05-07 20:17 UTC
Labels: registry: statsd
