### ISSUE TITLE
The instance is crashing due to version 1.8.2 of io.micrometer:micrometer-registry-statsd.

### ISSUE THREAD

**Issue by shirapur-sid** [micrometer-metrics/micrometer#3663] opened 2023-02-22 00:20 UTC
After updating the micrometer-registry-statsd version from 1.7.3 to 1.8.2, the instances are terminating during the load. It seems like something has changed as there are now envoy 503 errors being thrown before the instance crashes. The error message accompanying these errors is `status=503` `status_details=upstream_reset_before_response_started{connection_failure}.`

**Comment by shakuzen** [comment] 2023-02-22 02:46
As a general rule, please try with the latest patch version in the minor release you are trying to use to make sure the issue you are seeing hasn't already been resolved in a later patch release. For 1.8.x, that is 1.8.13. That said, the 1.8.x line is no longer in OSS support - see our [support policy](https://micrometer.io/docs/support). If you have a commercial support contract, please open a support ticket through that. If you can reproduce the issue with the latest 1.9.x or 1.10.x patch release, we can try to help you here, but we will need more information like logs or a way for us to reproduce the issue ourselves.

**Comment by shakuzen** [comment] 2023-03-14 01:50
Closing due to lack of response. We can reopen if the requested info/reproducer is provided.

**Closed by shakuzen** 2023-03-14 01:50 UTC
Labels: registry: statsd, feedback needed
