### ISSUE TITLE
After upgrading to version 1.13.0 endpoints are not exposed in Spring Boot with Prometheus

### ISSUE THREAD

**Issue by IlyaLisov** [micrometer-metrics/micrometer#5106] opened 2024-05-16 07:50 UTC
**Describe the bug**
I was used `micrometer:1.12.6` in Spring Boot application, but yesterday upgraded to `1.13.0`. After that I get message on startup: `Exposing 0 endpoint(s) beneath base path '/actuator'`
I only changed version, but config stayed as it was.

**Environment**
 - Micrometer version: 1.13.0
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: 17

**To Reproduce**
My `application.yaml` file contains this config. I changed micrometer version from `1.12.6` to `1.13.0` and started to get 0 endpoints exposed
```
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    enable:
      request:
        enabled: true
      response:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
```

My `pom.xml` file contains:
```
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-registry-prometheus</artifactId>
        <scope>runtime</scope>
        <version>1.13.0</version>
</dependency>
```

**Expected behavior**
I expected that I don't need to change configs because of minor version was changed and there are no corresponding messages in release notes.

**Comment by shakuzen** [comment] 2024-05-16 08:24
> there are no corresponding messages in release notes.

We have the following entry in the Micrometer 1.13 release notes. Perhaps the migration guide could be made more clear on Spring Boot (and other frameworks') compatibility.

> Add support for Prometheus client 1.x https://github.com/micrometer-metrics/micrometer/pull/4846 (please see the [Migration Guide](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide))

This issue is a duplicate of #5103. It's generally best practice to use to the version of dependencies managed by Spring Boot. From your provided pom.xml snippet, I can see you are doing that for `spring-boot-starter-actuator` but you are not doing that for `micrometer-registry-prometheus` (you are overriding the version Spring Boot is managing). If you let Spring Boot manage the version, you should not have an issue. Spring Boot 3.3.0 is scheduled to be released next week, which [plans to upgrade](https://github.com/spring-projects/spring-boot/issues/40666) the version of Micrometer to 1.13. Being on Spring Boot 3.3 will avoid the issue you are seeing. If you would like to use Micrometer 1.13 with Spring Boot 3.2 now, see https://github.com/micrometer-metrics/micrometer/issues/5103#issuecomment-2113119499.

**Comment by shakuzen** [comment] 2024-05-16 08:25
Duplicate of #5103

**Closed by shakuzen** 2024-05-16 08:25 UTC
Labels: duplicate
