### ISSUE TITLE
getThreadInfo method from JvmThreadMetrics cause jvm to crash

### ISSUE THREAD

**Issue by belligerent** [micrometer-metrics/micrometer#3770] opened 2023-04-17 03:05 UTC
**Describe the bug**
instance exited code 127 every one or two days, we managed to download hs_err.log file , which show the exception was occurred when threadBean.getThreadInfo(threadBean.getAllThreadIds() called, [link](https://github.com/micrometer-metrics/micrometer/blob/9936b066c2ac24f4eb7c1cdde1903dbc78625007/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java#L100) , i also filed a openjdk bug report, but no response so far. 

**Environment**

 - Micrometer version  1.8.0
 - Micrometer registry Prometheus
 - OS: Debian GNU/Linux 11
 - Java version: openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment 18.9 (build 11.0.16+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.16+8, mixed mode, sharing)

**To Reproduce**
not sure, instance crashed every one or two days, always this reason, instance was running with around 2000 threads 

**Expected behavior**

**Additional context**

java frame

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc0a0963afd, pid=1, tid=402
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.16+8) (build 11.0.16+8)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.16+8, mixed mode, sharing, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x85eafd]  java_lang_Thread::thread_id(oopDesc*)+0xd
#
# Core dump will be written. Default location: /opt/core.1
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

---------------  S U M M A R Y ------------

Command Line: -Xlog:gc=trace:file=/tmp/gc.log:utctime:filecount=5,filesize=20m -XX:MaxRAMPercentage=70 -XX:SurvivorRatio=3 -XX:NewRatio=1 -XX:ParallelGCThreads=4 -XX:+UseParallelGC -Dcom.mysql.cj.disableAbandonedConnectionCleanup=true -Ddtp.name=prod-dy -Dcom.zaxxer.hikari.useWeakReferences=true -Drocketmq.client.logUseSlf4j=true -Dsun.net.inetaddr.ttl=3 -Dsun.net.inetaddr.negative.ttl=1 -Dnetworkaddress.cache.ttl=3 --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-reads=java.base=ALL-UNNAMED -Dspring.cloud.nacos.config.shared-configs[0].data-id=platform-shared-config.yaml -Dspring.cloud.nacos.config.shared-configs[0].refresh=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/.tss/uploads/oom -XX:+ExitOnOutOfMemoryError -XX:OnOutOfMemoryError=curl tm-tss.service.consul/scripts/operator/oom-handle.sh | sh -XX:ErrorFile=/tmp/hs_err_pid%p.log -XX:OnError=curl tm-tss.service.consul/scripts/operator/crash-handle.sh | sh com.huice.platform.sync.PlatformSyncApplication

Host: Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz, 32 cores, 8G, Debian GNU/Linux 11 (bullseye)
Time: Thu Apr 13 09:26:03 2023 CST elapsed time: 125488.656049 seconds (1d 10h 51m 28s)

---------------  T H R E A D  ---------------

Current thread (0x00007fc09bb0a800):  JavaThread "http-nio-9090-exec-74" daemon [_thread_in_vm, id=402, stack(0x00007fbc53abb000,0x00007fbc53bbc000)] _threads_hazard_ptr=0x00007fbf4404c290

Stack: [0x00007fbc53abb000,0x00007fbc53bbc000],  sp=0x00007fbc53bb98e8,  free space=1018k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x85eafd]  java_lang_Thread::thread_id(oopDesc*)+0xd
V  [libjvm.so+0xaee28c]  jmm_GetThreadInfo+0x56c
J 35795  sun.management.ThreadImpl.getThreadInfo1([JI[Ljava/lang/management/ThreadInfo;)V java.management@11.0.16 (0 bytes) @ 0x00007fc08a2f17af [0x00007fc08a2f16c0+0x00000000000000ef]
J 44488 c2 io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics$$Lambda$1089.applyAsDouble(Ljava/lang/Object;)D (12 bytes) @ 0x00007fc08ae91ab4 [0x00007fc08ae91760+0x0000000000000354]
J 35694 c2 io.micrometer.prometheus.PrometheusMeterRegistry$$Lambda$1070.samples(Ljava/lang/String;Ljava/util/List;)Ljava/util/stream/Stream; (14 bytes) @ 0x00007fc08a2c1ac0 [0x00007fc08a2c1920+0x00000000000001a0]
J 35865 c2 io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement()Ljava/lang/Object; (5 bytes) @ 0x00007fc08a306b1c [0x00007fc08a305d40+0x0000000000000ddc]
J 40058 c2 io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(Ljava/io/Writer;Ljava/util/Enumeration;)V (413 bytes) @ 0x00007fc089b5f97c [0x00007fc089b5eba0+0x0000000000000ddc]
J 49938 c2 org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(Lorg/springframework/boot/actuate/metrics/export/prometheus/TextOutputFormat;Ljava/util/Set;)Lorg/springframework/boot/actuate/endpoint/web/WebEndpointResponse; (85 bytes) @ 0x00007fc08b737f28 [0x00007fc08b737160+0x0000000000000dc8]
J 49958 c2 jdk.internal.reflect.GeneratedMethodAccessor691.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (73 bytes) @ 0x00007fc08b751278 [0x00007fc08b7511c0+0x00000000000000b8]
J 46265 c2 jdk.internal.reflect.GeneratedMethodAccessor674.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (73 bytes) @ 0x00007fc08b0de9b0 [0x00007fc08b0dc980+0x0000000000002030]
J 41641 c2 org.springframework.web.method.support.InvocableHandlerMethod.doInvoke([Ljava/lang/Object;)Ljava/lang/Object; (143 bytes) @ 0x00007fc0890014e8 [0x00007fc089001180+0x0000000000000368]
J 40645 c2 org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(Lorg/springframework/web/context/request/NativeWebRequest;Lorg/springframework/web/method/support/ModelAndViewContainer;[Ljava/lang/Object;)Ljava/lang/Object; (58 bytes) @ 0x00007fc08a88afd8 [0x00007fc08a889fc0+0x0000000000001018]
J 43398 c2 org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljava/lang/Object;)Lorg/springframework/web/servlet/ModelAndView; (11 bytes) @ 0x00007fc08acd7134 [0x00007fc08acd3f80+0x00000000000031b4]
J 43906 c2 org.springframework.web.servlet.DispatcherServlet.doDispatch(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (543 bytes) @ 0x00007fc08ad57c50 [0x00007fc08ad55880+0x00000000000023d0]
J 43393 c2 org.springframework.web.servlet.FrameworkServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (37 bytes) @ 0x00007fc08acb2b64 [0x00007fc08acb0cc0+0x0000000000001ea4]
J 37029 c2 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V (388 bytes) @ 0x00007fc08a4d8f14 [0x00007fc08a4d8d40+0x00000000000001d4]
J 43652 c2 org.apache.catalina.core.StandardWrapperValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (2665 bytes) @ 0x00007fc08ad44874 [0x00007fc08ad445e0+0x0000000000000294]
J 43060 c2 org.apache.catalina.authenticator.AuthenticatorBase.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (810 bytes) @ 0x00007fc08ac1ddcc [0x00007fc08ac1d760+0x000000000000066c]
J 43392 c2 org.apache.catalina.core.StandardHostValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (396 bytes) @ 0x00007fc08acadfd4 [0x00007fc08acadac0+0x0000000000000514]
J 43006 c2 org.apache.catalina.valves.RemoteIpValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (1436 bytes) @ 0x00007fc08abf2758 [0x00007fc08abefb80+0x0000000000002bd8]
J 49008 c2 org.apache.catalina.connector.CoyoteAdapter.service(Lorg/apache/coyote/Request;Lorg/apache/coyote/Response;)V (908 bytes) @ 0x00007fc08b57bb9c [0x00007fc08b57b820+0x000000000000037c]
J 48933 c2 org.apache.coyote.http11.Http11Processor.service(Lorg/apache/tomcat/util/net/SocketWrapperBase;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1248 bytes) @ 0x00007fc08b5150a8 [0x00007fc08b514de0+0x00000000000002c8]
J 43370 c2 org.apache.coyote.AbstractProcessorLight.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (367 bytes) @ 0x00007fc08ac90a88 [0x00007fc08ac909e0+0x00000000000000a8]
J 43004 c2 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1272 bytes) @ 0x00007fc08abed2ec [0x00007fc08abecfe0+0x000000000000030c]
J 42698 c2 org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun()V (587 bytes) @ 0x00007fc08a89b548 [0x00007fc08a89b480+0x00000000000000c8]
J 42563 c2 org.apache.tomcat.util.net.SocketProcessorBase.run()V (35 bytes) @ 0x00007fc08ab58e14 [0x00007fc08ab58d40+0x00000000000000d4]
j  org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(Lorg/apache/tomcat/util/threads/ThreadPoolExecutor$Worker;)V+92
j  org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run()V+5
j  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run()V+4
J 16424 c1 java.lang.Thread.run()V java.base@11.0.16 (17 bytes) @ 0x00007fc081c506ac [0x00007fc081c50540+0x000000000000016c]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x85ae93]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x313
V  [libjvm.so+0x859130]  JavaCalls::call_virtual(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x160
V  [libjvm.so+0x859201]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x81
V  [libjvm.so+0x8fb3ec]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xd390e0]  JavaThread::thread_main_inner()+0xd0
V  [libjvm.so+0xd351a9]  Thread::call_run()+0x149
V  [libjvm.so+0xba7fa6]  thread_native_entry(Thread*)+0xe6

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 35795  sun.management.ThreadImpl.getThreadInfo1([JI[Ljava/lang/management/ThreadInfo;)V java.management@11.0.16 (0 bytes) @ 0x00007fc08a2f1736 [0x00007fc08a2f16c0+0x0000000000000076]
J 44488 c2 io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics$$Lambda$1089.applyAsDouble(Ljava/lang/Object;)D (12 bytes) @ 0x00007fc08ae91ab4 [0x00007fc08ae91760+0x0000000000000354]
J 35694 c2 io.micrometer.prometheus.PrometheusMeterRegistry$$Lambda$1070.samples(Ljava/lang/String;Ljava/util/List;)Ljava/util/stream/Stream; (14 bytes) @ 0x00007fc08a2c1ac0 [0x00007fc08a2c1920+0x00000000000001a0]
J 35865 c2 io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement()Ljava/lang/Object; (5 bytes) @ 0x00007fc08a306b1c [0x00007fc08a305d40+0x0000000000000ddc]
J 40058 c2 io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(Ljava/io/Writer;Ljava/util/Enumeration;)V (413 bytes) @ 0x00007fc089b5f97c [0x00007fc089b5eba0+0x0000000000000ddc]
J 49938 c2 org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(Lorg/springframework/boot/actuate/metrics/export/prometheus/TextOutputFormat;Ljava/util/Set;)Lorg/springframework/boot/actuate/endpoint/web/WebEndpointResponse; (85 bytes) @ 0x00007fc08b737f28 [0x00007fc08b737160+0x0000000000000dc8]
J 49958 c2 jdk.internal.reflect.GeneratedMethodAccessor691.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (73 bytes) @ 0x00007fc08b751278 [0x00007fc08b7511c0+0x00000000000000b8]
J 46265 c2 jdk.internal.reflect.GeneratedMethodAccessor674.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (73 bytes) @ 0x00007fc08b0de9b0 [0x00007fc08b0dc980+0x0000000000002030]
J 41641 c2 org.springframework.web.method.support.InvocableHandlerMethod.doInvoke([Ljava/lang/Object;)Ljava/lang/Object; (143 bytes) @ 0x00007fc0890014e8 [0x00007fc089001180+0x0000000000000368]
J 40645 c2 org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(Lorg/springframework/web/context/request/NativeWebRequest;Lorg/springframework/web/method/support/ModelAndViewContainer;[Ljava/lang/Object;)Ljava/lang/Object; (58 bytes) @ 0x00007fc08a88afd8 [0x00007fc08a889fc0+0x0000000000001018]
J 43398 c2 org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;Ljava/lang/Object;)Lorg/springframework/web/servlet/ModelAndView; (11 bytes) @ 0x00007fc08acd7134 [0x00007fc08acd3f80+0x00000000000031b4]
J 43906 c2 org.springframework.web.servlet.DispatcherServlet.doDispatch(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (543 bytes) @ 0x00007fc08ad57c50 [0x00007fc08ad55880+0x00000000000023d0]
J 43393 c2 org.springframework.web.servlet.FrameworkServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (37 bytes) @ 0x00007fc08acb2b64 [0x00007fc08acb0cc0+0x0000000000001ea4]
J 37029 c2 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V (388 bytes) @ 0x00007fc08a4d8f14 [0x00007fc08a4d8d40+0x00000000000001d4]
J 43652 c2 org.apache.catalina.core.StandardWrapperValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (2665 bytes) @ 0x00007fc08ad44874 [0x00007fc08ad445e0+0x0000000000000294]
J 43060 c2 org.apache.catalina.authenticator.AuthenticatorBase.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (810 bytes) @ 0x00007fc08ac1ddcc [0x00007fc08ac1d760+0x000000000000066c]
J 43392 c2 org.apache.catalina.core.StandardHostValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (396 bytes) @ 0x00007fc08acadfd4 [0x00007fc08acadac0+0x0000000000000514]
J 43006 c2 org.apache.catalina.valves.RemoteIpValve.invoke(Lorg/apache/catalina/connector/Request;Lorg/apache/catalina/connector/Response;)V (1436 bytes) @ 0x00007fc08abf2758 [0x00007fc08abefb80+0x0000000000002bd8]
J 49008 c2 org.apache.catalina.connector.CoyoteAdapter.service(Lorg/apache/coyote/Request;Lorg/apache/coyote/Response;)V (908 bytes) @ 0x00007fc08b57bb9c [0x00007fc08b57b820+0x000000000000037c]
J 48933 c2 org.apache.coyote.http11.Http11Processor.service(Lorg/apache/tomcat/util/net/SocketWrapperBase;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1248 bytes) @ 0x00007fc08b5150a8 [0x00007fc08b514de0+0x00000000000002c8]
J 43370 c2 org.apache.coyote.AbstractProcessorLight.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (367 bytes) @ 0x00007fc08ac90a88 [0x00007fc08ac909e0+0x00000000000000a8]
J 43004 c2 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Lorg/apache/tomcat/util/net/SocketWrapperBase;Lorg/apache/tomcat/util/net/SocketEvent;)Lorg/apache/tomcat/util/net/AbstractEndpoint$Handler$SocketState; (1272 bytes) @ 0x00007fc08abed2ec [0x00007fc08abecfe0+0x000000000000030c]
J 42698 c2 org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun()V (587 bytes) @ 0x00007fc08a89b548 [0x00007fc08a89b480+0x00000000000000c8]
J 42563 c2 org.apache.tomcat.util.net.SocketProcessorBase.run()V (35 bytes) @ 0x00007fc08ab58e14 [0x00007fc08ab58d40+0x00000000000000d4]
j  org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(Lorg/apache/tomcat/util/threads/ThreadPoolExecutor$Worker;)V+92
j  org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run()V+5
j  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run()V+4
J 16424 c1 java.lang.Thread.run()V java.base@11.0.16 (17 bytes) @ 0x00007fc081c506ac [0x00007fc081c50540+0x000000000000016c]
v  ~StubRoutines::call_stub

```

**Comment by jonatan-ivanov** [comment] 2023-04-17 03:32
Isn't there an error message before the snippet you copied?
Could you please edit the description and add it?

**Comment by belligerent** [comment] 2023-04-17 08:55
> 
thanks for the reply
I update the error message , or if you want the full log
[hs_err_pid1.log](https://github.com/micrometer-metrics/micrometer/files/11246006/hs_err_pid1.log)

I check the jdk source code there, no change for java_lang_Thread::thread_id and jmm_GetThreadInfo methods
but we will bump the version to 11.0.18 this week anyway, see if there is a luck

**Comment by jonatan-ivanov** [comment] 2023-04-17 17:35
Thank you for the details! Could you please also add the OpenJDK issue you filed?
(I only found this: [JDK-6930549](https://bugs.openjdk.org/browse/JDK-6930549))

Since Micrometer is only doing this:
```java
threadBean.getThreadInfo(threadBean.getAllThreadIds())
```
I think it is not very likely that the issue is in Micrometer.
Upgrading (maybe above 11 if you can) is definitely an option I would try, also, as a workaround, you ran disable the `jvm.threads.states` `Gauge` using a `MeterFilter`: https://micrometer.io/docs/concepts#_meter_filters

**Comment by marcingrzejszczak** [comment] 2023-12-20 16:47
There was no feedback since april. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-20 16:47 UTC
Labels: waiting for feedback
