### ISSUE TITLE
Elastic registry doesn't support configuring multiple hosts

### ISSUE THREAD

**Issue by benbenw** [micrometer-metrics/micrometer#1388] opened 2019-04-17 14:59 UTC
The elastic registry lost its ability to connect to multiple hosts with commit https://github.com/micrometer-metrics/micrometer/commit/dd62f0c8322031bc98c872965e420b132c68ed69 (isssue #842)

It was previously possible to configure multiple host with : 

_management.metrics.export.elastic.host**s**_

After dd62f0c8322031bc98c872965e420b132c68ed69 it became :

_management.metrics.export.elastic.host_

It looks like a regression. If it's confirmed by the micrometer team we could provide a PR.

**Comment by shakuzen** [comment] 2019-04-24 08:47
Elasticsearch support was added 1.1.0 and the referenced issue/change is from `1.1.0-rc.1` so I don't think we will consider this a regression - the previous property/support was never in a GA version, as far as I can tell. I do agree that supporting configuring multiple hosts could be useful, though, and it is an enhancement we can consider.
There are some alternatives to this that people could use for now. One would be putting a load balancer in front of your Elasticsearch server instances and configuring your applications to push metrics to that. Another would be a DNS record that points at your ES servers.

**Comment by marcingrzejszczak** [comment] 2023-12-21 14:41
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-21 14:41 UTC
Labels: enhancement, registry: elastic
