### ISSUE TITLE
[GraphiteReporter] MetricAttribute type is appended in the last tag value

### ISSUE THREAD

**Issue by Francois-Michaut-Epitech** [micrometer-metrics/micrometer#2085] opened 2020-05-11 10:03 UTC
Hello, 

I am reporting metrics to Graphite, using a `GraphiteReporter`.
Since Graphite support tags, I'm using them in my metrics.

For instance I have the following meter : 
`registry.counter("my.counter", Tag.of("version", "SNAPSHOT"));`
I'm expecting my tag to have the value `SNAPSHOT`, and a serie named something like `my.counter.count`.

But when I look the series name in Graphite I have the following : 
`my.counter;version=SNAPSHOT.count`
And when I'm looking for the values of the tag `version`, I don't have `SNAPSHOT`, but this : 
![image](https://user-images.githubusercontent.com/33881730/81549015-66ea1280-937e-11ea-9869-e922f58b3acf.png)

The problem is that Graphite allows the dot character in the tag value, and the `GraphiteReporter` append the `MettricAttribute` after the serie's name and tags have been concatenated.

The serie should look like `my.counter.count;version=SNAPSHOT` instead of `my.counter;version=SNAPSHOT.count` when sended to Graphite-carbon.

**Comment by jkschneider** [comment] 2020-05-11 12:46
Is this a duplicate of https://github.com/micrometer-metrics/micrometer/issues/2069?

**Comment by Francois-Michaut-Epitech** [comment] 2020-05-11 12:48
Yeah, it seems so, should I close this ?

**Comment by jkschneider** [comment] 2020-05-11 12:51
Thanks for checking @Francois-Michaut-Epitech (and the initial report). I'll close and tag as duplicate.

**Closed by jkschneider** 2020-05-11 12:51 UTC
