### ISSUE TITLE
Metrics static methods use a different registry than the injected MeterRegistry

### ISSUE THREAD

**Issue by Davio** [micrometer-metrics/micrometer#2633] opened 2021-06-03 15:40 UTC
I don't know whether this belongs on the Spring Boot side, but basically since version 1.7.0 of Micrometer and 2.5.0 of Spring Boot, all of my custom metrics had disappeared.

After some research, it seems like `Metrics.counter("test").increment()` adds the counter to the global registry which is a `CompositeMeterRegistry`. This counter does not get displayed at endpoint `/actuator/metrics` nor `/actuator/prometheus`.

When I use an injected `MeterRegistry`, I get a registry of type `PrometheusMeterRegistry` (I assume because of my micrometer-registry-prometheus dependency). If I register my counter with this registry, it is both shown in the metrics and prometheus endpoint.

Is there some configuration which I'm missing or is this a (known) bug?

**Comment by checketts** [comment] 2021-06-03 17:14
This sounds like a new bug. 

Out of curiosity, do you see any message about `<bean> is not eligible for getting processed by all BeanPostProcessors`?

**Comment by Davio** [comment] 2021-06-03 17:19
Yes, several, currently these are the beans mentioned which are not eligible:

- Bean 'management.metrics-org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties' of type [org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties]
- Bean 'org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.data.RepositoryMetricsAutoConfiguration]
- Bean 'org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusMetricsExportAutoConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusMetricsExportAutoConfiguration]
- Bean 'management.metrics.export.prometheus-org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusProperties' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusProperties]
- Bean 'prometheusConfig' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.prometheus.PrometheusPropertiesConfigAdapter]
- Bean 'collectorRegistry' of type [io.prometheus.client.CollectorRegistry]
- Bean 'org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration]
- Bean 'micrometerClock' of type [io.micrometer.core.instrument.Clock$1]
- Bean 'prometheusMeterRegistry' of type [io.micrometer.prometheus.PrometheusMeterRegistry]
- Bean 'repositoryTagsProvider' of type [org.springframework.boot.actuate.metrics.data.DefaultRepositoryTagsProvider]
- Bean 'metricsRepositoryMethodInvocationListener' of type [org.springframework.boot.actuate.metrics.data.MetricsRepositoryMethodInvocationListener]

**Comment by checketts** [comment] 2021-06-03 17:49
That is the smoking gun. By `PrometheusMeterRegistry` being unavailable for bean post-processing then `MeterRegistryPostProcessor` can't configure it (and add it to the global registry)

You might have a dependency or code that is instantiating the Prometheus registry very early. See https://github.com/spring-projects/spring-framework/issues/24092 for an overview (and note the linked Micrometer issues to see some more details)

This sounds like a Spring Boot issue.

**Comment by shakuzen** [comment] 2021-06-04 04:54
> since version 1.7.0 of Micrometer and 2.5.0 of Spring Boot, all of my custom metrics had disappeared.

Sounds like https://github.com/spring-projects/spring-boot/issues/26630, which is fixed in the upcoming Spring Boot 2.5.1 release, scheduled for June 10. I would suggest trying your application on Spring Boot 2.5.1 snapshots to ensure the issue is fixed for you.

Under the assumption that is the cause, I'll close this as a duplicate of that issue. If that turns out to not be the case, we can reopen and investigate further.

**Comment by Davio** [comment] 2021-06-04 06:28
I can confirm the workaround mentioned in https://github.com/spring-projects/spring-boot/issues/26630 (which originates from https://stackoverflow.com/questions/57607445/spring-actuator-jvm-metrics-not-showing-when-globalmethodsecurity-is-enabled/57908577#57908577) fixes my issue.

So until 2.5.1 is released, I have implemented this workaround.

This means there is nothing more to be done in this issue, so I will close it and I hope that whoever finds this issue also finds the mentioned workaround.

**Comment by Davio** [comment] 2021-06-14 07:00
I tested this with Spring Boot 2.5.1 and sadly, the problem still exists. Using the `Metrics.counter` static method doesn't show my metric in the prometheus endpoint when I removed the workaround.

When I re-added the workaround mentioned in the related issue:

    // Workaround for https://github.com/spring-projects/spring-boot/issues/26630
    @Bean
    @ConditionalOnBean(name = {"meterRegistryPostProcessor", "prometheusMeterRegistry"})
    public InitializingBean forcePrometheusPostProcessor(BeanPostProcessor meterRegistryPostProcessor,
                                                         PrometheusMeterRegistry registry) {
        return () -> meterRegistryPostProcessor.postProcessAfterInitialization(registry, "");
    }

...it worked again.

**Comment by giuseppemilicia** [comment] 2021-08-11 12:04
> I tested this with Spring Boot 2.5.1 and sadly, the problem still exists. Using the `Metrics.counter` static method doesn't show my metric in the prometheus endpoint when I removed the workaround.
> 
> When I re-added the workaround mentioned in the related issue:
> 
> ```
> // Workaround for https://github.com/spring-projects/spring-boot/issues/26630
> @Bean
> @ConditionalOnBean(name = {"meterRegistryPostProcessor", "prometheusMeterRegistry"})
> public InitializingBean forcePrometheusPostProcessor(BeanPostProcessor meterRegistryPostProcessor,
>                                                      PrometheusMeterRegistry registry) {
>     return () -> meterRegistryPostProcessor.postProcessAfterInitialization(registry, "");
> }
> ```
> 
> ...it worked again.

Same issue also with Spring Boot 2.5.3

**Comment by shakuzen** [comment] 2021-08-20 09:25
Can you provide a minimal sample project for us to run that reproduces the issue?

**Comment by shakuzen** [comment] 2023-01-26 10:34
Closing until we can get a minimal sample project that reproduces the issue for us to investigate further.

**Closed by shakuzen** 2023-01-26 10:34 UTC
Labels: duplicate, for: external-project, feedback needed
