### ISSUE TITLE
No metric published

### ISSUE THREAD

**Issue by krishnaai265** [micrometer-metrics/micrometer#3991] opened 2023-07-21 10:12 UTC
I am also not able to see any metric published for OkHttpClient. What are the metrics should be published in http://localhost:8080/actuator/metrics. Could you please check the configs?
```{
OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
                .connectionPool(okHttpConnectionPool)
                .connectTimeout(connectTimeout, TimeUnit.MILLISECONDS)
                .readTimeout(readTimeout, TimeUnit.MILLISECONDS)
                .writeTimeout(writeTimeout, TimeUnit.MILLISECONDS)
                .addInterceptor(httpLoggingInterceptor)
                .dispatcher(new Dispatcher(executorService));

      OkHttpMetricsEventListener okHttpMetricsEventListener = OkHttpMetricsEventListener.builder(meterRegistry,
                      MonitoringConstants.METRIC_PREFIX + name)
              .tags(Tags.of(MonitoringConstants.SERVICE, service))
              .uriMapper(request -> request.url().toString())
              .includeHostTag(true)
              .build();

          okHttpClientBuilder.eventListener(okHttpMetricsEventListener);
         okHttpClientBuilder.authenticator(authenticator);

      return okHttpClientBuilder.build();

}
```
micrometer-registry-statsd: 1.8.1
spring-boot: 2.6.7
okhttp3.version: 3.14.9

**Comment by jonatan-ivanov** [comment] 2023-07-21 17:04
The versions you use are not supported anymore, could you please upgrade?

**Comment by krishnaai265** [comment] 2023-07-21 18:38
@jonatan-ivanov Can you please suggest stable version?

**Comment by jonatan-ivanov** [comment] 2023-07-21 20:33
I would upgrade to the latest Spring Boot 2.7.x and let it define the Micrometer version to me (latest 1.9.x), you can find the latest versions in the releases: https://github.com/micrometer-metrics/micrometer/releases

**Comment by krishnaai265** [comment] 2023-07-22 07:48
@jonatan-ivanov I have updated dependencies to Spring Boot 2.7.14 and Micrometer core & statsd to 1.9.13. 
Still no metric for okhttpclient has been published to http://localhost:8080/actuator/metrics.

**Comment by krishnaai265** [comment] 2023-07-26 09:21
@jonatan-ivanov Any update?

**Comment by shakuzen** [comment] 2023-07-27 02:38
There won't be any metrics registered until the OkHttp client is actually used. Have you verified the client has been used to make an HTTP request before checking the metrics?

**Comment by krishnaai265** [comment] 2023-07-27 08:09
@shakuzen Yes, I sent multiple calls using okhttp client but no metrics has been generated.

**Comment by shakuzen** [comment] 2023-07-27 08:13
You're going to need to provide a minimal sample that reproduces the issue for us to investigate further, then. I'm out of other ideas why the instrumentation would not be working for you, and it's not efficient for us to keep guessing without seeing runnable code that reproduces the issue you're having.

**Comment by izeye** [comment] 2023-09-05 15:13
I created [a sample](https://github.com/izeye/hello-spring-boot-micrometer/tree/micrometer-gh-3991) based on [the reference doc](https://micrometer.io/docs/ref/okhttpclient), and it seems to work as expected.

@krishnaai265 You can try to reproduce or solve the issue with the sample if you still have the problem.

**Comment by shakuzen** [comment] 2023-09-08 22:44
Closing as we can't reproduce it. We can reopen the issue if we get a minimal sample project that reproduces the issue or enough information to identify the issue.

**Closed by shakuzen** 2023-09-08 22:44 UTC
Labels: feedback needed
