### ISSUE TITLE
 ERROR --- [elastic-metrics-publisher] i.m.elastic.ElasticMeterRegistry : failed to send metrics to elastic (sent 256 metrics but created 241 metrics): 

### ISSUE THREAD

**Issue by patpatpat123** [micrometer-metrics/micrometer#3841] opened 2023-05-15 09:10 UTC
**Describe the bug**
 ERROR --- [elastic-metrics-publisher] i.m.elastic.ElasticMeterRegistry : failed to send metrics to elastic (sent 256 metrics but created 241 metrics): 

**Environment**
 - Micrometer version 1.11.0-RC1
 - Micrometer registry elasticsearch
 - OS: reproducible with macOS Unix and Windows
 - Java version: [e.g. output of `java -version`] graalVM 17

**To Reproduce**
using the ```io.micrometer.core.instrument.binder.jetty.JettyClientMetrics``` will 100% reproduce the issue

```
@Bean
    public HttpClient getHttpClient(final MeterRegistry registry) {
        final var clientConnector = new ClientConnector();
        final var jettyClientMetrics = JettyClientMetrics.builder(registry, (request, result) -> result.getRequest().getURI().getPath()).build();
        HttpClient httpClient = new HttpClient(new HttpClientTransportOverHTTP(clientConnector));
        httpClient.getRequestListeners().add(jettyClientMetrics);
        return httpClient;
    }
```

**Expected behavior**
Having the metrics sent to elasticsearch without issue

**Comment by jonatan-ivanov** [comment] 2023-05-18 21:52
I have a few questions:
1. Can you try it with the GA release instead of RC1 (I don't think it will make a difference though)?
1. Which version of Elastic is this?
1. Can you repro it with creating meters manually or is it Jetty specific (should not be)?
1. Is it happening locally too (can it be an ElasticSearch issue/eventual consistency)?
1. After the line you pasted, the response body should be there, what is missing from it? Can it happen that Elastic drops certain documents because of their content?

Could you please provide a minimal sample project to reproduce this issue so we can more easily investigate and ensure any fix is working properly for your use case?

**Comment by izeye** [comment] 2023-06-27 21:41
I tried to reproduce this with [a sample](https://github.com/izeye/hello-spring-boot-micrometer/tree/micrometer-gh-3841) but couldn't.

**Comment by shakuzen** [comment] 2023-06-28 01:08
Thank you for trying to reproduce it, @izeye. We'll close the issue for now, and we can reopen it if we get a way to reproduce it.

**Closed by shakuzen** 2023-06-28 01:08 UTC
Labels: feedback needed
