### ISSUE TITLE
Docs: Add CloudWatch to the list of supported backends, document

### ISSUE THREAD

**Issue by holyjak** [micrometer-metrics/micrometer#1393] opened 2019-04-23 07:22 UTC
Since there is https://github.com/micrometer-metrics/micrometer/tree/master/implementations/micrometer-registry-cloudwatch, CloudWatch should be mentioned at https://micrometer.io/docs just as InfluxDB & others and preferably link to a page with some documentation (such as the required IAM permissions to be able to use it).

Regarding IAM: perhaps only `cloudwatch:PutMetricData` needed?

Thank you!!!

**Comment by izeye** [comment] 2019-04-23 08:43
Duplicate of https://github.com/micrometer-metrics/micrometer-docs/issues/49

**Comment by izeye** [comment] 2019-04-23 08:48
@holyjak Thanks for the report but there's already an issue for it.

> Regarding IAM: perhaps only `cloudwatch:PutMetricData` needed?

In regards to this specific question I'm not a CloudWatch user but the permission seems sufficient for Micrometer to work just by guessing based on its name.

**Closed** 2019-04-23 08:47 UTC
Labels: duplicate

**Comment by mateuszmrozewski** [comment] 2019-05-14 02:50
`cloudwatch:PutMetricData` is enough from the IAM permissions side
