### ISSUE TITLE
Enhanced support for NewRelic APM

### ISSUE THREAD

**Issue by schmidt-galen-heb** [micrometer-metrics/micrometer#1761] opened 2019-12-19 21:59 UTC
Howdy! I'm using NewRelic APM to monitor my Springboot applications, and am investigating reporting custom MicroMeter metrics to NewRelic Insights.

This was previously implemented in feature request https://github.com/micrometer-metrics/micrometer/issues/122.
Two potential integration paths were investigated:
1. Indirect integration via the [NewRelic Java Agent](https://docs.newrelic.com/docs/agents/java-agent/api-guides/guide-using-java-agent-api)
1. Direct integration via the [Insights REST API](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/introduction-event-api)

Ultimately, option (2) was chosen because:
1. Integration via the agent required the use of [APM custom metrics](https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/collect-custom-metrics), which are less powerful than Insights metrics
1. The agent must be installed as a [Java agent](https://docs.newrelic.com/docs/agents/java-agent/installation/include-java-agent-jvm-argument) on the application JVM, which requires customizing the JVM startup arguments as well as providing an agent configuration file

In my case however, we've already integrated the APM agent, and option (1) requires use of an [Insights API key](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#event-insert-key), as well as [specifying the NewRelic account ID](https://github.com/micrometer-metrics/micrometer/blob/114d62be80c51768031a0672b021bb30a917c615/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicConfig.java#L66), neither of which are required by the agent (and thus we aren't currently providing them).

The agent API allows programmatic access to the Insights API via [NewRelic.getAgent().getInsights()](https://docs.newrelic.com/docs/agents/java-agent/api-guides/guide-using-java-agent-api#obtain-references), and metrics can then be recorded via the [Insights.recordCustomEvent(...)](https://newrelic.github.io/java-agent-api/javadoc/index.html?com/newrelic/api/agent/Insights.html) method. NewRelic's guide on this is [here](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/insert-custom-events-new-relic-apm-agents).

Note: the [current implementation](https://github.com/micrometer-metrics/micrometer/blob/114d62be80c51768031a0672b021bb30a917c615/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java#L111) also records metrics as a [custom event](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/introduction-event-api#submit-event) internally, but does so using the insights API directly.

In addition to the existing `NewRelicMeterRegistry`, I'd like to have the option of using a class (called something like `NewRelicApmMeterRegistry`) which utilized the APM agent's Java API to submit metrics. Since submitting custom events via the agent does not appear to require any additional configuration, this is a much simpler integration path for consumers who are already utilizing the NewRelic APM.

(additional note: I've looked briefly at [newrelic/micrometer-registry-newrelic](https://github.com/newrelic/micrometer-registry-newrelic), but it also appears to require an insights API key, which is what I'm trying to avoid for applications already integrated with the APM).

**Comment by schmidt-galen-heb** [comment] 2019-12-19 22:05
If you think this feature request makes sense, I'd be potentially interested in submitting a PR to implement it. 

First though, do you have a contributor license agreement for the project? I wasn't able to find one looking over the repo/website

**Comment by schmidt-galen-heb** [comment] 2020-02-14 18:32
I've submitted a PR for this here: https://github.com/micrometer-metrics/micrometer/pull/1854

After more investigation into the existing code, as well as how Spring integrates with it, I decided that although pulling the APM integration into a separate `MeterRegistry` subclass makes more sense from a design perspective, it would make it significantly more difficult for clients to integrate.

**Comment by shakuzen** [comment] 2020-03-12 16:34
First of all, thank you for the detailed description and a very complete pull request. I apologize I didn't respond to this much sooner. We had #1540 already open which I believe is the same as your request. The good news is we just merged an implementation for it with #1647 which will be part of the upcoming 1.4 release. Sorry I didn't share this before you went to the trouble of making a pull request.

Would you be willing to take a look at that issue and pull request to make sure it covers what you're expecting and works for you? I like that in your pull request, you've made it configurable in NewRelicConfig which implementation gets used. It would be appreciated if you could rework your pull request or open a new one to make that possible with the latest changes.

/cc @neiljpowell

**Comment by neiljpowell** [comment] 2020-03-12 17:29
Hi. I created https://github.com/micrometer-metrics/micrometer/pull/1647 for the very same reason. APM Agent users get the benefit of publishing metrics to the same Insights MicrometerSample event type but without needing to manage distribution of the API Key and Account Id.
I'll be opening a PR with Spring Boot to enable the Agent delegation feature (publishes to a SpringBootSample event type), once Micrometer 1.4 is released.

**Comment by shakuzen** [comment] 2020-04-23 07:16
Duplicate of #1540

**Closed by shakuzen** 2020-04-23 07:16 UTC
Labels: registry: new relic
