### ISSUE TITLE
Elastic Shipper non finite value

### ISSUE THREAD

**Issue by sabareeshkkanan** [micrometer-metrics/micrometer#1420] opened 2019-05-14 14:12 UTC
@izeye 
I am still facing this issue even with the new snapshot. It produced several metric where elastic might consider it as not finite. 
Spring boot 2.1.4
Spring cloud GreenwichSR1
Java11
Spring Cloud Kafka Streams

```
+--- io.micrometer:micrometer-registry-elastic:1.1.5-SNAPSHOT
|    \--- io.micrometer:micrometer-core:1.1.5-SNAPSHOT (*)

```

```
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"0","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"1","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"2","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"3","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.778Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"4","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"5","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"6","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
{ "index" : {} }
{"@timestamp":"2019-05-13T16:50:18.779Z","name":"kafka_consumer_records_lead_min","type":"gauge","activeProfile":"dev","client_id":"consumer-4","partition":"7","region":"","serviceName":"request-handler","topic":"DV_REQUEST_HANDLER","value":1.7976931348623157E308}
```

_Originally posted by @sabareeshkkanan in https://github.com/micrometer-metrics/micrometer/issues/1370#issuecomment-491905536_

**Comment by izeye** [comment] 2019-05-14 14:51
@sabareeshkkanan Thanks for the report!

1.7976931348623157E308 is a finite value which is the max value of `double`, so I think this issue is different from #1370. I suspect this is due to type mismatch for the `value` field: `float` vs. `double`

Could you please provide full error logs including HTTP response from Elasticsearch? Also sharing the mapping of the index for metrics would help.

**Comment by sabareeshkkanan** [comment] 2019-05-14 16:25
I have isolated the ones I get error with because there are so many metrics. I have attached both the map and json response here 
[metric-fields.xlsx](https://github.com/micrometer-metrics/micrometer/files/3178814/metric-fields.xlsx)
[elastic-error.txt](https://github.com/micrometer-metrics/micrometer/files/3178817/elastic-error.txt)

**Comment by izeye** [comment] 2019-05-14 16:47
@sabareeshkkanan Thanks for sharing!

I confirmed `float` type handles it as infinity as follows:

```
$ curl -XPOST --header "Content-Type: application/json" http://localhost:9200/metrics-2019-05/doc/_bulk --data-binary '
{ "index" : {} }
{"@timestamp":"2019-05-14T15:31:46.313Z","name":"jvm_gc_memory_promoted","type":"counter","count":1.7976931348623157E308}
'
{"took":3,"errors":true,"items":[{"index":{"_index":"metrics-2019-05","_type":"doc","_id":"qb8zt2oBVqC16kvPj5mB","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [count] of type [float] in document with id 'qb8zt2oBVqC16kvPj5mB'","caused_by":{"type":"illegal_argument_exception","reason":"[float] supports only finite values, but got [Infinity]"}}}}]}
$ 
```

I think this is a duplicate of #1071. I created #1421 to try to resolve both.

**Comment by sabareeshkkanan** [comment] 2019-05-14 18:10
@izeye Thank you for this, when can we expect this to be merged and built

**Comment by izeye** [comment] 2019-05-15 02:28
@sabareeshkkanan If the PR gets merged, I think it will be in [1.1.5 which is not scheduled for a release ATM](https://github.com/micrometer-metrics/micrometer/milestone/45).

**Closed** 2019-05-15 15:27 UTC

**Comment by shakuzen** [comment] 2019-05-15 15:36
@sabareeshkkanan now that the fix is merged, please feel free to test out a [snapshot version](https://github.com/micrometer-metrics/micrometer/#snapshot-builds) containing the fix.

**Comment by sabareeshkkanan** [comment] 2019-05-15 17:03
@izeye @shakuzen Is there something else I have to do ? weird we are not building a unique version every time for the snapshot but after redownloading the dependency i still got the same error. Should i delete and recreate the index ? Sorry i am bit new to elastic

**Comment by izeye** [comment] 2019-05-15 17:13
@sabareeshkkanan When I was testing this, I deleted the index for metrics (`metrics-2019-05`) and the template for the index (`metrics_template`). So I'm afraid you need to do so, too.

See https://github.com/micrometer-metrics/micrometer/pull/1421#issuecomment-492321904

**Comment by sabareeshkkanan** [comment] 2019-05-15 22:06
@izeye thanks for clarification. This appears to work fine now
