### ISSUE TITLE
Disable kotlinSourcesJar since it conflicts with sourcesJar

### ISSUE THREAD

**Issue by liaozan** [micrometer-metrics/micrometer#5151] opened 2024-05-28 16:00 UTC
This is the archive of the source jar in the central repository

https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.13.0/micrometer-core-1.13.0-sources.jar

It looks like it adds an extra layer of `main` directory?

<img width="756" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/26990889/ef0cb7db-9ac6-4366-adf3-6dbb946e41f5">

**Comment by jonatan-ivanov** [comment] 2024-06-14 00:38
Thank you for the issue!
I'm not sure what is causing this yet, it seems:
- The latest 1.12.x does not have this issue: [`micrometer-core-1.12.7-sources.jar`](https://repo1.maven.org/maven2/io/micrometer/micrometer-core/1.12.7/micrometer-core-1.12.7-sources.jar)
- Neither other 1.13.x jars like [`micrometer-commons-1.13.1-sources.jar`](https://repo1.maven.org/maven2/io/micrometer/micrometer-commons/1.13.1/micrometer-commons-1.13.1-sources.jar) (I spot-checked a few more)
- The first milestone release have it: [`micrometer-core-1.13.0-M1-sources.jar`](https://repo.spring.io/artifactory/milestone/io/micrometer/micrometer-core/1.13.0-M1/micrometer-core-1.13.0-M1-sources.jar)
- I can repro this locally:
```shell
git checkout v1.13.0
./gradlew -Prelease.disableGitChecks=true -Prelease.useLastTag=true -Prelease.stage=milestone final pTML -x test
```
- But if I just run `pTML`, I can't:
```shell
./gradlew pTML
```
Diffing 1.12.x with 1.13.x does not help much, I can't see any suspicious changes.

I'm continuing the investigations tomorrow but is this causing any issues to you right now? Can the IDE automatically attach source for 1.13.0?

**Comment by jonatan-ivanov** [comment] 2024-07-09 20:52
I investigated this a bit further, I found a simpler way of reproducing it (than the above) with `micrometer-core` (`1.13.x`) if I run `sourcesJar` and `pTML` (`publishToMavenLocal`) **together**:
```bash
./gradlew :micrometer-core:sourcesJar :micrometer-core:pTML -x check --console=plain --no-build-cache
```

If I run just one of these tasks or run them after each other in separate gradle commands, I cannot repro it so these are ok:
```bash
./gradlew :micrometer-core:sourcesJar -x check --console=plain --no-build-cache
./gradlew :micrometer-core:pTML -x check --console=plain --no-build-cache
```

It seems I can "fix" this by downgrading the Kotlin plugin(!), i.e. changing this line: https://github.com/micrometer-metrics/micrometer/blob/10614998cf0779b3d6bbd33a822b96a10695572e/micrometer-core/build.gradle#L2
to
```groovy
alias(libs.plugins.kotlin17)
```
Here are the steps you should be able to repro this too (first checkout `1.13.x`):
```bash
./gradlew clean
rm -rf ~/.gradle/caches/build-cache-1/
./gradlew :micrometer-core:sourcesJar :micrometer-core:pTML -x check --console=plain --no-build-cache
unzip -l micrometer-core/build/libs/micrometer-core-*-sources.jar | head -n20
```
Then downgrade the kotlin plugin: `alias(libs.plugins.kotlin17)` instead of `alias(libs.plugins.kotlin19)` in [`micrometer-core/build.gradle`](https://github.com/micrometer-metrics/micrometer/blob/10614998cf0779b3d6bbd33a822b96a10695572e/micrometer-core/build.gradle#L2) and the `main` folder should be gone.

I tried to upgrade the Kotlin plugin from `1.9.23` to `1.9.24`, it did not help.

There is another interesting thing I found, the `META-INF` folder contains only the `MANIFEST.MF` file when `main` is the root folder (I don't think this is a problem, the "norlam jar contains the necessary files").
When `main` folder is not present (Kotlin 1.7 plugin):
```
Archive:  micrometer-core/build/libs/micrometer-core-1.13.3-SNAPSHOT-sources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  07-09-2024 13:24   META-INF/
      817  07-09-2024 13:24   META-INF/MANIFEST.MF
      762  07-09-2024 13:24   META-INF/micrometer-core.properties
        0  07-09-2024 11:50   META-INF/native-image/
        0  07-09-2024 11:50   META-INF/native-image/io.micrometer/
        0  07-09-2024 11:50   META-INF/native-image/io.micrometer/micrometer-core/
      871  07-09-2024 11:50   META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json
      541  07-09-2024 11:50   META-INF/native-image/io.micrometer/micrometer-core/proxy-config.json
        0  11-17-2023 16:20   io/
        0  11-17-2023 16:20   io/micrometer/
        0  03-15-2024 14:07   io/micrometer/core/
```
When `main` folder is present (Kotlin 1.9 plugin):
```
Archive:  micrometer-core/build/libs/micrometer-core-1.13.3-SNAPSHOT-sources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-01-1980 00:00   META-INF/
       25  02-01-1980 00:00   META-INF/MANIFEST.MF
        0  02-01-1980 00:00   main/
        0  02-01-1980 00:00   main/io/
        0  02-01-1980 00:00   main/io/micrometer/
        0  02-01-1980 00:00   main/io/micrometer/core/
```

**Comment by jonatan-ivanov** [comment] 2024-07-09 21:49
It seems the `kotlinSourcesJar` task does this and its order relative to `sourcesJar`.
If `sourcesJar` runs first, there is no `main` folder:
```bash
./gradlew :micrometer-core:sourcesJar :micrometer-core:kotlinSourcesJar -x check --console=plain --no-build-cache
```
If `kotlinSourcesJar` runs first, the `main` folder is present:
```bash
./gradlew :micrometer-core:kotlinSourcesJar :micrometer-core:sourcesJar -x check --console=plain --no-build-cache
```

This is the same issue: https://youtrack.jetbrains.com/issue/KT-54207/Kotlin-has-two-sources-tasks-kotlinSourcesJar-and-sourcesJar-that-archives-sources-to-the-same-artifact

**Comment by jonatan-ivanov** [comment] 2024-07-09 22:54
I think this should be fixed in earlier versions too (whenever we use the Kotlin plugin): `1.12.x` since that's the oldest OSS supported branch.

**Closed** 2024-07-09 23:06 UTC
Labels: bug, build

**Comment by jonatan-ivanov** [comment] 2024-07-09 23:15
The new snapshot is published, you can see the diff between the old sources jar and the new one:
- old, not fixed: https://repo.spring.io/artifactory/snapshot/io/micrometer/micrometer-core/1.13.3-SNAPSHOT/micrometer-core-1.13.3-20240709.034046-1-sources.jar
- new, fixed: https://repo.spring.io/artifactory/snapshot/io/micrometer/micrometer-core/1.13.3-SNAPSHOT/micrometer-core-1.13.3-20240709.230322-2-sources.jar
