### ISSUE TITLE
What's the time window that _max is calculated from?

### ISSUE THREAD

**Issue by RafalSkolasinski** [micrometer-metrics/micrometer#2126] opened 2020-05-27 16:18 UTC
Timers (Histograms?) produce time series with also `_count`, `_sum` and `_max`. 
I am wondering over what time window are these calculated, mostly about the `max`. 

I did some empirical tests and it looks like time window is 2-3 mins but would be good to get some clarification on this.

**Comment by shakuzen** [comment] 2020-05-28 03:23
Duplicate of #1350

**Closed by shakuzen** 2020-05-28 03:23 UTC
Labels: question
