### ISSUE TITLE
missing pcollection dependency for 1.0.5 tag

### ISSUE THREAD

**Issue by okrische** [micrometer-metrics/micrometer#664] opened 2018-06-18 07:39 UTC
Hello,

i get a NoClasDefFound error, when adding micrometer-registry-statsd-1.0.5 as dependency (well, spring boot 2.0.3 does that for me)

`Caused by: java.lang.NoClassDefFoundError: org/pcollections/PMap
	at io.micrometer.statsd.StatsdMeterRegistry.lambda$lineBuilder$4(StatsdMeterRegistry.java:251)
	at io.micrometer.statsd.StatsdMeterRegistry.lineBuilder(StatsdMeterRegistry.java:259)
	at io.micrometer.statsd.StatsdMeterRegistry.newCounter(StatsdMeterRegistry.java:264)`

Did you forget to shade pcollections? Otherwise i will have to add it manually, dont i?

Cheers!

**Comment by shakuzen** [comment] 2018-06-18 08:07
Duplicate of #655

**Closed by shakuzen** 2018-06-18 08:07 UTC

**Comment by jkschneider** [comment] 2018-06-18 14:14
Also, noted in release notes: https://github.com/micrometer-metrics/micrometer/releases/tag/v1.0.5
