### ISSUE TITLE
@Timed annotation not binding in Spring MVC app (without Spring Boot)

### ISSUE THREAD

**Issue by ynohtna92** [micrometer-metrics/micrometer#3331] opened 2022-08-05 01:24 UTC
**Describe the bug**
I am utilising micrometer in a Spring 5 MVC app without spring boot and was wondering how to get the @Timed annotation working for a @RestController class. I have tried using the Bean TimedAspect but I'm not sure how to integrate it with spring mvc without spring boot as there are no examples for this.

I am able to get influx working with the controller and timers + counters working manually but nothing is logged without explicitly declaring a register (and obviously annotations are not working so functions can't be wrapped in timers).

**Environment**

 - Micrometer version 1.7.2
 - Micrometer registry influxdb 1.8.10
 - Spring MVC 5.3.20

**Code**
```
package com.app.rest;

@Configuration
@EnableWebMvc
@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)
@ComponentScan({"com.app.rest"})
public class RestApiServletConfig {

}
```
```
@Configuration
public class RestApiConfig {

    @Bean
    public InfluxConfig influxConfig() {
        return new InfluxConfig() { ... };
    }

    @Bean
    public Clock clock() {
        return Clock.SYSTEM;
    }

    @Bean
    public InfluxMeterRegistry influxMeterRegistry(InfluxConfig influxConfig, Clock clock) {
        return new InfluxMeterRegistry(influxConfig, clock);
    }

    @Bean
    public TimedAspect timedAspect(MeterRegistry registry) {
        return new TimedAspect(registry);
    }
```
```
package com.app.rest;

public class RestApiServletInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class[]{ RestApiConfig.class };
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class[]{ RestApiServletConfig.class };
    }

    @Override
    protected String[] getServletMappings() {
        return new String[]{ "/" };
    }

    // Do I need to add a filter for the TimedAspect Bean?
    @Override
    protected Filter[] getServletFilters() {
        return new Filter[] { new CommonRequestLoggingFilter() };
    }
}
```
```
@RestController
public class UserController {

    private final IDao<User> repository;
    private final InfluxMeterRegistry registry;
    private final Timer timer;

    UserController(IDao<User> repository, InfluxMeterRegistry registry) {
        this.repository = repository;
        this.registry = registry;
        this.timer = Timer
                .builder("http.server.requests")
                .tag("uri","/user/{id}")
                .publishPercentiles(0.5, 0.95, 0.999)
                .publishPercentileHistogram()
                .register(registry);
    }

    @GetMapping("/user/{id}")
    @Timed    // This does not work
    public ResponseEntity<Object> userById(@PathVariable Long id) {
        User user = repository.get(id);

        // I can add timers/counters here if required
        // This works and adds entries to the influxdb
        timer.record(Duration.ofMillis(50));
        timer.record(Duration.ofMillis(20));

        return ResponseEntity.ok(EntityModel.of(user,
                linkTo(methodOn(UserController.class).userById(id)).withSelfRel(),
                linkTo(methodOn(UserController.class).all()).withRel("user")));
    }
```

**Expected behavior**
I would expect @Timed to work somehow.

**Additional context**
Related to https://github.com/micrometer-metrics/micrometer/issues/537

**Comment by shakuzen** [comment] 2022-08-05 01:47
`TimedAspect` is an AspectJ `@Aspect`. See [this section](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop-aspectj-support) of the Spring Framework documentation on AspectJ support. Make sure you have the necessary dependencies and configuration enabled. If it is still not working after trying that, we will probably need a minimal sample project that reproduces the issue to investigate further.

**Comment by ynohtna92** [comment] 2022-08-05 02:17
Thanks for the quick response.

I was missing a dependency for aspectjweaver when I tried to add it last time. 

```
@Configuration
@EnableWebMvc
@EnableAspectJAutoProxy
@EnableHypermediaSupport(type = EnableHypermediaSupport.HypermediaType.HAL)
@ComponentScan({"com.app.rest"})
public class RestApiServletConfig {

}
```

It seems to be logging now in influxdb.

![image](https://user-images.githubusercontent.com/2245318/182987227-6611be69-bb71-4c20-9cd6-6ca70c812067.png)

**Comment by shakuzen** [comment] 2022-08-05 02:26
I'm glad you were able to get it working. I'll close the issue as I think there's no remaining problem.

**Closed by shakuzen** 2022-08-05 02:26 UTC
Labels: question

**Comment by ynohtna92** [comment] 2022-08-05 02:28
Just one quick question. Do I need to put a timed on top of every method I want to log or does it do some of this automatically?

**Comment by shakuzen** [comment] 2022-08-05 02:42
You can put it at the class level, also. There is support in Spring Boot for automatically timing Controller methods, but since you are not using Spring Boot and you're using the TimedAspect, you need to specify which classes/methods to time.
