### ISSUE TITLE
Tomcat ThreadPool metrics still reporting NaN values

### ISSUE THREAD

**Issue by SimoneFalzone** [micrometer-metrics/micrometer#2251] opened 2020-09-02 14:45 UTC
Using  Apache Tomcat Version 9.0.34 with latest micrometer, Tomcat ThreadPool report NAN values.
```
# HELP tomcat_threads_busy_threads  
# TYPE tomcat_threads_busy_threads gauge
tomcat_threads_busy_threads{name="http-nio-0.0.0.0-11080",} 1.0
tomcat_threads_busy_threads{name="ajp-nio-0.0.0.0-11009",} NaN
```
Because like pointedout in [isssue](https://github.com/micrometer-metrics/micrometer/issues/1145), there is now a subtype.
![image](https://user-images.githubusercontent.com/34038878/91997192-1dad3c80-ed3a-11ea-87f7-9f4f39e657ba.png)

Therfore with the current querry 2 `objectNames` are returned, and it depends on the returned order wich  `objectNames` is choosen to register the metric. As a conequence if the subtype e.g. `Tomcat:type=ThreadPool,name="http-nio-8888",subType=SocketProperties` is first in list the metric is not found wich results in NaN problem.
```Java
Set<ObjectName> objectNames = this.mBeanServer.queryNames(new ObjectName(getJmxDomain() + ":" + key + "=" + value + ",*"), null);
```
The problem is that the different thread types are not distinguished and only one value is chosen. Furthermore it is random which of the `objectNames` is chosen (with or without subType). 
It might be better to ask if there are several metrics with different names but the same type and if a subtype is needed.

**Comment by shakuzen** [comment] 2020-09-17 03:29
This should be fixed by the changes in #2262 which handle multiple object names now, and should avoid the subType=SocketProperties by using a more narrow pattern for ThreadPool type metrics. Please try out the latest snapshots or one of the soon to be released versions (1.5.5, 1.3.12, 1.1.18) to confirm if the issue is fixed for your use case.

**Closed by shakuzen** 2020-09-17 03:29 UTC
Labels: bug
