### ISSUE TITLE
Logback metrics stops counting when using Spring Cloud

### ISSUE THREAD

**Issue by ssoerensen** [micrometer-metrics/micrometer#960] opened 2018-10-22 12:40 UTC
I have recently discovered, that logback_metrics stopped recording logline counters, after spring refreshes it's context. this is happening in:

https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java#L131

and is triggered by the event ApplicationEnvironmentPreparedEvent in
https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/context/logging/LoggingApplicationListener.java#L194

I Believe that the log turbofilter should be re registered after the the logging context have been refreshed. I'm just wondering if it is a known issue or if there is a workaround to fix this issue?

**Comment by izeye** [comment] 2018-10-22 13:33
Duplicate of #564

**Closed by izeye** 2018-10-22 13:33 UTC
