### ISSUE TITLE
support java-dogstatsd-client directly

### ISSUE THREAD

**Issue by drobert** [micrometer-metrics/micrometer#2578] opened 2021-04-26 13:57 UTC
The [micrometer datadog documentation](https://micrometer.io/docs/registry/datadog) for dogstatsd states that

> java-dogstatsd-client is not needed on the classpath for this to work. Micrometer uses an alternative, non-blocking UDP implementation

However this seems both unnecessary and problematic due to two main reasons

1. java-dogstatsd-client *has* support for non-blocking UDP (readme references `new NonBlockingStatsDClientBuilder`)
2. the datadog agent supports [origin detection](https://github.com/DataDog/java-dogstatsd-client/blob/1b8b20e3f396e7dc4b22a432266472db7801ca80/README.md#origin-detection-over-udp-and-uds) over UDP/UDS which the micrometer statsd implementation does not

Importantly, origin detection allows for things like the k8s pod id to be automatically applied as a tag to published metrics. It took us a while to track down why our spring boot/micrometer apps were not being tagged the same way our applications were and this seems to be in.

**Comment by shakuzen** [comment] 2021-04-26 15:13
We added support for Datadog's UDP origin detection with #2417. It's available for testing in 1.7.0-RC1 (and 1.7 snapshots) and if nothing terribly wrong is found with it, it will be part of the GA release of Micrometer 1.7.0. Please feel free to try it out and let us know if it works well for you.

While I can understand the sentiment of just using the dogstatsd client, our StatsdMeterRegistry supports multiple flavors, only one of which is dogstatsd. Therefore, we'd have to choose to include dogstatsd as a dependency for everyone, even though it would only be used when the datadog flavor is configured, or we would have to make it an optional dependency and then users would have to add that dependency to use the dogstatsd flavor, which I think is not as good of a user experience.
We can consider other proposals against the current setup if there are good enough reasons, though.
Closing this for now as a duplicate of #2417. Let us know if it's worthwhile considering this more.

**Closed by shakuzen** 2021-04-26 15:13 UTC

**Comment by shakuzen** [comment] 2021-05-07 10:40
Following-up that our [DogStatsD documentation](https://micrometer.io/docs/registry/datadog#_through_dogstatsd_approach) has been updated to include mention of origin detection support. Do let us know if you run into any issues trying it (available now in 1.7.0-RC-1) out so we can get those fixed before the upcoming GA release.
