### ISSUE TITLE
NewRelic Http 403

### ISSUE THREAD

**Issue by marcusbb** [micrometer-metrics/micrometer#1177] opened 2019-01-22 16:09 UTC
Hello, I'm trying to integrate into NewRelic.  I've configured NewRelicConfig appropriately with accountId and apiKey, but I'm getting an error on sending timer and counter metrics.

2019-01-22 10:50:25.319 ERROR 21228 --- [trics-publisher] i.m.newrelic.NewRelicMeterRegistry       : failed to send metrics to new relic: {}

When I debug HttpSender I'm reading that the error is a 403.  I've posted sample payload with cURL to the insights collector api with the same api key and account id successfully (empty response).

I'm using micrometer 1.1.1.

**Comment by izeye** [comment] 2019-02-18 13:53
@marcusbb Based on [the code for the error logging](https://github.com/micrometer-metrics/micrometer/blob/v1.1.1/implementations/micrometer-registry-new-relic/src/main/java/io/micrometer/newrelic/NewRelicMeterRegistry.java#L214), having the "{}" in the error message doesn't seem to be possible. Can you confirm what version of `io.micrometer:micrometer-registry-new-relic` you are using?

**Comment by izeye** [comment] 2019-02-18 14:21
@marcusbb Ah, sorry. I can reproduce this and `response.body()` was "{}".

**Comment by izeye** [comment] 2019-02-18 15:18
My 403 seems to occur due to "Insights None" subscription. I'm not sure there's any free plan for Insights. It'd be good if anyone using Insights confirmed that it's working or not.

@marcusbb Are you using a proper subscription for Insights?

**Comment by marcusbb** [comment] 2019-02-25 20:41
As far as I know I have a valid account.  I described how I was using a simple curl command to the insights URL with success.  

At this point I have moved to using jmx based integration new the NewRelic agent attached to the jvm, scraping the MBeans published by micrometer.

**Comment by handsomehari** [comment] 2019-04-28 16:53
Hi, I'm also facing a similar issue, where I could see 403 error code in the log file. I'm trying to integrate resilience4j metrics to new relic through mircrometer.
ERROR i.m.newrelic.NewRelicMeterRegistry - failed to send metrics to new relic: http 403 {}
Please suggest.

**Comment by handsomehari** [comment] 2019-04-28 17:26
I'm using new relic trail version and trying to publish the metrics to new relic from micrometer.
In the log file, I could see a 403 error code.
ERROR i.m.newrelic.NewRelicMeterRegistry - failed to send metrics to new relic: http 403 {}

**Comment by shakuzen** [comment] 2019-09-27 22:14
I would check with New Relic to make sure that your license includes the Insights API.

**Comment by Mahesh-MSFT** [comment] 2019-11-22 04:45
@shakuzen did you get anything back from New Relic? I am facing same issue. I have a open ticket (https://support.newrelic.com/tickets/377691) pending with New Relic support.

**Comment by shakuzen** [comment] 2019-12-04 06:21
@Mahesh-MSFT I am not a New Relic customer so I have not checked with them. Please do share any findings you might get if they'll be helpful to other users.

**Comment by sudiero** [comment] 2020-02-14 08:53
I had this same problem. Solution was change url to europe data center.
Default url by micrometer is
```https://insights-collector.newrelic.com```
for europe new relic account should be
```https://insights-collector.eu01.nr-data.net```

**Comment by shakuzen** [comment] 2020-04-01 14:06
@sudiero thank you for sharing. I wonder if New Relic denies access from IP addresses outside of the region the URL is for.

**Comment by jkschneider** [comment] 2020-05-07 19:15
Closing this as it seems it is nothing Micrometer can do anything about it, but the user must know and configure the correct URL depending on their region. 

If there's any way that Micrometer can _sense_ the correct URL it should use, we could update the default. I would suggest @sudiero or @Mahesh-MSFT open a ticket with New Relic and ask them to 302 redirect you to the appropriate URL rather than hard failing with 403. That would be a much better user experience...

**Closed by jkschneider** 2020-05-07 19:15 UTC
Labels: registry: new relic
