### ISSUE TITLE
[Stackdriver] One or more of the points specified had an older start time than the most recent point

### ISSUE THREAD

**Issue by cbismuth** [micrometer-metrics/micrometer#1335] opened 2019-03-27 16:16 UTC
Micrometer 1.1.3
Spring Boot 2.1.3.RELEASE

Hi,

We're trying to setup Micrometer with Stackdriver with the Spring Boot integration and we have this error message below. Did we miss some configuration?

Thank you,
Christophe

```
Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries[12,13,18,19,49,50]
```

Stackdriver properties:

```java
@Component
public class StackdriverProperties extends StepRegistryProperties {

    private final String projectId;

    public StackdriverProperties(@Value("${kolsquare.ingest.google.projectId}") final String projectId) {
        this.projectId = projectId;
    }

    public String getProjectId() {
        return projectId;
    }
}
```

Stackdriver configuration:

```java
@Component
public class StackdriverPropertiesConfigAdapter extends StepRegistryPropertiesConfigAdapter<StackdriverProperties> implements StackdriverConfig {

    private final String prefix;

    public StackdriverPropertiesConfigAdapter(final StackdriverProperties properties,
                                              @Value("${kolsquare.ingest.stackdriver.prefix}") final String prefix) {
        super(properties);

        this.prefix = prefix;
    }

    @Override
    public String projectId() {
        return get(StackdriverProperties::getProjectId, StackdriverConfig.super::projectId);
    }

    @Override
    public String prefix() {
        return prefix;
    }
}
```

Meter registry declaration:

```java
@Configuration
public class StackdriverConfig {

    @Bean
    public StackdriverMeterRegistry stackdriverMeterRegistry(final StackdriverConfig config) throws IOException {
        final MetricServiceSettings settings = MetricServiceSettings.newBuilder()
                                                                    .setCredentialsProvider(StackdriverGoogleCredentialsProvider.INSTANCE)
                                                                    .build();

        return StackdriverMeterRegistry.builder(config)
                                       .clock(Clock.SYSTEM)
                                       .metricServiceSettings(() -> settings)
                                       .build();
    }
}
```

Exception:

```
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/gc/live/data/size, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[54]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/gc/max/data/size, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[9]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/memory/committed, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[14,48,51,64,74,76]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/memory/used, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[8,15,22,32,39,53]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/threads/states, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[1,25,26,42,44,63]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/process/cpu/usage, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[43]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/process/uptime, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[40]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/system/cpu/usage, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[24]; Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries[12,13,18,19,49,50]
    at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
    at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
    at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
    at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
    at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
    at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1056)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:748)
    at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
    at java.util.concurrent.FutureTask.run(FutureTask.java)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
        at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
        at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
        at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1156)
        at io.micrometer.stackdriver.StackdriverMeterRegistry.publish(StackdriverMeterRegistry.java:163)
        at io.micrometer.core.instrument.push.PushMeterRegistry.close(PushMeterRegistry.java:69)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
        at io.micrometer.core.instrument.composite.CompositeMeterRegistry.close(CompositeMeterRegistry.java:232)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:337)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:271)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1052)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1059)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1035)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1011)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:931)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/gc/live/data/size, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[54]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/gc/max/data/size, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[9]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/memory/committed, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[14,48,51,64,74,76]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/memory/used, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[8,15,22,32,39,53]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/jvm/threads/states, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[1,25,26,42,44,63]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/process/cpu/usage, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[43]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/process/uptime, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[40]; One or more points were written more frequently than the maximum sampling period configured for the metric. {Metric: custom.googleapis.com/system/cpu/usage, Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}}: timeSeries[24]; Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries[12,13,18,19,49,50]
    at io.grpc.Status.asRuntimeException(Status.java:526)
    ... 24 more
```

**Comment by shakuzen** [comment] 2019-03-28 03:20
`Timestamps: {Youngest Existing: '2019/03/27-09:04:51.023', New: '2019/03/27-09:04:51.023'}` leads me to believe reporting is happening twice at the same timestamp. I'm not sure how that would happen.

**Comment by checketts** [comment] 2019-03-28 03:42
Could they have duplicate registries? Then it would punish twice at the same time?

**Comment by shakuzen** [comment] 2019-03-28 16:48
@cbismuth would you be able to provide a sample project that reproduces this issue using Micrometer? That would help me be able to debug what's happening.

**Comment by cbismuth** [comment] 2019-03-28 16:54
> Could they have duplicate registries? Then it would publish twice at the same time?

I can safely say no, I've created a Spring test with an injection of all beans of type `StackdriverMeterRegistry` and the list of beans has a size of 1.

**Comment by cbismuth** [comment] 2019-03-28 16:55
> @cbismuth would you be able to provide a sample project that reproduces this issue using Micrometer? That would help me be able to debug what's happening.

I'll try to do so.

**Comment by 1mdc** [comment] 2021-03-27 22:44
Hi, I have the same problem in `micrometer-registry-stackdriver:1.6.5`
My code is quite simple, it has same meter name but different tags:
```
var metricKey = String.format("%s_%s", obj.getMetricName(), key).toLowerCase();
if (!metrics.containsKey(metricKey)) {
  log.info("creating new metric {} type={}", obj.getMetricName(), key);
  metrics.put(metricKey, meterRegistry.counter(obj.getMetricName(), "type", key));
}
log.info("Recording metric {}: {}", metricKey, value);
metrics.get(metricKey).increment(value);
```
I looked the log and it never duplicates metric key.

**Comment by hixichen** [comment] 2021-06-16 21:34
same here with k8s deployment:
 ```
      - name: sidecar
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.8.2
  ```
  
  
`  prometheus-deployment-7c8ffbbfdd-664xd sidecar level=warn ts=2021-06-16T21:34:15.489Z caller=queue_manager.go:534 component=queue_manager msg="Unrecoverable error sending samples to remote storage" err="rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries[0-199]"`

**Comment by shakuzen** [comment] 2021-08-17 06:41
> So basically it's not my custom metric triggering the exception but the built it ones, in this case `process` which was the only one not disabled.

Can you reproduce this consistently? If so, can you share a minimal sample project I can run to investigate? I have run samples that include process metrics and did not see the error message, so I am having trouble reproducing.

**Comment by torakiki** [comment] 2021-08-17 14:09
It happens consistently in a GKE cluster with 2 nodes and 2 pods, it doesn't happen in my single pod dev environment. Do your samples run in a similar env? I assumed the issue is that both pods are sending at the same time the same metric tags to Stackdriver and that ends with a fail of one of the requests but I don't have enough knowledge of the products involved.. I can try to set up a minimal example

**Comment by shakuzen** [comment] 2021-08-18 03:56
Alright. I think I was able to reproduce running two instances locally. Adding a common tag unique to each instance made the issue go away though. We should update the documentation to stress the need to tag metrics so instances don't write the same metrics. If adding a common tag unique to the instance is not working, please share how you are configuring the common tag. Common tags need to be configured before any meters are bound for them to be applied to all meters.

**Comment by torakiki** [comment] 2021-08-18 08:16
Ok, I reproduced it locally too with two instances. So this is what I was doing:
```
@Profile("metrics")
@Service
public class DefaultMetricsService implements MetricService {

    @Autowired
    private MeterRegistry registry;

    @Value("${HOSTNAME}")
    private String hostname;

    @PostConstruct
    private void commonsTags() {
        registry.config().commonTags("host", defaultIfBlank(hostname, "UNKNOWN"));
    }

    @Override
    public void increment(Metric metric, KeyValue... tags) {
        registry.counter(metric.metric(), Arrays.stream(tags).map(t -> Tag.of(t.key, t.value)).collect(toList()))
                .increment();
    }

}
```
Using this service bean the commons tag are added to my custom metrics but they are not added to the built in metrics and that leads to the Exception. 
I followed the documentation and added it to the application.properties and common tags are now added to all the metrics:
```
management.metrics.tags.host=${HOSTNAME}
```

**Comment by shakuzen** [comment] 2021-08-20 05:58
I've created https://github.com/micrometer-metrics/micrometer-docs/pull/191 to document what I believe to be the resolution of this issue. Feel free to leave feedback on the documentation changes there (even post-merge). I am closing this issue as I believe that addresses how to stop this problem. Let us know if that's not the case.

**Closed by shakuzen** 2021-08-20 05:58 UTC
Labels: doc-update, registry: stackdriver

**Comment by lbaeumer** [comment] 2021-11-01 20:49
I stripped down my app to a minimum set of code, cmp. https://github.com/lbaeumer/micrometer-stackdriver-issue
There are only 4 calls to send metrics with a different measurement name, different value and key name.
After deploying this to GAE I get the above error. Checkout the info in the README.md of the provided link for detailed info.

**Comment by jonatan-ivanov** [comment] 2021-11-03 20:17
@lbaeumer I think I don't consider this as minimal (given having a DTO, service, util).
Also, you are only setting tags for one counter and your value is not unique, your key is.

Could you please try to set a unique value of a key (let's call it `instance`) for every meter? See the docs how to do it: https://micrometer.io/docs/concepts#_common_tags

**Comment by lbaeumer** [comment] 2021-11-04 21:39
Now I reproduced the error with a simpler testcase. You find all code in a single class. Everything is unique now. The key and value for the tag and the value of the common tag. The problem occurs if I start 4 GAE instances at the same time. It even fails if I start only 2 instances at the same time.
Invoking all 4 requests in a row is ok, the error does not occur as only 1 GAE instance will be started.

**Comment by rocketraman** [comment] 2021-11-13 06:59
@lbaeumer I was having the same issue. I got it working with the information in this comment: https://github.com/micrometer-metrics/micrometer/issues/1907#issuecomment-601346553.
