### ISSUE TITLE
Metrics' eviction

### ISSUE THREAD

**Issue by Sic4Parvis9Magna** [micrometer-metrics/micrometer#2116] opened 2020-05-21 19:42 UTC
Probably I overlooked it while reading the documentation, even so, I have to ask.
I would like to know if micrometer supports something like cache eviction functionality (I  am aware about cache metrics support, but it is not that I want).
I mean support for the following workflow:
1. new metric added to the registry
2. it is updated after a while
3. if the metric does not updated after specified amount of time the metric will be removed from the registry

Does micrometer support that?

**Comment by shakuzen** [comment] 2020-05-25 02:58
Duplicate of #1114

**Closed by shakuzen** 2020-05-25 02:58 UTC

**Comment by huzais520** [comment] 2023-03-26 14:36
Just wondering if eviction's been supported?

**Comment by shakuzen** [comment] 2023-03-27 03:15
See the linked issue #1114 for the latest. It has not been implemented. Feel free to share your use case on that issue so we can better understand the priority and scenario in which the need for this is coming up.
