### ISSUE TITLE
`MeterRegistry.remove()` blocks a thread for a long time

### ISSUE THREAD

**Issue by ikhoon** [micrometer-metrics/micrometer#5743] opened 2024-12-13 05:03 UTC
**Describe the bug**

We have a giant monolithic server that handles LINE messages. The server produces tons of metrics so a small delay could be critical.

`MeterRegistry.remove()` was not a problem when a small number of connections were closed but when 100+ connections were closed simultaneously. Many event loops were blocked to acquire a lock to call `MeterRegistry.remove()`, resulting in an outage.
https://github.com/line/armeria/blob/0b204554fedde24c79e001a1bc153bee24a011cc/core/src/main/java/com/linecorp/armeria/client/ConnectionPoolMetrics.java#L79-L91

We released a hotfix to not call `MeterRegistry.remove()` directly. A scheduled job was added to remove inactive `Meter` periodically instead.The issue has been resolved, but I would like to improve the performance of `MeterRegistry.remove()` to avoid similar issues in the future.  

**Environment**

 - Micrometer version 1.13.6
 - OS: Linux
 - Java version: 11

**Expected behavior**

Unfortunately, there is no profile of what part inside `MeterRegistry.remove()` was taking so long. When I checked the code, the iteration of `preFilterIdToMeterMap` may take long. 
https://github.com/micrometer-metrics/micrometer/blob/3c53a7c5a1b25c14a4647482dfcbca2da692ce36/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L777-L784
So I suggest adding a reverse map to avoid iterating `preFilterIdToMeterMap`.

**Additional context**

- https://github.com/line/armeria/pull/6024

**Comment by shakuzen** [comment] 2024-12-16 07:40
@ikhoon thank you for all the details and reporting this. Sorry for the issues this caused. I believe this is a duplicate of https://github.com/micrometer-metrics/micrometer/issues/5466. We still need to figure out how best to fix that, but it sounds like most people badly affected by this are wanting the feature of automatically removing old/inactive meters. I wonder if we had that feature if we could do it in a more performant way than removing a generic meter.

**Comment by shakuzen** [comment] 2024-12-16 07:41
Duplicate of #5466

**Closed by shakuzen** 2024-12-16 07:41 UTC
Labels: waiting-for-triage

**Comment by ikhoon** [comment] 2024-12-17 02:42
It would be useful if Micrometer offered an API that removes inactive meters in certain conditions, similar to other cache implementations.

That being said, many people don't realize that the `MeterRegistry.remove()` operation is not scalable. I think the most important thing is to improve the `MeterRegistry.remove()` operation so that it has performance close to `HashMap`'s remove, O(1).
