### ISSUE TITLE
WebIdentityTokenCredentialsProvider() error when utilizing AWS EKS IRSA

### ISSUE THREAD

**Issue by romelBen** [micrometer-metrics/micrometer#3783] opened 2023-04-20 16:10 UTC
Hello everyone. I'm currently updating code for our project and ran into this error when upgrading `aws-java-sdk` from version 1.12.x to 2.x. An error that frequently pops up is in regards to Micronaut's usage of micrometer's technology to push metrics from the pod to AWS CloudWatch. However, this error pops up frequently:

```
"message":"error sending metric data.",
"logger_name":"io.micrometer.cloudwatch2.CloudWatchMeterRegistry",
"thread_name":"Thread-2",
"level":"ERROR",
"level_value":40000,
"stack_trace":"
    java.util.concurrent.CompletionException:
    software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain
        AwsCredentialsProviderChain(credentialsProviders=[
            SystemPropertyCredentialsProvider(),
            EnvironmentVariableCredentialsProvider(),
            WebIdentityTokenCredentialsProvider(),
            ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])), 
            ContainerCredentialsProvider(),
            InstanceProfileCredentialsProvider()
        ]) : [
            SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).,
            EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).,
            WebIdentityTokenCredentialsProvider(): Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, 
            ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])): Profile file contained no credentials for profile 'default': ProfileFile(profilesAndSectionsMap=[]),
            ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set.,
            InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.
        ]
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
    at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
    at software.amazon.awssdk.services.cloudwatch.DefaultCloudWatchAsyncClient.putMetricData(DefaultCloudWatchAsyncClient.java:3382)
    at io.micrometer.cloudwatch2.CloudWatchMeterRegistry.sendMetricData(CloudWatchMeterRegistry.java:113)
    at io.micrometer.cloudwatch2.CloudWatchMeterRegistry.publish(CloudWatchMeterRegistry.java:93)
    at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:52)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: 
    software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain
    AwsCredentialsProviderChain(
        credentialsProviders=[
            SystemPropertyCredentialsProvider(),
            EnvironmentVariableCredentialsProvider(),
            WebIdentityTokenCredentialsProvider(),
            ProfileCredentialsProvider(profileName=default,profileFile=ProfileFile(profilesAndSectionsMap=[])),
            ContainerCredentialsProvider(),
            InstanceProfileCredentialsProvider()
        ]) : [
            SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).,
            EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).,
            WebIdentityTokenCredentialsProvider(): Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target,
            ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[])): Profile file contained no credentials for profile 'default': ProfileFile(profilesAndSectionsMap=[]),
            ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set.,
            InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.
        ]
    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)

```
The culprit is this section:
`WebIdentityTokenCredentialsProvider(): Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

With these kind of issues, adding `implementation("software.amazon.awssdk:sts:2.17.277")` is sufficient enough to fix this issue; nevertheless, it errors with the above issue.

My question is, what could be causing this issue when it was working before where IRSA began to give issues? What other packages would be necessary to resolve this error? Would appreciate any feedback.

**Environment**
 - Micrometer version: 2.5.11
 - Micrometer registry: CloudWatchRegistry
 - OS: Debian
 - Java version: java 11.0.16

**Comment by jonatan-ivanov** [comment] 2023-04-20 22:32
This means that the AWS SDK is not able to fetch credentials from any of the sources in its fallback-chain. Please read the whole error message, it helps if you convert the stacktrace back to a readable format (I edited the issue and did this for you).

The issue you highlighted means that the TLS certificate chain that the destination of this (HTTPS) connection uses is not trusted by your application (JVM). (Search for the error message for more details.)
```
Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I'm not sure what you are trying to do or if this is your root cause or not but I'm fairly certain this has not much to do with Micrometer. Please try to use anything else from the AWS SDK, they will fail the same way. With this, let me close the issue, please let us know that I misunderstood something and we can reopen.

**Closed by jonatan-ivanov** 2023-04-20 22:32 UTC
Labels: waiting-for-triage

**Comment by romelBen** [comment] 2023-04-21 14:11
Thank you @jonatan-ivanov. I've searched this error but have not received a solution to the error. I'll continue looking into this error more.

**Comment by jonatan-ivanov** [comment] 2023-04-24 22:52
I searched for `SunCertPathBuilderException: unable to find valid certification path to requested target` in Google, the first hit was this SO question: https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find, the first answer tells you what to do (add the cert to your truststore).

**Comment by romelBen** [comment] 2023-04-26 19:55
Thanks. I'm sorry to not respond during this time but we have been able to resolve this issue. This was on our side when certs were being pulled to our pod for AWS DocumentDB. Thank you are for help!
