### ISSUE TITLE
Not sending metrics after stop and start of the StatsdMeterRegistry

### ISSUE THREAD

**Issue by uchandroth** [micrometer-metrics/micrometer#1676] opened 2019-10-29 10:50 UTC
Environment :   spring-boot 2.2.0.RELEASE
micrometer-registry-statsd : 1.3.0 also tried with older versions
steps to replicate the issue:

1.  Once the application is started statsd metrics will be start pumping to stats daemon running on 8125 udp port
2. invoke StatsdMeterRegistry.stop() --> which will shutdown the udp client
3. invoke StatsdMeterRegistry.start() --> which will start the udp client.  debug mode we can see that udp client status is started
But statsd metrics will not be send.
could you please help to understand the issue. Or is this the right way to reinitialise the connection

Background of the issue : we are using a stasd daemon with a dns name, if the deamon is restarted the ip address maybe different, because of the dns caching udp client will not be able to connect to the    stasd daemon if the ip address is different.
We have tried setting networkaddress.cache.ttl=10 but it is not getting affected for the StatsdMeterRegistry UdpClient object

**Comment by shakuzen** [comment] 2019-10-30 14:34
This looks like a duplicate of #1252

**Comment by shakuzen** [comment] 2019-10-31 05:28
I'd like to verify but I think this will be an issue when stopping and starting the registry even if not changing the address. See https://github.com/micrometer-metrics/micrometer/issues/1252#issuecomment-548222033. This will probably be obviated when we stop having the issue with only a single subscriber allowed to the publisher (see https://github.com/micrometer-metrics/micrometer/pull/1251#issuecomment-469220750)

**Closed** 2020-01-27 08:33 UTC
Labels: bug, registry: statsd

**Comment by shakuzen** [comment] 2020-01-27 08:48
Stopping and starting the `StatsdMeterRegistry` should work correctly now. Could you try with the latest `1.4.0-SNAPSHOT` version and let us know if it is working for you?

**Comment by uchandroth** [comment] 2020-02-06 09:50
micrometer-registry-statsd 1.4.0-snapshot with spring boot 2.2.0.RELEASE, 2.2.4.RELEASE release will  throw java.lang.NoClassDefFoundError: io/micrometer/shaded/reactor/core/publisher/FluxSink
FluxSink class was part of the micrometer-registry-statsd 1.3.0 jar.
Could please let me know how can we can integrate micrometer-registry-statsd.1.4.0-snapshot with springboot

**Comment by shakuzen** [comment] 2020-02-06 13:06
Thanks for trying things out. Indeed it looks like the shaded dependencies are missing from the latest snapshots. I've opened #1843 to fix that. Once that is fixed, if you could try again, things should work.

**Comment by shakuzen** [comment] 2020-02-07 06:44
@uchandroth could you try again with the latest snapshots now that a fixed has been merged for the `NoClassDefFoundError`?

**Comment by uchandroth** [comment] 2020-03-05 11:14
@shakuzen could you please let me know the release version of micrometer-registry-statsd which has this fix

**Comment by shakuzen** [comment] 2020-03-05 13:04
For now it is only available in the snapshot version `1.4.0-SNAPSHOT`. It will be available in 1.4.0 when that is released.

**Comment by uchandroth** [comment] 2020-03-06 08:52
@shakuzen thanks for the update
