### ISSUE TITLE
Provide a way to instantiate Quantiles from a string specification

### ISSUE THREAD

**Issue by trustin** [micrometer-metrics/micrometer#88] opened 2017-08-10 02:57 UTC
For example:

```java
QuantilesSpec spec = QuantilesSpec.parse("ckms:0.5,0.75,...");
Quantiles quantiles = spec.createQuantiles();
```

This is going to be useful when a user wants to move the quantiles configuration to an external resource such as .properties file and System property. Inspired by `CaffeineSpec` from Caffeine.

**Comment by jkschneider** [comment] 2017-10-19 21:48
Duplicate of #146.

**Closed by jkschneider** 2017-10-19 21:48 UTC
