### ISSUE TITLE
Hystrix thread pool metrics

### ISSUE THREAD

**Issue by starlight36** [micrometer-metrics/micrometer#1400] opened 2019-04-26 10:55 UTC
Hi, I'm looking for Hystrix thread pool metrics support. Some metric indexs like `currentActiveCount` or `currentLargestPoolSize` is useful to calculate runtime properties. 

In [MicrometerMetricsPublisher.java](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/hystrix/MicrometerMetricsPublisher.java)  , only `getMetricsPublisherForCommand` has a micrometer publisher, thread pool metrics is not implemented. 

There is a pull request [1229](https://github.com/micrometer-metrics/micrometer/pull/1229) , looks a good implementation to fulfill this requirement.

**Comment by izeye** [comment] 2019-07-02 23:19
Duplicate of #1229

**Closed by izeye** 2019-07-02 23:19 UTC
