### ISSUE TITLE
Java service is not publishing micrometer metrics to AWS cloudwatch

### ISSUE THREAD

**Issue by VinithaYamsani** [micrometer-metrics/micrometer#2521] opened 2021-03-23 06:37 UTC
Hi all,
I have a java service from where I want to publish micrometer metrics to cloudwatch. The following versions of spring dependencies are being used -

```
<dependencyManagement>
     <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>2.3.9.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Hoxton.SR10</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-aws</artifactId>
    </dependency>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-registry-cloudwatch</artifactId>
    </dependency>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-core</artifactId>
    </dependency>
</dependencies>
```
and the following spring cloud configuration is done in application.yaml file -
```
cloud.aws:
  stack.auto: false
  region:
    auto: false
    static: us-east-1
management:
  metrics.export.cloudwatch:
    namepsace: example-namespace
    batchSize: 20
    enabled: true
```
then we configure the common tags in micrometer config file -
```
@Bean
public MeterRegistryCustomizer<MeterRegistry> configureCommonTags() {
    return registry -> registry
            .config()
            .commonTags(new String[]{"service", "service-name"});
}
```
and to populate the metrics - 

```
public class SampleMetric {
private final AtomicInteger loggedIn = Metrics.gauge("metric_name", new AtomicInteger(0));

public void onLogin() {
loggedIn.set(1);
}

public void onLogout() {
loggedIn.set(0);
}
}
```
With this configuartion, the service is not able to publish the micrometer metrics to cloudwatch, I could neither see any logs related to this metric publishing in cloudwatch.
I have few other java apps which uses these dependency versions and they are able to publish the metrics fine.
Unable to figure out what the issue could be here, please advise.
Thanks in advance.

**Comment by shakuzen** [comment] 2021-03-23 08:28
Could you provide a minimal sample project that reproduces the issue? The Spring Cloud AWS project may be a better place to start this issue since that is where the auto-configuration lives.

**Comment by VinithaYamsani** [comment] 2021-03-23 11:41
@shakuzen, I have added the sample code

**Comment by shakuzen** [comment] 2021-03-24 03:21
I was able to publish metrics to CloudWatch using the same versions you mentioned. I don't know how you're configuring your credentials, but I would expect some error logs if credentials are an issue. You can try turning on DEBUG logging for Micrometer with `logging.level.io.micrometer=DEBUG` which will show successful publishes of metrics. Note it took several minutes before I could actually see the metrics in the CloudWatch Metrics console that I had sent initially.

**Comment by shakuzen** [comment] 2021-03-25 08:10
Closing since I cannot reproduce the issue. Let us know if there's any additional information on this and we can reopen if there is something to change in Micrometer.

**Closed by shakuzen** 2021-03-25 08:10 UTC
Labels: feedback needed, registry: cloudwatch

**Comment by izeye** [comment] 2021-04-01 09:18
@VinithaYamsani The `application.yaml` file you shared has a typo. `namepsace` should be `namespace` based on [its reference doc](https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC1/reference/html/index.html#cloudwatch-metrics).
