### ISSUE TITLE
DiskSpaceMetrics returns NaN when garbage collected

### ISSUE THREAD

**Issue by ciccio14** [micrometer-metrics/micrometer#1409] opened 2019-05-03 14:14 UTC
When using standard DiskSpaceMetrics, metrics returned are always NaN
Jon said that it is a known issue:
> there is an issue with that binder where we should have used a strong reference gauge

Jon also has given a workaround:

```java
Iterable<Tag> tagsWithPath = Tags.concat(tags, "path", absolutePath);
        Gauge.builder("disk.free", path, File::getUsableSpace)
                .strongReference(true)
                .tags(tagsWithPath)
                .description("Usable space for path")
                .baseUnit("bytes")
                .register(registry);
        Gauge.builder("disk.total", path, File::getTotalSpace)
                .strongReference(true)
                .tags(tagsWithPath)
                .description("Total space for path")
                .baseUnit("bytes")
                .register(registry);
```

**Comment by shakuzen** [comment] 2019-05-14 15:21
> When using standard DiskSpaceMetrics, metrics returned are always NaN

Could you share how you are configuring `DiskSpaceMetrics`? I am not able to reproduce this issue.

**Comment by ciccio14** [comment] 2019-05-15 06:57
i'm using it like this:
 `PrometheusMeterRegistry prometheusRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
new DiskSpaceMetrics(new File("/")).bindTo(prometheusRegistry);`

**Comment by shakuzen** [comment] 2019-05-15 15:49
Did you figure out what the cause was or did you not mean to close the issue?
Is `new File("/")` returning an accessible directory when you are trying? From the Prometheus endpoint, I'm seeing 

```
# HELP disk_free_bytes Usable space for path
# TYPE disk_free_bytes gauge
disk_free_bytes{path="/",} 3.98410305536E11
# HELP disk_total_bytes Total space for path
# TYPE disk_total_bytes gauge
disk_total_bytes{path="/",} 4.99963174912E11
```

**Comment by ciccio14** [comment] 2019-05-16 09:23
I had a chat with Jon Schneider, he tells me that DiskSpaceMetrics has an issue:
"there is an issue with that binder where we should have used a strong reference gauge"
Jon also give the workaround, you must replace the existing code (lines 57-67 of DiskSpaceMetrice.java) with this one;
`Iterable<Tag> tagsWithPath = Tags.concat(tags, "path", absolutePath);
        Gauge.builder("disk.free", path, File::getUsableSpace)
                .strongReference(true)
                .tags(tagsWithPath)
                .description("Usable space for path")
                .baseUnit("bytes")
                .register(registry);
        Gauge.builder("disk.total", path, File::getTotalSpace)
                .strongReference(true)
                .tags(tagsWithPath)
                .description("Total space for path")
                .baseUnit("bytes")
                .register(registry);`

**Comment by shakuzen** [comment] 2019-05-17 07:37
I don't think it has an issue. A reference to the `path` is kept as a class field: https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/DiskSpaceMetrics.java#L42

So it shouldn't need to set `strongReference` to `true`. This is why I'm asking for a way to reproduce the behavior where it is returning NaN.

**Comment by ciccio14** [comment] 2019-05-17 09:50
> I don't think it has an issue. 

you don't think that this metrics as an issue, Jon Schneider (the creator of micrometer library) thinks that this metrics HAS an issue. Speak with him and explain to him your ideas.
With the workaround provided by Jon i resolved my issue, so for me this is an issue closed

**Comment by roded** [comment] 2019-06-12 15:34
I'm experiencing the same issue with micrometer 1.1.4.
Setting the Gauge's strongReference to `true` has resolved the issue as suggested.

@shakuzen, regarding the `path` reference: I think that that would work if a reference to `DiskSpaceMetrics` was retained in using code. However, I assume some (or most?) users do the following:
`new DiskSpaceMetrics(new File("/"), tags).bindTo(compositeRegistry);` in which case the `path` won't be retained.

I believe that this issue should be reopened.

**Comment by shakuzen** [comment] 2019-06-12 17:20
> I think that that would work if a reference to `DiskSpaceMetrics` was retained in using code. However, I assume some (or most?) users do the following:
> `new DiskSpaceMetrics(new File("/"), tags).bindTo(compositeRegistry);` in which case the `path` as well as the `DiskSpaceMetrics` object won't be retained.

@roded thank you for having the patience to explain how this could be reproduced. I have now reproduced this and we'll get it fixed.

**Closed** 2019-06-14 06:01 UTC
Labels: bug
