### ISSUE TITLE
io.micrometer.core.instrument.Metrics should support setting a description for a metric

### ISSUE THREAD

**Issue by eyalrin** [micrometer-metrics/micrometer#2866] opened 2021-11-16 15:24 UTC
**Please describe the feature request.**
when registering metrics using the ```Metrics``` generator class (i.e. ```io.micrometer.core.instrument.Metrics```) we should be able to provide a "description" in addition to the name and tags. 

**Rationale**
Currently all metrics created using the ```Metrics``` generator class are generated with an empty description, but when using the metrics builder classes it is possible to provide a description. Both methods should support the same functionality,

**Comment by jonatan-ivanov** [comment] 2021-11-24 00:51
Hi @eyalrin,
This is by design, please see my reply here: https://github.com/micrometer-metrics/micrometer/pull/2863#issuecomment-977314650

I'm closing this as a duplicate of #2863

**Closed by jonatan-ivanov** 2021-11-24 00:51 UTC
Labels: enhancement
