### ISSUE TITLE
JDBCTemplate metrics

### ISSUE THREAD

**Issue by cemo** [micrometer-metrics/micrometer#643] opened 2018-06-06 07:53 UTC
I had to dig our metrics to detect some problems. I had to write a simple JdcbTemplate implementation. Here is the code: 

https://gist.github.com/cemo/6d2572380c8b4b9e0b1800e67a08880c

Supporting JDBCTemplate would be nice.

**Comment by gavlyukovskiy** [comment] 2018-07-27 14:53
I think it would be more generic to instrument DataSource itself instead of JdbcTemplate, for example it could be done using [p6spy](https://github.com/p6spy/p6spy) or [datasource-proxy](https://github.com/ttddyy/datasource-proxy/) and it will work not only for JdbcTemplate, but also for jdbi, hibernate, jooq and regular jdbc.
I've done something similar, but it were not query metrics, but connection pool metrics - https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/master/datasource-decorator-spring-boot-autoconfigure/src/main/java/com/github/gavlyukovskiy/micrometer/DataSourceMetricsHolder.java

**Comment by sganslandt** [comment] 2018-10-02 22:32
+1 on this. I've been longing for a feature like this for many years (shame on me for not taking the matters into my hands). Something that gives similar metrics as the mysql slow log, when setting the slow thresh hold to 0, but just the histograms and not the actual full log.

**Comment by jkschneider** [comment] 2018-10-05 14:49
Closing this as a duplicate of #635, though this issue does have useful context.

**Closed by jkschneider** 2018-10-05 14:49 UTC
