### ISSUE TITLE
INTERNAL: Internal error encountered. Please retry after a few seconds. If internal errors persist, contact support at https://cloud.google.com/support/docs.

### ISSUE THREAD

**Issue by drieselliott** [micrometer-metrics/micrometer#2190] opened 2020-07-14 15:19 UTC
Hi,

When using the Stackdriver integration from Micrometer in a Spring Boot application, I see quite some Internal errors.

An example:

```
com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered. Please retry after a few seconds. If internal errors persist, contact support at https://cloud.google.com/support/docs.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67) ~[gax-1.54.0.jar:1.54.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) ~[gax-grpc-1.54.0.jar:1.54.0]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) ~[gax-grpc-1.54.0.jar:1.54.0]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[gax-grpc-1.54.0.jar:1.54.0]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) ~[api-common-1.8.1.jar:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039) ~[guava-28.2-android.jar:na]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.2-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165) ~[guava-28.2-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-28.2-android.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749) ~[guava-28.2-android.jar:na]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:522) ~[grpc-stub-1.27.2.jar:1.27.2]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497) ~[grpc-stub-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.27.2.jar:1.27.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.27.2.jar:1.27.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-1.54.0.jar:1.54.0]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-1.54.0.jar:1.54.0]
		at com.google.cloud.monitoring.v3.MetricServiceClient.createTimeSeries(MetricServiceClient.java:1150) ~[google-cloud-monitoring-1.99.2.jar:1.99.2]
		at io.micrometer.stackdriver.StackdriverMeterRegistry.publish(StackdriverMeterRegistry.java:175) ~[micrometer-registry-stackdriver-1.3.2.jar:1.3.2]
		at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48) [micrometer-core-1.3.2.jar:1.3.2]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_252]
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_252]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_252]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_252]
		... 3 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Internal error encountered. Please retry after a few seconds. If internal errors persist, contact support at https://cloud.google.com/support/docs.
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.27.2.jar:1.27.2]
	... 16 common frames omitted
```

I'm using the default Micrometer configuration in Sping Boot with Actuator enabled.

I logged a ticket for this in the Google issue tracker for Stackdriver, but they seem to think it has to do with the Micrometer integration. (https://issuetracker.google.com/issues/161057612)

When I have some time I'll try to dig up some more context. Meanwhile, I was wondering if you've seen this issue before. It could be that some additional retry logic might need to be added in the library.

Is there some debug logging I can enable to get some more info?

**Comment by shakuzen** [comment] 2020-07-22 11:53
We have seen this before, but it is a bit generic. Without a more specific error than `AsyncTaskException: Asynchronous task failed` it is hard to say what we are doing wrong in Micrometer code. It looks like the call to `createTimeSeries` is failing, but why is the question I think we need answered.
Please also make sure you are using the latest versions available when reproducing this.

**Comment by shakuzen** [comment] 2021-08-20 06:59
Were you ever able to get more context on this? If we could reliably reproduce this, we could look into it more. Without being able to do that, it will be hard for us to make progress on this.

**Comment by shakuzen** [comment] 2021-08-25 07:45
Closing due to not being able to reliably reproduce this. If we can get information about how to reproduce it, we can reopen and look into this.

**Closed by shakuzen** 2021-08-25 07:45 UTC
Labels: registry: stackdriver, feedback needed
