### ISSUE TITLE
Monitor the tomcat connection metrics to know the situation about server connections with client

### ISSUE THREAD

**Issue by puppylpg** [micrometer-metrics/micrometer#2258] opened 2020-09-10 15:08 UTC
Thanks for micrometer, helps me a lot with monitoring. 

However, is #2248 considered? I think it's important and easy to add at the same time.

**Comment by shakuzen** [comment] 2020-09-17 02:19
Thank you for the pull request. We can track the enhancement with that, so I will close this issue.
Duplicate of #2248

**Closed by shakuzen** 2020-09-17 02:19 UTC
