### ISSUE TITLE
After upgrading to spring boot 2.7.0 the http_server_requests_seconds prometheus metric is missing.

### ISSUE THREAD

**Issue by Thangaduraia** [micrometer-metrics/micrometer#3273] opened 2022-07-06 18:15 UTC
**Describe the bug**
After upgrading the spring boot version to 2.7.0 **_TYPE http_server_requests_seconds summary_** is missing in metrics.

**Environment**
 - Micrometer version 1.9.0
 - Micrometer registry- prometheus
 - Java version: 11

**To Reproduce**
How to reproduce the bug:
Use spring boot version 2.7.0, micrometer version 1.9.0

**Expected behavior**
Expected the http_server_requests_seconds_count prometheus metric.
`http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/userInfo/",} 4.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/userInfo/",} 0.051901905
http_server_requests_seconds_max{exception="None",method="GET",outcome="REDIRECTION",status="304",uri="/**",} 0.0`

I am not able find any document related this change. Is additional config we need to do?

**Comment by izeye** [comment] 2022-07-06 18:20
@Thangaduraia It seems to be a duplicate of https://github.com/spring-projects/spring-boot/issues/31150. Could you try Spring Boot 2.7.1 to see if it fixes your issue?

**Comment by shakuzen** [comment] 2022-07-07 01:37
Duplicate of https://github.com/spring-projects/spring-boot/issues/31150

**Closed by shakuzen** 2022-07-07 01:37 UTC
Labels: duplicate, for: external-project

**Comment by Thangaduraia** [comment] 2022-07-07 04:59
@shakuzen @izeye Thanks. After updating I can see the metric.
