### ISSUE TITLE
java.lang.NoClassDefFoundError: io/prometheus/metrics/expositionformats/ExpositionFormats

### ISSUE THREAD

**Issue by bogedal** [micrometer-metrics/micrometer#5104] opened 2024-05-15 13:37 UTC
**Describe the bug**
I upgraded from io.micrometer:micrometer-registry-prometheus:1.12.5 to io.micrometer:micrometer-registry-prometheus:1.13.0 in my Javalin.io service
```
implementation("io.javalin:javalin:6.1.4")
implementation("io.javalin:javalin-micrometer:6.1.4")

```

Now when starting the service I get this error
java.lang.NoClassDefFoundError: io/prometheus/metrics/expositionformats/ExpositionFormats

**Environment**
 - Micrometer version : 1.13.0
 - Micrometer registry: prometheus
 - Java version: java 21

Initial configuration is done like this

```
PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
MicrometerPlugin micrometerPlugin = new MicrometerPlugin(pluginConfig -> pluginConfig.registry = registry);

new UptimeMetrics().bindTo(registry);

registry.config().meterFilter(MeterFilter.deny(id -> {
     String name = id.getName();
     return name.startsWith("jetty.") || name.startsWith("jvm.buffer.count.buffers");
}));
Javalin app = Javalin.create(javalinConfig -> javalinConfig.registerPlugin(micrometerPlugin)).start(7000);

```

**Expected behavior**
Is this because you no longer bundle this dependency and I have to add it myself or is this not expected behavior ?

**Comment by ttddyy** [comment] 2024-05-15 17:59
Hi @bogedal 
If you are using prometheus client `0.x` then you need to use `micrometer-registry-prometheus-simpleclient`.
In micrometer `1.13`, `micrometer-registry-prometheus` is for prometheus client `1.x`.

You can find the details in ["1.13 Migration Guide"](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide) as well as https://github.com/micrometer-metrics/micrometer/issues/5093#issuecomment-2108940744.

**Comment by jonatan-ivanov** [comment] 2024-05-15 22:12
Duplicate of https://github.com/micrometer-metrics/micrometer/issues/5093

**Closed by jonatan-ivanov** 2024-05-15 22:12 UTC
Labels: waiting-for-triage

**Comment by bogedal** [comment] 2024-05-16 04:20
@ttddyy Ah I see where I went wrong here. I need to wait for Javalin.io to bump their micrometer version to 1.13.0+ as well.
Thanks for the quick response 👍

**Comment by jonatan-ivanov** [comment] 2024-05-16 18:54
You can also exclude
```
micrometer-registry-prometheus
```
and include
```
micrometer-registry-prometheus-simpleclient
```
if you want to upgrade but it is usually a good idea to use the managed version of your framework.
