### ISSUE TITLE
Can't build from source archive in GitHub releases

### ISSUE THREAD

**Issue by nikhkumar** [micrometer-metrics/micrometer#2606] opened 2021-05-18 19:10 UTC
Trying to build version 1.5.9, getting below error, any lead on this?

* Where:
Build file '/Users/abc/Desktop/micrometer/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'micrometer'.
> Failed to apply plugin class 'nebula.plugin.release.ReleasePlugin'.
   > /Users/abc/Desktop/micrometer/config (Is a directory)

**Comment by shakuzen** [comment] 2021-05-19 01:52
Out of curiosity, why are you trying to build a release instead of use the release artifacts we publish to Maven Central? How exactly are you trying to build (what command)? The error seems to indicate that a plugin is trying to be applied to a directory, not a sub-project.

**Comment by nikhkumar** [comment] 2021-05-19 06:48
Hi
For building we tried below commands, all are giving same error.
./gradlew clean pTML
gradle build

Thanks

**Comment by shakuzen** [comment] 2021-05-20 10:57
I'm still wondering what is the reason to not use the published release artifacts instead of building yourself. Generally, consumers of Micrometer should not need to build specific tags.

I know it doesn't help you, but I just tried checking out the `v1.5.9` tag and ran `./gradlew check` and `./gradlew pTML -Prelease.useLastTag=true` successfully.
I'm not able to reproduce the issue you're reporting, and without understanding what you're trying to achieve, it's hard to justify spending much more effort investigating this.

**Comment by nikhkumar** [comment] 2021-05-20 15:26
For some reasons our organisation wants to build all dependencies from source.
To achieve that we took the code and trying to build a jar.

Tried again ./gradlew check and ./gradlew pTML -Prelease.useLastTag=true but still same issue.

I have uploaded the scan result also to gradle site, this might give you more details.
https://scans.gradle.com/s/3engjs6pvvchc

Thanks for the support.

**Comment by jonatan-ivanov** [comment] 2021-05-20 16:04
@nikhkumar I checked out `v1.5.9` and ran `./gradlew clean check` it worked to me too.
Is there a chance that you are using other custom things? Like a custom build of gradle, a custom build of JDK did you modify anything after checking out 1.5.9? What will you get if you run `./gradlew --version` and `git status`?

**Comment by nikhkumar** [comment] 2021-05-20 18:04
This time I cloned the project and then tried do a build and it was success.
Not sure why the build is failing on code which was downloaded as zip and then extracted.

Is there anything which I’m missing while doing build on downloaded code.

./gradlew --version
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------
Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0
Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.16 x86_64

**Comment by shakuzen** [comment] 2021-05-21 03:13
I can reproduce it when downloading the source archive from the GitHub release page. I don't know what is causing the issue. I couldn't find a difference between the git source and the archive source. Though I do think our build plugins (e.g. nebula) rely on being built in a git repository. For now, I think you'll have to build from source control instead of the archive. Initially I assumed you were checking out the `v1.5.9` release tag, so it would have been helpful in investigating to know you were building from the source archive from the GitHub release.

For already published versions, we would need to find some workaround that allows building them. Perhaps we can make a change for future versions so that it is more straightforward to build from the source archive. The recommendation for now is, however, to build from source control.

**Comment by shakuzen** [comment] 2021-05-21 03:29
Your build scan seems to confirm my suspicion that at least one of our build plugins doesn't like not being in a git repository:

```
Caused by: java.io.FileNotFoundException: /Users/nikhilkumar/Downloads/micrometer-1.5.9/config (Is a directory)
    at org.eclipse.jgit.util.IO.readFully(IO.java:141)
    ...
    at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:65)
    ...
    at io.spring.gradle.release.SpringReleasePlugin.apply(SpringReleasePlugin.groovy:43)
    ...
    at build.run(/Users/nikhilkumar/Downloads/micrometer-1.5.9/build.gradle:30)
```

It's odd though because line 30 in `build.gradle` is a blank line. `apply plugin: 'io.spring.release'` is on line 29.

**Comment by marcingrzejszczak** [comment] 2023-12-22 11:44
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-22 11:44 UTC
Labels: build
