### ISSUE TITLE
Remove reference to tags from Timer.Sample.stop javadoc

### ISSUE THREAD

**Issue by chicobento** [micrometer-metrics/micrometer#2352] opened 2020-11-18 15:22 UTC
Timer.Sample.stop javadoc seems to have leftovers from 1.5.x version:
 
> Records the duration of the operation. Using this method, any tags
> stored on the sample are NOT recorded with the timing.

**Comment by shakuzen** [comment] 2020-12-08 11:40
Duplicate of #2351

**Closed by shakuzen** 2020-12-08 11:40 UTC
