### ISSUE TITLE
TimedAspect work only with ElementType.METHOD

### ISSUE THREAD

**Issue by diablont** [micrometer-metrics/micrometer#2458] opened 2021-02-18 09:00 UTC
Target of annotation @Timed ElementType.TYPE and also in TimedAspect.java i see comment: "AspectJ aspect for intercepting types or methods annotated with @Timed.", but single aspect in code is @Around("execution (@io.micrometer.core.annotation.Timed * *.*(..))").
I may be wrong, but I think need to add @within(@io.micrometer.core.annotation.Timed)

**Comment by jonatan-ivanov** [comment] 2021-02-25 00:21
@diablont Thank you for spotting this. I agree, if the intention is to measure every method in a class annotated with `@Timed`, the current pointcut is not sufficient.

@shakuzen @jkschneider Do you remember the original intention here?
Is the `@Target` of the `Timed` annotation is wrong (btw `ANNOTATION_TYPE` is there too) or the pointcut in `TimedAspect` should be fixed?

**Comment by jonatan-ivanov** [comment] 2021-03-02 02:40
Connected to #493

**Comment by shakuzen** [comment] 2022-03-04 10:01
Duplicate of #493

**Closed by shakuzen** 2022-03-04 10:01 UTC
Labels: duplicate
