### ISSUE TITLE
Dynatrace Load average Metrics - Error 400

### ISSUE THREAD

**Issue by nandhusriram** [micrometer-metrics/micrometer#1648] opened 2019-10-17 15:42 UTC
I am using micrometer-registry-dynatrace jar version 1.3.0 with Spring Boot 2.1.9 and  I am seeing error code 400 while pushing  the load average metrics.

failed to create custom metric custom:system.load.average.1m in dynatrace: {"error":{"code":400,"message":"The timeseries id is only allowed to contain alphanumeric characters, '.', '_' and '-'. Also, it is not allowed to start with 'com.ruxit.builtin'."}}

Any ideas , may  be I am passing something wrong ?

**Comment by izeye** [comment] 2019-10-18 09:16
@nandhusriram Thanks for the report! I'm not a Dynatrace user, but I did a quick try, and I could reproduce it with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/dynatrace).

It seems to reject numeric characters in a time series ID unlike what it says in its error message. I think it'd be better to ask Dynatrace folks about it.

I wonder why this hasn't been reported earlier.

**Comment by shakuzen** [comment] 2019-10-23 06:03
@nandhusriram Thank you for reporting this, and thank you @izeye for investigating and reproducing the issue.
@nandhusriram let us know if you can reach out to Dynatrace support about this and get an official answer about the discrepancy of the error message as mentioned by @izeye.

**Comment by izeye** [comment] 2019-10-24 04:25
I got the following answer from the official Dynatrace support channel:

> A numeric character is supported, but it cannot be immediately after the dot.

I created https://github.com/micrometer-metrics/micrometer/pull/1661 to try to work around the constraints by prefixing "n" (from number). I'm not happy with it, but I couldn't find a better solution. We might be better to refrain from using leading numeric characters in meter names for Dynatrace in the future. In the PR, I also changed to sanitize meter names as it seems to be missing.

**Comment by checketts** [comment] 2019-10-24 15:07
> We might be better to refrain from using leading numeric characters in meter names for Dynatrace in the future.

Do the numbers appear after the dot because of hierarchical naming? Like `status` tag values? I don't think we can refrain in that case.

`n` isn't intuitive, I think a character like `_` is more typical as not having significance and still being widely supported.

**Comment by izeye** [comment] 2019-10-24 22:20
> > We might be better to refrain from using leading numeric characters in meter names for Dynatrace in the future.
> 
> Do the numbers appear after the dot because of hierarchical naming? Like `status` tag values? I don't think we can refrain in that case.

@checketts  No, it's due to a meter name, not a tag value. Currently, `system.load.average.1m` is the only one that has the problem.

> `n` isn't intuitive, I think a character like `_` is more typical as not having significance and still being widely supported.###

I thought the same thing, and I've already tried to prefix with all the allowed non-alphabets (`_` and `-`). However, I got the same error, so I didn't have much choice when I chose the "n".

The PR simply focused on the dot only, but it might be better to handle all the allowed non-alphabets.

**Comment by nandhusriram** [comment] 2019-10-25 02:35
Thanks  a bunch , @shakuzen  I will reach out  to Dynatrace  and check with them as well.

**Comment by shakuzen** [comment] 2019-10-28 03:18
> I thought the same thing, and I've already tried to prefix with all the allowed non-alphabets (`_` and `-`). However, I got the same error, so I didn't have much choice when I chose the "n".

I wonder if Dynatrace has any suggestion for how we should handle this. I'm also not happy with prefixing "n". I think it will confuse many users and cause increased support for this.

I thought about converting the numeric to the word (e.g. `1` to `one`), but then we would need to do something with `m` for `minute` also because `onem` is not clear, and `min` is likely to be conflated with minimum. `oneminute` is an option, I suppose.

**Comment by izeye** [comment] 2019-10-28 04:43
@shakuzen I also thought the numeric to word conversion, but with multiple numeric characters, it doesn't seem to be nice, either. For the "m" to "minute" conversion, I'm not sure if "m" would mean only "minute" generally. It might be any word starting with "m" like "meter". We might be better to rename only `system.load.average.1m` to `system.load.average.oneminute`, and let users rename their custom meter names if necessary.

**Comment by shakuzen** [comment] 2019-10-31 05:56
> We might be better to rename only `system.load.average.1m` to `system.load.average.oneminute`, and let users rename their custom meter names if necessary.

This seems like the best compromise so far. Unless there is any other feedback, I think we should move forward with this.

**Comment by izeye** [comment] 2019-10-31 11:10
@shakuzen Thanks for the feedback! I updated the PR accordingly.

**Comment by shakuzen** [comment] 2019-11-04 13:55
@nandhusriram Could you try with the latest snapshots (either 1.1.8-SNAPSHOT or 1.3.1-SNAPSHOT) to confirm things are fixed with the latest changes?

**Closed** 2019-11-04 14:08 UTC
Labels: bug, registry: dynatrace
