### ISSUE TITLE
How to exclude tag?

### ISSUE THREAD

**Issue by Lovnx** [micrometer-metrics/micrometer#2195] opened 2020-07-20 09:29 UTC
My project is based on SpringBoot2, and I use `micrometer-registry-prometheus` to expose metrics. but I found there are some tags below:
```
# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="UNKNOWN",} 15.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="UNKNOWN",} 2.839475611
http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics/prometheus",} 26.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics/prometheus",} 0.235868302
http_server_requests_seconds_count{exception="ResponseStatusException",method="GET",outcome="SERVER_ERROR",status="500",uri="UNKNOWN",} 3.0
http_server_requests_seconds_sum{exception="ResponseStatusException",method="GET",outcome="SERVER_ERROR",status="500",uri="UNKNOWN",} 15.820789013
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="UNKNOWN",} 0.0
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics/prometheus",} 0.006495912
http_server_requests_seconds_max{exception="ResponseStatusException",method="GET",outcome="SERVER_ERROR",status="500",uri="UNKNOWN",} 5.310219864
```

Actually, I dont need this tags. How to exclude them ?

**Comment by izeye** [comment] 2020-07-20 11:35
This is a duplicate of https://github.com/spring-projects/spring-boot/issues/22404 that has already been answered.

**Closed by izeye** 2020-07-20 11:35 UTC

**Comment by Lovnx** [comment] 2020-07-20 14:27
Thanks!
