### ISSUE TITLE
Clean/Remove a specific metric or metrics with specific set of labels

### ISSUE THREAD

**Issue by sskmail14** [micrometer-metrics/micrometer#2939] opened 2022-01-03 10:36 UTC
**Describe the bug**
Clean/Remove a specific metric or metrics with specific set of labels after every scrape.

**Environment**

 - Micrometer version: 1.5.1
 - Micrometer registry: prometheus
 - OS: linux
 - Java version: OpenJDK Runtime Environment (build 11.0.13+8-alpine-r0)
                           OpenJDK 64-Bit Server VM (build 11.0.13+8-alpine-r0, mixed mode)

**To Reproduce**
How to reproduce the bug:
Need to clean up a specific metrics after every scrape to `/actuator/prometheus`

**Expected behavior**

**Additional context**
Am having a gauge(custom metric) that has the information about the HTTP request with custom labels. I need to clean up this metric after every scrape from prometheus.

Kindly suggest if there is a  work around.

Thanks in advance.

**Comment by shakuzen** [comment] 2022-01-04 09:48
Could you provide more information about your use case? Removing metrics after each scrape is not a generally expected use case. Also, having more than one prometheus server scraping your application for high availability purposes is a common setup. The application (by design) doesn't have information about how many servers are scraping it. So the application wouldn't know when all servers have scraped and it is safe to remove the metric.

If the reason is because the labels are high cardinality so you want to remove metrics, this only solves the effect of high cardinality on your application's memory usage, but it will still be a problem for the Prometheus server that is storing and querying the high cardinality metrics.

**Comment by sskmail14** [comment] 2022-01-05 00:32
@shakuzen ,
My use case : I have a `Metric` of type `Gauage` which captures the some business details this is happening on the event based. So this has to be published to prometheus only once. Once this is published all the `Gauges` under that Metric name should get cleaned up since we dont need to see the redundant data in prometheus. 

#### Note:
1. Our setup supports only poll based mechanism to all our kubernetes pods(application) from prometheus pod.

**Comment by sskmail14** [comment] 2022-01-05 00:44
Providing more insights:
As an example:
If we have close to 500 gauge data generated for that metric from each of our pod.
Number of pods would be between 4 and 6.
Scrape Interval : 15sec

##### For a day:

**One Pod:**
Each minute (15sec once).  -> 500 * 4          = 2000
Each hour                              -> 2000 * 60     = 120000
Each day                                -> 120000 * 24 = 2880000

**All Pods:**
Minimum 4 pods   -> 2880000 * 4 = **11520000**
Maximum 6 pods  -> 2880000 * 6 = **17280000**

Which is a huge number. Instead it has to be just 500 * 4 = 2000 gauge data.

**Comment by checketts** [comment] 2022-01-05 16:10
@sskmail14 I agree that this usecase is likely a mis-use of Prometheus metrics. If you can add some context around what that gauge is measuring I could provide a recommendation for how it should be tracked in Prometheus.

These sorts of metrics are intended to be viewed in aggregate.

**Comment by sskmail14** [comment] 2022-01-06 08:50
@checketts ,
We have a graphql application(a custom java library), in that Metric we are sending the information about the request that's received along with the lookup name and other info as part of that metrics. Once the scrape is done we would have the data as part of the prometheus. So we need to clean that from our application. We are using spring boot 2.x.

**Comment by jonatan-ivanov** [comment] 2022-01-06 20:17
Since this seems more like business data/metric, would not be better to store the data in a persistent storage and use BI tools to process it (generate stats/dashboards)?

Also, as others mentioned above: you can have multiple Prometheus servers scraping your app and prometheus can also retry scrapes, e.g.: let's say your app get a scraping request, it removed the Gauge but Prometheus never get the response because of a network issue (e.g.: timeout) and it retries. Because of these your application should not really care about Prometheus scrapes.

Back to your original issue: I'm not sure I completely understand it.
Let's say you have 4 instances and you update a gauge with data from a request you received.
This means you will have four time-series and this number won't change unless your running instances change since the apps are updating the same gauges for every request.

If it is not the case and you will have an extra gauge/time-series for every request, removing the gauge after the scrape won't really help you: your app need to handle less gauges but Prometheus needs to handle the same amount.

If this is still not the case, could you please give us a concrete example with an example request and gauges/time-series (with tags/labels) in Prometheus?

**Comment by sskmail14** [comment] 2022-01-07 13:20
@jonatan-ivanov 
>If it is not the case and you will have an extra gauge/time-series for every request, removing the gauge after the scrape won't really help you: your app need to handle less gauges but Prometheus needs to handle the same amount.

Yes we doesn't want to send the data at each and every scrape. We just need to send what's that `till that point` from the last scrape.

>Example:
![image](https://user-images.githubusercontent.com/5357908/148549688-7674174e-190b-45af-ba0c-23f6b65e7c06.png)

Once during the first scrape we need the data to be present, once the scrape is done we want to clean up the data.

**Comment by jonatan-ivanov** [comment] 2022-01-07 19:27
>Yes we doesn't want to send the data at each and every scrape. We just need to send what's that till that point from the last scrape.

To me this seems like a mis-use of Prometheus or metrics in general (this is not how Prometheus or metric systems usually work).
On the image you attached, you have a uuid field which seems to be high cardinality data. That is an issue itself that can't be solved by deleting Meters on the client side, Prometheus still needs to hold them.

I highly recommend against this but if you really want to, you can hack this around in two ways:
1. Implementing your own custom `MeterCollector` using the Prometheus `CollectorRegistry` as @checketts mentioned above
2. Implementing your own scrape endpoint and remove meters from the `PrometheusMeterRegistry` after you called scrape on it

I'm closing this issue with this, please let us know if you want us to reopen it with a concrete example with an example request and gauges/time-series (with tags/labels) in Prometheus.

**Closed by jonatan-ivanov** 2022-01-07 19:27 UTC
Labels: bug, feedback needed

**Comment by sskmail14** [comment] 2022-01-08 06:46
@jonatan-ivanov ,
I would still say that this is a valid test case. The example with the diagram should have explained in detail. Do you need a sample project out if our test case?

Am basically looking for a in-build support on this.I fell workarounds are ok, but its dusty to have as always.

Would be great if we have the support as part of the library itself.

Would be good to re-open it.

**Comment by jonatan-ivanov** [comment] 2022-01-21 21:58
The example might be crystal clear to you since you have the full context but it is a little less clear to me. A sample project could definitely help but I think before that answering these questions would also be helpful:

1. What does the request look like, is the uuid coming from the request?
2. Is the uuid high cardinality data?
