### ISSUE TITLE
WebMvcMetricsFilter won't record async requests

### ISSUE THREAD

**Issue by leiy88** [micrometer-metrics/micrometer#1308] opened 2019-03-22 05:01 UTC
I'm using servlet3.0 asyncContext. 
AOP on Controller, then the request will asynchronous execute in a threadPool like this:
```
request.startAsync();
threadPool.execute(()->{
    ...
    runController...
    writeResponse...
    ...
})
return null;
```
However the WebMvcMetricsFilter won't filter twice for async requests.
```
                if (request.isAsyncSupported()) {
                    // this won't be "started" until after the first call to doFilter
                    if (request.isAsyncStarted()) {
                        request.setAttribute(TIMING_SAMPLE, timingContext);
                    }
                }

                if (!request.isAsyncStarted()) {
                    record(timingContext, (HttpServletResponse) response, (HttpServletRequest)request,
                            handlerObject, (Throwable) request.getAttribute(DispatcherServlet.EXCEPTION_ATTRIBUTE));
                }
```
So it won't be recorded. What should I do?

**Comment by leiy88** [comment] 2019-03-22 05:26
I guess it was because WebMvcMetricsFilter extends OncePerRequestFilter. So each request only filter once. 
But I copy the code to my own WebMvcMetricsFilter extends GenericFilterBean it still remain the same. Somebody tell me why?

**Comment by izeye** [comment] 2019-03-23 14:04
@leiy88 Thanks for the report but I couldn't reproduce it with [a sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/1.5.x). Could you provide a sample reproducing it or change my sample to reproduce it by applying your specific configuration?

**Comment by leiy88** [comment] 2019-03-25 06:18
@izeye Figure it out. asyncContext.dispatch() will trigger the second time filter invocation. I'm using asyncContext.complete(). TKS

**Comment by leiy88** [comment] 2019-03-26 03:15
@izeye Thanks for your sample. I have figured it out.
Spring DeferResult use AsyncContext.dispatch() for the first phase while the async request was not compeleted.  I did the same thing and the problem have been sloved. TKS

**Comment by shakuzen** [comment] 2019-03-26 03:57
Closing as it sounds like the issue is resolved now.

**Closed by shakuzen** 2019-03-26 03:57 UTC
