### ISSUE TITLE
@Timed annotation on classes

### ISSUE THREAD

**Issue by sabouri** [micrometer-metrics/micrometer#1278] opened 2019-03-12 12:24 UTC
The @Timed annotation's target includes ElementType.TYPE, but when a class is annotated with @Timed, no new metrics are registered.

Is the @Timed annotation supposed to support classes?

**Comment by sabouri** [comment] 2019-03-12 12:32
Please see:
https://github.com/micrometer-metrics/micrometer/pull/1279

**Comment by plum117** [comment] 2020-09-22 17:38
Hi, can we expect a fix?

**Comment by mukeshjitsingh** [comment] 2021-09-08 07:47
Has there been any updates on this? Any other alternative to have all the methods timed by annotating the class?

**Comment by shakuzen** [comment] 2022-03-04 09:59
Duplicate of #493

**Closed by shakuzen** 2022-03-04 09:59 UTC
