### ISSUE TITLE
TimeWindowFixedBoundaryHistogram doesn't work with double buckets correctly

### ISSUE THREAD

**Issue by gebhardt** [micrometer-metrics/micrometer#2592] opened 2021-05-07 09:50 UTC
If your `DistributionSummary` has service level objective (SLO) boundaries smaller to 1 (e.g. 0.1, 0.2, 0.3) the buckets are not correctly determined in the `TimeWindowFixedBoundaryHistogram` class.

The `TimeWindowFixedBoundaryHistogram.recordDouble(FixedBoundaryHistogram bucket, double value)` method calls the `recordLong(..)` method and rounds the value to the next long value. This makes all buckets with boundaries smaller to 1 useless...

Instead the `FixedBoundaryHistogram` class should provide a `void record(double value)` method to determine the correct buckets.

**Comment by shakuzen** [comment] 2021-05-10 07:04
Duplicate of #2341. For now, the way this is supported is with scaling, as explained in the documentation: see the section Distribution summaries → [Scaling and histograms](https://micrometer.io/docs/concepts#_scaling_and_histograms). Does scaling work for your use case? We could consider your proposal, but the issue of it being out of the range of our predetermined buckets for percentile histograms remains.

**Comment by gebhardt** [comment] 2021-05-10 07:23
I could use scaling and it is working correctly. However the disadvantage of this approach is that the data is no longer exposed in seconds but in milliseconds. And according to Prometheus' best practice you should use seconds as base unit: https://prometheus.io/docs/practices/naming/#base-units

**Comment by marcingrzejszczak** [comment] 2023-12-20 12:38
At this point we're suggesting to go with scaling as @shakuzen shown. If you're not happy with this solution please comment on this issue and we'll consider re-opening the issue.

**Closed by marcingrzejszczak** 2023-12-20 12:38 UTC
Labels: waiting for feedback

**Comment by Grryum** [comment] 2024-06-28 10:57
Hello! I would like to re-open this issue as I have encountered the same problem. In certain eco-systems (for example Prometheus) there is no separate metric type for measuring durations, like a Timer. As a result, durations and other values need to be observed using Histograms. However, this presents a challenge when trying to use Micrometer as a common interface for integration with such systems.

I am a contributor to the ZIO ecosystem in Scala and have developed an integration with ZIO native metrics using [Micrometer](https://github.com/zio/zio-metrics-connectors/pull/42).

At a low-level, ZIO operates only with Histograms (like Prometheus), so I had to use DistributionSummary. However, I am now facing a problem where metrics are collected incorrectly when I try to observe durations and set up the buckets with values between 0 and 1 second. I can not use `scale` because I need bucket values be in original scale (seconds).

It would be nice if DistributionSummary can record Double values (not Long).

**Comment by jonatan-ivanov** [comment] 2024-06-28 21:34
> I would like to re-open this issue as I have encountered the same problem.

Thanks for reporting your issue but after reading it through, I feel you have a different problem. If not please let me know what I misunderstood.

>for example Prometheus there is no separate metric type for measuring durations, like a Timer

It's not clear if you mean the Prometheus Server, where you don't measure anything, or the Prometheus Java Client, that has [`TimerApi`](https://prometheus.github.io/client_java/api/io/prometheus/metrics/core/datapoints/TimerApi.html) to do the measurements.

>As a result, durations and other values need to be observed using Histograms.

Not sure what you mean by other values but `Summary` can also be used (though you will have significantly less data about the measurement).

>At a low-level, ZIO operates only with Histograms (like Prometheus), so I had to use DistributionSummary.

Please do not use `DistributionSummary` for measuring/reporting elapsed time, Micrometer has a `Timer`: https://docs.micrometer.io/micrometer/reference/concepts/timers.html, I guess that would also eliminate the issue you are facing with since with the `Timer`, the time unit for recording and for reporting are decoupled, please feel free to record whatever time unit you want, by default publishing will use seconds:
```
void record(long amount, TimeUnit unit);
void record(Duration duration);
```

If this does not solve your issue, please open a new one with a few lines of minimal sample code that shows what you are trying to do.

**Comment by Grryum** [comment] 2024-07-01 16:38
thank you for your response.
It seems that we may have misunderstood each other.
I am not writing the final client code for gathering metrics; I am developing a library that implements a common interface for interacting with Prometheus metrics types through the Micrometer interface. Conceptually, Prometheus does not have a specific metric type (class implementing StatefulMetric and DistributionDataPoint) like Timer (all available metric types are described here https://prometheus.io/docs/concepts/metric_types/).
Despite the presence of the TimerApi you mentioned, ultimately, Histogram is still used as the metric type. Therefore, in my connector, I receive Histogram data for both timing and other arbitrary data.
Then I need to pass this data to Micrometer interface. However, when using the Micrometer interface, I need to know exactly which data is being observed through the Histogram in order to use either DistributionSummary or Timer. Unfortunately, I do not have this information in this context.

I tried to use DistributionSummary as a common case for incoming Histogram data, but faced with problem for observing data between 0 and 1 boundries which I tried to described above.

**Comment by Grryum** [comment] 2024-07-01 16:38
> > I would like to re-open this issue as I have encountered the same problem.
> 
> Thanks for reporting your issue but after reading it through, I feel you have a different problem, if you think otherwise after reading through this comment, please let me know.
> 
> > for example Prometheus there is no separate metric type for measuring durations, like a Timer
> 
> It's not clear if you mean the Prometheus Server, where you don't measure anything, or the Prometheus Java Client, that has [`TimerApi`](https://prometheus.github.io/client_java/api/io/prometheus/metrics/core/datapoints/TimerApi.html) to do the measurements.
> 
> > As a result, durations and other values need to be observed using Histograms.
> 
> Not sure what you mean by other values but `Summary` can also be used (though you will have significantly less data about the measurement).
> 
> > At a low-level, ZIO operates only with Histograms (like Prometheus), so I had to use DistributionSummary.
> 
> Please do not use `DistributionSummary` for measuring/reporting elapsed time, Micrometer has a `Timer`: https://docs.micrometer.io/micrometer/reference/concepts/timers.html, I guess that would also eliminate the issue you are facing with since with the `Timer`, the time unit for recording and for publishing are decoupled, please feel free to record whatever time unit you want, by default publishing will use seconds:
> 
> ```
> void record(long amount, TimeUnit unit);
> void record(Duration duration);
> ```
> 
> If this does not solve your issue, please open a new one with a few lines of minimal sample code that shows what you are trying to do.
> 
> Oh also, since it seems you are measuring duration on your own, you might want to read this: https://develotters.com/posts/how-not-to-measure-elapsed-time/ and use `Timer.Sample` to do the measurements instead of doing it manually.

thank you for your response.
It seems that we may have misunderstood each other.
I am not writing the final client code for gathering metrics; I am developing a library that implements a common interface for interacting with Prometheus metrics types through the Micrometer interface. Conceptually, Prometheus does not have a specific metric type (class implementing StatefulMetric and DistributionDataPoint) like Timer (all available metric types are described here https://prometheus.io/docs/concepts/metric_types/).
Despite the presence of the TimerApi you mentioned, ultimately, Histogram is still used as the metric type. Therefore, in my connector, I receive Histogram data for both timing and other arbitrary data.
Then I need to pass this data to Micrometer interface. However, when using the Micrometer interface, I need to know exactly which data is being observed through the Histogram in order to use either DistributionSummary or Timer. Unfortunately, I do not have this information in this context.

I tried to use DistributionSummary as a common case for incoming Histogram data, but faced with problem for observing data between 0 and 1 boundries which I tried to described above.

**Comment by jonatan-ivanov** [comment] 2024-07-01 22:38
>It seems that we may have misunderstood each other.
I am not writing the final client code for gathering metrics; I am developing a library that implements a common interface for interacting with Prometheus metrics types through the Micrometer interface.

Could you please open a new issue where you provide a **minimal** sample project to reproduce your issue? From this it seems you are reimplementing the `PrometheusMeterRegistry` which I don't understand why (or why scaling the `DistributionSummary` or using a `Timer` would not work) so could you please show us some code about what you are trying to do?

>Conceptually, Prometheus does not have a specific metric type (class implementing StatefulMetric and DistributionDataPoint) like Timer (all available metric types are described here https://prometheus.io/docs/concepts/metric_types/).

You might misunderstood me, I'm familiar with those types but when you say Prometheus I have no idea if you mean the server or the client. :)

>Despite the presence of the TimerApi you mentioned, ultimately, Histogram is still used as the metric type. Therefore, in my connector, I receive Histogram data for both timing and other arbitrary data.
Then I need to pass this data to Micrometer interface. However, when using the Micrometer interface, I need to know exactly which data is being observed through the Histogram in order to use either DistributionSummary or Timer. Unfortunately, I do not have this information in this context.

I need to admit, I'm lost. Above you wrote that
>common interface for interacting with Prometheus metrics types through the Micrometer interface.

Which tells me that you want to bridge Micrometer API calls to Prometheus (client?) but from this section it seems you are creating a bridge from Prometheus types (API?) to the Micrometer API? :o Which one and why do you need to do this? If the latter, can you check the unit used for the Prometheus `Histogram` and use a `Timer` if it is a time unit and use `DistributionSummary` otherwise?
Please open a new issue and show us the code in a **minimal** sample.

>I tried to use DistributionSummary as a common case for incoming Histogram data, but encountered a problem for observing data between 0 and 1 boundries which I tried to described above.

In these cases either scaling (if it is not a duration) or a `Timer` (if it is a duration) should be used.
