### ISSUE TITLE
New Kafka Metrics duplicate metrics

### ISSUE THREAD

**Issue by tchiotludo** [micrometer-metrics/micrometer#2095] opened 2020-05-14 11:11 UTC
With the last kafka metrics on `implementation "io.micrometer:micrometer-core:1.4.2"`, I've just got a new error that crash my application : 
```
2020-05-14 08:23:11,061 ERROR akfa-queue-1 tionHandlers Caught an exception in Thread[kakfa-queue-1,5,main]. Shutting down.
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'kafka_consumer_fetch_manager_bytes_consumed_total' containing tag keys [client_id, kafka_version, topic]. The meter you are attempting to register has keys [client_id, kafka_version].
```

<details><summary>stack trace</summary><p>

	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:382)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:369)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newFunctionCounter(PrometheusMeterRegistry.java:280)
	at io.micrometer.core.instrument.MeterRegistry$More.lambda$counter$1(MeterRegistry.java:866)
	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:541)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:594)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:548)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:541)
	at io.micrometer.core.instrument.MeterRegistry.access$500(MeterRegistry.java:76)
	at io.micrometer.core.instrument.MeterRegistry$More.counter(MeterRegistry.java:866)
	at io.micrometer.core.instrument.FunctionCounter$Builder.register(FunctionCounter.java:122)
	at io.micrometer.core.instrument.composite.CompositeFunctionCounter.registerNewMeter(CompositeFunctionCounter.java:58)
	at io.micrometer.core.instrument.composite.CompositeFunctionCounter.registerNewMeter(CompositeFunctionCounter.java:26)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:604)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:548)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:541)
	at io.micrometer.core.instrument.MeterRegistry.access$500(MeterRegistry.java:76)
	at io.micrometer.core.instrument.MeterRegistry$More.counter(MeterRegistry.java:866)
	at io.micrometer.core.instrument.FunctionCounter$Builder.register(FunctionCounter.java:122)
	at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.registerCounter(KafkaMetrics.java:190)
	at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.bindMeter(KafkaMetrics.java:175)
	at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.lambda$checkAndBindMetrics$1(KafkaMetrics.java:161)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.checkAndBindMetrics(KafkaMetrics.java:137)
	at io.micrometer.core.instrument.binder.kafka.KafkaMetrics.bindTo(KafkaMetrics.java:93)
	at io.micrometer.core.instrument.binder.kafka.KafkaClientMetrics.bindTo(KafkaClientMetrics.java:39)
	at org.kestra.core.metrics.MetricRegistry.bind(MetricRegistry.java:173)
	at org.kestra.runner.kafka.services.KafkaConsumerService$Consumer.<init>(KafkaConsumerService.java:63)
	at org.kestra.runner.kafka.services.KafkaConsumerService.of(KafkaConsumerService.java:52)
	at org.kestra.runner.kafka.KafkaQueue.lambda$receive$3(KafkaQueue.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

</p></details>

Since the environnement is in production, I can't have any more information (previous internal state, ...). 

To have some context, my application is multithreaded application with multiple Kafka Consumer.
I suspect that if there is some consumer in different state, the Kafka metrics don't return the topic on init (before the subscribe) and this will failed if a previous consumer was already registered after the subscribe. 
To be honest, I don't have internal knowledge of micrometer how to handle this case properly, but without any change, the Metrics will crash my application, that is not really expected. 

any clue @shakuzen & @jeqo ?

**Comment by jeqo** [comment] 2020-05-14 13:06
This is caused here: https://github.com/micrometer-metrics/micrometer/blob/a6fefc903002e6d426fc8506d56b2f8a108eafad/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L415-L418

There is an [existing effort](https://github.com/micrometer-metrics/micrometer/blob/00c2771419a6fce29d9285136b9a1e9ab00582a8/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/kafka/KafkaMetrics.java#L163-L189) on Kafka binders to avoid this. In the case of this happening, even on 1 pull iteration, it should not lead to crashing the application as it is today IMO--agree with @tchiotludo. At most a `WARN` message should be logged. 

PS: Searching Prometheus codebase, I haven't been able to found this constraint specified so far. Even though this scenario (same name, diff tags) is not desired--as it could be mean redundant metrics--, it should not be enforced as it is today.

**Comment by kgunnerud** [comment] 2020-06-08 06:38
We experienced this as well: https://stackoverflow.com/questions/62210222/micrometer-throws-exception-when-creating-a-second-kafka-consumer/62255997#62255997
I'll link from StackOverflow to here so that the issue can be discussed here.

**Comment by izeye** [comment] 2020-06-08 14:42
With the current implementation, a different client seems to be possible to have the same meter name but a different set of tag keys.

Including the client ID in meter names could resolve this although it doesn't seem to be nice.

I'm not sure if there's any better way at the moment, but I created https://github.com/micrometer-metrics/micrometer/pull/2143 to try to resolve this.

**Comment by izeye** [comment] 2020-06-08 15:03
For the record, `kafka_consumer_fetch_manager_bytes_consumed_total` doesn't have "topic" tag at the first registration but has "topic" tag somehow when refreshing. So any subsequently created client will fail with the above exception for the meter due to tag key set mismatch.

**Comment by izeye** [comment] 2020-06-08 16:06
> So any subsequently created client will fail with the above exception for the meter due to tag key set mismatch.

After further investigation, this should be resolved in the next refresh, but it doesn't work as the exception stops the refresh logic.

I created https://github.com/micrometer-metrics/micrometer/pull/2144 as alternative solution to #2143 as it seems to be much better if a subsequent retry just resolves it. I'm not sure if it is enough, but at least I confirmed that the scenario I mentioned above has been resolved with the fix.

**Comment by tchiotludo** [comment] 2020-06-08 16:30
Seems to be a good hack waiting a clarification on prometheus exception. 
Maybe I would change the exception here : 
https://github.com/micrometer-metrics/micrometer/blob/a6fefc903002e6d426fc8506d56b2f8a108eafad/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L415-L418
to a Proper `DuplicateMeterException` to avoid parsing string message ?

**Comment by izeye** [comment] 2020-06-09 00:15
@tchiotludo Thanks for the feedback!

I know it's brittle, but I couldn't find a better way to distinguish the Prometheus-specific exception in the core module.

**Closed** 2020-06-23 14:10 UTC
Labels: bug

**Comment by ventsislav-penev** [comment] 2020-10-22 10:53
@shakuzen @izeye 
I am using SpringBoot 2.3.4.RELEASE with micrometer 1.5.5 and also getting such info logs - "Failed to bind meter...." , (which are the result of handling the IllegalArgumentException inside PrometheusMeterRegistry class, caused by "..meters with the same name have the same set of tag keys.."), when I have more than one kafka consumer/listener in the application.
At the end, it seems that meters are correct, after the refreshing, but is there any way to get rid of these logs?

**Comment by shakuzen** [comment] 2020-10-28 09:20
> Is this intended and is there any way to avoid or get rid of these logs?

We probably underestimated how much this could typically happen and were too verbose with the logging. You can configure your logging to only log at warn level or higher for the `KafkaMetrics` class as a way to silence that log. I've made a proposal to substantially decrease the amount of logging most should see for this for the upcoming 1.5.6 release: https://github.com/micrometer-metrics/micrometer/pull/2311
