### ISSUE TITLE
serviceLevelObjectiveBoundaries doesn't allow to record bucket with zero value

### ISSUE THREAD

**Issue by RestfulBlue** [micrometer-metrics/micrometer#3944] opened 2023-06-28 21:35 UTC
Hello! I am trying to migrate monitoring in application to micrometer, but found out that serviceLevelObjectives in histogram does not allow to create bucket with zero value (DistributionStatisticConfig performs check for that. 

It seems like having zero-value bucket is completely legit in histogram. For example, when we try to calculate distribution of size ( which is always int/long), we have buckets of 0, 1, 2 .. 10. After that from prometheus side we could group it and show distribution ( which is very handy)

is this restriction of zero buckets done on purpose? if so, how application should instrument such places?

**Comment by shakuzen** [comment] 2023-07-06 04:04
Duplicate of #2550

**Closed by shakuzen** 2023-07-06 04:04 UTC
Labels: waiting-for-triage
