### ISSUE TITLE
A bare-bones module for inclusion in bootstrap classloader to be used by javaagent instrumentation

### ISSUE THREAD

**Issue by william-tran** [micrometer-metrics/micrometer#2137] opened 2020-06-03 22:03 UTC
I want to use Micrometer to define metrics in java-agent instrumentation rules, so I can write my own [specialagent rules](https://github.com/william-tran/specialagent-rules) that add metrics as well as tracing behaviour to other classes.  This forces me to load micrometer-core into the bootstrap classloader, but this causes strange issues in the app classloader, eg on spring boot startup:

```
java.lang.NoClassDefFoundError: ch/qos/logback/classic/LoggerContext
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindConstructorProvider.findConstructorBindingAnnotatedConstructor(ConfigurationPropertiesBindConstructorProvider.java:62)
```

There seem to be a lot of dependencies both optional and hard to micrometer-core. I like prometheus's simpleclient approach, which has no dependencies and very few classes: https://github.com/prometheus/client_java/blob/master/simpleclient/pom.xml#L38-L40

I'd like a module that gives me the bare minimum needed to register metrics to the `Metrics.globalRegistry`

**Comment by checketts** [comment] 2020-06-03 22:29
Since the `globalRegistry` is largely a facade in front of another registry what would your ideal usecase be for that registry? A `SimpleMeterRegistry` perhaps that can be self sufficient? Or would it also need to forward on to a Prometheus one?

I'm not too familiar with the classpath issues/javaagent stuff at work, but it sounds like you are proposing a module that has fewer features so it can be used in this special case.

Could you invert the dependency so your own code just collected values and stored them as static globals that application code could hook into via a binder?

**Comment by jkschneider** [comment] 2020-06-04 18:09
@william-tran I don't imagine the optional dependencies have any impact right? I mean, if you expect to be able to bind OkHttp metrics without including an optional OkHttp dependency on the runtime classpath it obviously isn't going to work, and no wishfulness about dependency hygiene changes that.

`micrometer-core` is actually quite thin as far as dependencies go, only requiring HdrHistogram and LatencyUtils which in turn have no dependencies.

Logback is probably coming in with a particular registry implementation. And this is where things get tricky. I don't think you get to have your cake and eat it too... if you want a registry implementation, you get its dependency requirements... Some registries will be thinner than others. The prometheus registry for example only has these:

![image](https://user-images.githubusercontent.com/1697736/83795062-882fdd00-a664-11ea-86d2-e5acf8c48f2b.png)

**Comment by jkschneider** [comment] 2020-06-04 18:11
It would probably be really helpful to see what you are trying to do in code. I don't undersatnd how Spring is in the stacktrace. That certainly isn't because of a dependency of `micrometer-core`.

**Comment by jkschneider** [comment] 2020-06-04 19:42
Closing because I don't see how `micrometer-core` gets any thinner. HdrHistogram and LatencyUtils are clearly not the problem, and it has no other required dependencies.

Optional dependencies are a red herring.

The problem is that the OP somehow is bringing Spring onto the classpath without _its_ dependencies, which has nothing to do with Micrometer.

**Closed by jkschneider** 2020-06-04 19:42 UTC
