### ISSUE TITLE
Add option to change time unit for a Timer metric

### ISSUE THREAD

**Issue by generalpsycha** [micrometer-metrics/micrometer#4405] opened 2023-11-24 07:46 UTC
All timer metrics are measured in seconds. Example metric:
latency_seconds{quantile="0.0",} 0.0

Seconds is very long in IT systems - smaller time units are more reasonable for such measurements. While it is possible to manually recalculate the result to milliseconds, it reduces clarity of queries. This can also be confusing, if another approach is taken, and such metric is recalculated to milliseconds, and displayed as "_seconds" metrics list.

**Comment by lenin-jaganathan** [comment] 2023-11-25 08:32
More so a duplicate of https://github.com/micrometer-metrics/micrometer/issues/4322.

Specifically [see this response](https://github.com/micrometer-metrics/micrometer/issues/4322#issuecomment-1802734465) from @jonatan-ivanov .

**Comment by jonatan-ivanov** [comment] 2023-11-26 07:42
Duplicate of https://github.com/micrometer-metrics/micrometer/issues/4322

**Closed by jonatan-ivanov** 2023-11-26 07:42 UTC
Labels: waiting-for-triage
