### ISSUE TITLE
TimedAspect creates duplicates the metrics when spring already register it

### ISSUE THREAD

**Issue by AnakinPt** [micrometer-metrics/micrometer#2524] opened 2021-03-23 14:24 UTC
I have a class that is a `@RestController` and I have methods with `@PostMapping` and `@Timed`

Ex:
 

```
     @PostMapping
     @ResponseStatus(HttpStatus.ACCEPTED)
     @Timed(value="processFullUpdate", extraTags = {"version", "V4"})
     public void processFullUpdate(@Valid @RequestBody FullUpdateRequestV4 fullUpdateRequestV4){
        // do some stuff
 }
```

If I register the `TimedAspect` as a bean, Spring will register a metric with name processFullUpdate and then the aspect will try to register again, but now with different tags. This causes the application to crash because prometheus requires the same metric to have always the same tag list.

Expected behavior, in these cases, the aspect should not register a metric (ex: methods annotated with the annotations that already register metrics, like the *Mapping)

**Comment by shakuzen** [comment] 2021-03-24 08:12
On the latest versions (Spring Boot 2.4.4, Micrometer 1.6.5) an exception is no longer thrown due to the changes in #2068, which don't log the exception by default, but the first registered wins behavior is still there. I don't know if the meter that will be registered first is deterministic or not. Nonetheless, this sounds like a duplicate of https://github.com/spring-projects/spring-boot/issues/15184. Why are you registering the `TimedAspect` instead of using the Boot-provided support which will customize the controller methods' timer with the `@Timed` annotation without registering the `TimedAspect`?

**Comment by shakuzen** [comment] 2021-03-24 08:24
Duplicate of #780

**Closed by shakuzen** 2021-03-24 08:24 UTC
Labels: for: external-project

**Comment by AnakinPt** [comment] 2021-03-25 09:25
@shakuzen Yes, it's the same problem as the #780. And answering to your question, we need to use the TimedAspect to have metrics in any method. For now, we're going to use the workaround provided by kwtan.
