### ISSUE TITLE
Infinite loop in a shaded class when using DEBUG log level

### ISSUE THREAD

**Issue by tyleroconnell** [micrometer-metrics/micrometer#2369] opened 2020-12-02 21:25 UTC
My team added micrometer into our application and subsequently found that some environments were unable to come up and reach a steady state. After further investigation, we realized that the environments that were experiencing issues had their log4j logging level set to `DEBUG`. More specifically, _io.micrometer.shaded.io.netty.util.Recycler_ was causing an infinite loop from the bitwise left shift of `this.elements.length` by 1.

The key to replicating our issue is using log4j2, micrometer with statsd, creating two MeterRegistry beans, and running in debug. When two registry beans exist, there is a composite meter registry bean created as well. The infinite loop scenario only occurs when all of these criteria are met, which is likely why this issue may have gone unnoticed.

Since our project is on an enterprise instance of GitHub (and therefore unable to be shared publicly), we've replicated the issue in a [sample repo](https://github.com/tyleroconnell/micrometer-bug-example) that goes into more detail on the above. Given the culprit is a shaded class, I'm not sure if this GitHub issue would be better suited for [netty/netty](https://github.com/netty/netty) but I thought I'd start here.

We have found a better workaround than explicitly setting the logging level for that shaded class, in that we can use the [default Spring Boot wiring](https://github.com/tyleroconnell/micrometer-bug-example/blob/main/src/main/java/com/example/demo/config/App2Config.java) for _StatsdMeterRegistry_ but wanted to raise this in the hopes of honing in on a fix, or at least documenting this for others.

**Comment by shakuzen** [comment] 2020-12-03 09:05
Thank you for the detailed report/investigation and sample project. Maybe this is just a typo in the command in the README - I was only able to reproduce the issue with the Spring Boot auto-config enabled for the StatsdMeterRegistry (`-Dmanagement.metrics.export.statsd.enabled=true`).

As for the workaround, it is best practice to not instantiate the meter registry yourself in a Spring Boot application unless you need to for some reason. If you are using the standard `StatsdMeterRegistry`, there should not be a need to do so. If you want to provide a custom `StatsdConfig` different from what Spring Boot would provide, you can define a bean of type `StatsdConfig` and Spring Boot auto-configuration will use that. If you were going to make your own `StatsdMeterRegistry` bean, you should declare the type as `StatsdMeterRegistry` instead of the more generic `MeterRegistry` so the auto-config knows to back off on making a `StatsdMeterRegistry`, if that was the intention.

Could you clarify what the intention is? Do you want to configure two different statsd registries in the same application? I could not reproduce the issue with a `PrometheusMeterRegistry` and a `StatsdMeterRegistry`, so it seems to be an issue with two `StatsdMeterRegistry` and the `Log4j2Metrics` binder.

**Comment by izeye** [comment] 2020-12-03 14:48
I created https://github.com/netty/netty/pull/10836 to try to resolve the Netty part of the issue.

**Comment by shakuzen** [comment] 2021-01-08 08:30
Closing as the underlying issue has been fixed in Netty and we are tracking upgrade in #2374

**Closed by shakuzen** 2021-01-08 08:30 UTC
Labels: for: external-project, registry: statsd

**Comment by shakuzen** [comment] 2021-01-12 12:52
We have upgraded the version of netty to one including the fix submitted by @izeye. The change will be included in the upcoming releases 1.5.10 and 1.6.3.
