### ISSUE TITLE
Flooded with "Could not serialize meter XXX: Value was NaN" with Dynatrace plugin

### ISSUE THREAD

**Issue by szpak** [micrometer-metrics/micrometer#3560] opened 2022-12-08 17:30 UTC
**Describe the bug**
Dynatrace exporter prints a lot of WARNs with `Could not serialize meter kafka.xxx: Value was NaN` meters.

**Environment**

I added micrometer-registry-dynatrace to my Spring Boot application to have the additional metrics exported to Dynatrace.

The pod is instrumented by the OneAgent and the exporter is able to detect that:

```
13:03:03.317  INFO 1 --- [           main] i.m.dynatrace.DynatraceMeterRegistry     : Exporting to Dynatrace metrics API v2
13:03:03.321  INFO 1 --- [           main] i.m.dynatrace.v2.DynatraceExporterV2     : Exporting to endpoint https://xxx.yyy/zzz/www/api/v2/metrics/ingest
13:03:03.385  INFO 1 --- [           main] i.m.c.instrument.push.PushMeterRegistry  : publishing metrics for DynatraceMeterRegistry every 1m
```

However, later on, after the Kafka consumer initialization, I see:

```
13:04:00.034  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.partition.lost.latency.max: Value was NaN.
13:04:00.036  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.partition.lost.latency.avg: Value was NaN.
13:04:00.049  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.reauthentication.latency.avg: Value was NaN.
13:04:00.049  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.reauthentication.latency.max: Value was NaN.
13:04:00.078  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.partition.lost.latency.max: Value was NaN.
13:04:00.081  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.partition.lost.latency.avg: Value was NaN.
13:04:00.099  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.commit.latency.avg: Value was NaN.
13:04:00.101  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.reauthentication.latency.max: Value was NaN.
13:04:00.105  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.coordinator.commit.latency.max: Value was NaN.
13:04:00.106  WARN 1 --- [trics-publisher] i.m.dynatrace.v2.DynatraceExporterV2     : Could not serialize meter kafka.consumer.reauthentication.latency.max: Value was NaN.
```

After a while I see a lot of that kind of message repeated (all Kafka-related).

I use Spring Boot 2.7.3 with Micrometer 1.10.2 running JDK 17 on Kubernetes. The pod is instrumented by the OneAgent (and it seems to work fine in general as the generic metrics from JVM are gathered). The problem is similar to https://github.com/micrometer-metrics/micrometer/issues/1343, but it was fixed years ago. Do you have an idea why it is problematic with those Kafka meters?

**To Reproduce**
See above description.

**Expected behavior**
The metrics are exported to Dynatrace without any errors

**Additional context**
Related issue: https://github.com/micrometer-metrics/micrometer/issues/1343

**Comment by jonatan-ivanov** [comment] 2022-12-09 02:30
@szpak see this: https://github.com/micrometer-metrics/micrometer/pull/3557
Though this might just hide the issue. Are those Kafka consumers not used anymore and they should report `NaN` in your use-case or they should not?

**Comment by szpak** [comment] 2022-12-09 08:09
It might. In the meantime, I added a MeterFilter to remove the problematic `kafka.consumer` metrics. However, it wonder, if this could be effectively fixed on the spring-kafka side?

**Comment by shakuzen** [comment] 2023-01-16 07:45
The log messages should be at DEBUG level now in the latest versions with https://github.com/micrometer-metrics/micrometer/pull/3557. As for the underlying cause, I wonder if new Kafka clients are being started, while old Kafka clients are being removed but the meters are still registered for those old Kafka clients. Are you able to reliably reproduce this locally? Could you provider a sample with steps for us to reproduce it?

**Comment by shakuzen** [comment] 2023-01-26 09:24
Closing for now. We can reopen or investigate in a new issue if we have a reproducer and instructions.

**Closed by shakuzen** 2023-01-26 09:24 UTC
Labels: feedback needed

**Comment by szpak** [comment] 2023-01-26 21:12
I missed the original question :-/

> As for the underlying cause, I wonder if new Kafka clients are being started, while old Kafka clients are being removed but the meters are still registered for those old Kafka clients. Are you able to reliably reproduce this locally?

As it happens only with the DynaTrace OneAgent deployed on the Kubernetes cluster, it's somehow problematic for me to produce locally. It was a new application (Spring Boot µservice) redeployed, so there could be an old instance of that service (in an another pod) available. However, I believe, the errors were flooded long after the application start.

Anyway, if you don't have a good idea why it happens, closing the issue, waiting for some reproducer (probably from someone else) seems a practical approach.

Btw, I don't observe similar problems with the Prometheus registry attached. Maybe it handles potential NaN in some other way (or just ignores them ;) ).

**Comment by shakuzen** [comment] 2023-01-27 02:50
Thank you for the additional details. We'll keep an eye out for reports of similar issues and see if we can figure out the cause eventually.

**Comment by pirgeo** [comment] 2023-02-03 07:07
I must have missed this one too - I think the flood was coming from weak-referenced Gauge metrics. Once the backing field for the Gauge is garbage collected, the return value defaults to NaN. Before we realized that, our thinking was that if you indeed export a NaN by accident, you probably want to know about it - that's why we log it. However, since the Gauge is never automatically cleaned up independent of whether or not the backing field is still available, it will log lots of NaNs (i. e., every time it tries to export, for every gauge). We addressed this in https://github.com/micrometer-metrics/micrometer/pull/3557 by only logging the first occurrence at `WARN`, and everything else at `DEBUG`, so starting from `v1.9.7` you should see 1 warning at most. IMO, The weak reference is the most probable cause for this log spam - if you find some other reason for it please let me know!

To fix this for good, it would be required to unregister the gauge from the MeterRegistry once it is no longer used. Unfortunately, there is no way of automating this on the Registry side, as far as I am aware.
