### ISSUE TITLE
WebMvcMetricsFilter is setting the 500 error when rethrowing

### ISSUE THREAD

**Issue by somayaj** [micrometer-metrics/micrometer#2314] opened 2020-10-28 22:27 UTC
figures the WebMvcMetricsFilter is setting the 500 error on ln: 104
catch (NestedServletException ex) {
response.setStatus(HttpStatus.INTERNAL_SERVER_ERROR.value());
record(timingContext, request, response, ex.getCause());
throw ex;

Assume this fix is meant to be on the spring boot repo but thought it might be here where a resolution may be found. 

PS: Willing to submit a PR for this change if agreed on.

**Comment by shakuzen** [comment] 2020-10-29 02:17
I'm not sure I understand the issue being reported, but it sounds like perhaps it is a duplicate of https://github.com/spring-projects/spring-boot/issues/13300. @somayaj let me know if you're reporting something different than that.

**Closed by shakuzen** 2020-10-29 02:17 UTC
Labels: duplicate, for: external-project
