### ISSUE TITLE
failed to send metric metadata when using application key

### ISSUE THREAD

**Issue by srinivasvsk** [micrometer-metrics/micrometer#415] opened 2018-02-12 01:10 UTC
Hi,
Im seeing these errors in log frequently when i configure application key,  the metrics are making it datadog but not sure what these metadata errors related to json are. If i skip the applicationkey, the errors dont appear.

```2018-02-05 11:13:57.846 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11:14:00.826 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11:14:01.765  INFO 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : successfully sent 49 metrics to datadog
2018-02-05 11:14:01.909 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11:14:02.022 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11:14:02.121  INFO 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : successfully sent 49 metrics to datadog
2018-02-05 11:14:02.296 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11:14:02.362 ERROR 59125 --- [pool-7-thread-1] i.m.datadog.DatadogMeterRegistry         : failed to send metric metadata: {"errors": ["request data must be valid JSON"]}
2018-02-05 11```

**Comment by checketts** [comment] 2018-02-12 03:01
I believe this is a dupe of #396

**Comment by jkschneider** [comment] 2018-02-12 04:39
Agreed, @checketts. This is fixed on the latest snapshot.

**Closed by jkschneider** 2018-02-12 04:39 UTC

**Comment by jkschneider** [comment] 2018-02-22 20:36
@n0mer This [sample ](https://github.com/micrometer-metrics/micrometer-samples-boot2-datadog/blob/master/src/main/resources/application.yml) works for me without failure. Can you spot any differences in your setup? Are you sure you have 1.0.0 for all micrometer deps in your classpath?

To be clear, the application key is different from the API key:

![image](https://user-images.githubusercontent.com/1697736/36562821-bd307388-17dd-11e8-8dbc-ccf22e6eac1e.png)

**Comment by n0mer** [comment] 2018-02-23 11:14
@jkschneider this is definitely side-effect.

So, i caught this error in breakpoint, metric name is `org.springframework.integration.config.ServiceActivatorFactoryBean#0.timer.avg`

Code that constructs connection:

```java
            con = (HttpURLConnection) URI.create(config.uri() + "/api/v1/metrics/" + metricName
                    + "?api_key=" + config.apiKey() + "&application_key=" + config.applicationKey()).toURL().openConnection();

```

uri = `https://app.datadoghq.com`; apiKey and applicationKey are set.

So, i think that this is something with url-encoding of tricky characters from metricName. Maybe `metricName` needs to be base64 or URL-encoded

**Comment by n0mer** [comment] 2018-02-23 11:16
same for `org.springframework.integration.config.ServiceActivatorFactoryBean#0.timer.count`

**Comment by n0mer** [comment] 2018-02-23 12:02
`MeterFilter.denyNameStartsWith("org.springframework.integration.config.ServiceActivatorFactoryBean")` helped to clear log from  error messages

**Comment by jkschneider** [comment] 2018-02-23 14:20
@n0mer good to know! looks like we need to improve metric naming in spring-integration as well.
