### ISSUE TITLE
Recreate ConfigurableApplicationContext may cause OutOfMemory when using spring-boot-starter-actuator #19387

### ISSUE THREAD

**Issue by qfdk** [micrometer-metrics/micrometer#1759] opened 2019-12-17 17:00 UTC
I have a SpringBoot application using actuator, in my method update Context, I need to recreate ConfigurableApplicationContext in order to use the new properties updated in application.properties, because in SpringBoot actuator doesn’t have “refresh” endpoint. 

In production this service may called only 1 time by week. After 3 mouths I got OOM.

After analyzing of headdump in prod, the problem came form io.micrometer using by actuator.

io.micrometer.core.instrument.binder.tomcat.TomcatMetrics

I created a demo project to isole le problem.

### pom.xml

```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.7.RELEASE</version>
        <!--same problem-->
        <!--<version>2.2.2.RELEASE</version>-->
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.8</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```
### DemoApplication

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class DemoApplication {

    public static ConfigurableApplicationContext context = null;

    public static void main(String[] args) {
        DemoApplication.context = SpringApplication.run(DemoApplication.class, args);
    }

}
```

### MyController

```java
package me.qfdk.demo;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

@RestController
@Slf4j
public class MyController {
    @GetMapping("/")
    // call every 5 s
    @Scheduled(cron = "0/5 * * * * ?")
    public void test() {
        ThreadPoolExecutor threadPool;
        threadPool = new ThreadPoolExecutor(1, 1, 0, TimeUnit.SECONDS, new ArrayBlockingQueue<>(1), new ThreadPoolExecutor.DiscardOldestPolicy());
        threadPool.execute(() -> {
            // close context
            DemoApplication.context.close();
            log.info("[update] create new Context");
            DemoApplication.context = SpringApplication.run(DemoApplication.class, "");
            log.info("[update] update done");
        });
        threadPool.shutdown();
    }
}

```
![img1](https://user-images.githubusercontent.com/2404478/71007084-b0437800-20e6-11ea-8be1-38c6df89087c.png)
![img2](https://user-images.githubusercontent.com/2404478/71007086-b174a500-20e6-11ea-91a3-03c53121403a.png)

**using JVM option to give the problem faster _-Xms128m -Xmx128m -XX:+HeapDumpOnOutOfMemoryError_**

### Solution ?
**AutoCloseable** could be implemented in TomcatMetrics

**Comment by izeye** [comment] 2019-12-18 04:58
@qfdk Thanks for the issue! If any notification could be missing somehow, there doesn't seem to be any way to clean up notification listeners implicitly. I created #1760 to try to resolve this by implementing `AutoCloseable` as you suggested. If we go down this route, consumers like Spring Boot also need to be updated accordingly.

**Comment by qfdk** [comment] 2019-12-19 08:03
Hi @izeye ,
Thx for the discussion and PR. I have compiled the 1.1.x branch with the correction class **TomcatMetric**, It seems to not be working for me. I got a head dump, now i try to investigate.

![bug](https://user-images.githubusercontent.com/2404478/71155254-9d8f8700-223d-11ea-92ae-6d066fb3224e.png)

**Comment by izeye** [comment] 2019-12-19 08:18
@qfdk Thanks for trying it out. As I mentioned above, Spring Boot also needs to be changed to call `TomcatMetrics.close()` when the application context is being closed.

**Comment by izeye** [comment] 2019-12-19 08:18
@qfdk Thanks for trying it out. As I mentioned above, Spring Boot also needs to be changed to call `TomcatMetrics.close()` when the application context is being closed.

**Comment by qfdk** [comment] 2019-12-19 08:25
@izeye I change tomcat by jetty to try. The problem did not re-prod. After Full GC memory came back. Thanks i will recreate an issue or a pr for SpringBoot
![Snipaste_2019-12-19_09-22-40](https://user-images.githubusercontent.com/2404478/71156891-3a075880-2241-11ea-85ac-5d65ea2f86bb.png)

**Comment by shakuzen** [comment] 2019-12-29 09:36
Duplicate of #1424

**Closed by shakuzen** 2019-12-29 09:36 UTC
