### ISSUE TITLE
Getting error Prometheus requires that all meters with the same name have the same

### ISSUE THREAD

**Issue by nikunjy** [micrometer-metrics/micrometer#2540] opened 2021-03-29 22:27 UTC
I am emitting a metric like this in kotlin
``` 
fun doit(status: String, topic: String, consumergroupId: String) {
 eventsConsumed
            .tag("topic", topic)
            .tag("consumer_group_id", consumerGroupId)
            .tag("status", status)
            .register(meterRegistry)
            .increment()
}
```

`doit` is called multiple times, values are never empty but yet I run into the error 

```
Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named
```

I think there is some sort of bug here in getting the tags ?
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L482

**Comment by jonatan-ivanov** [comment] 2021-03-31 00:13
Duplicate of https://github.com/micrometer-metrics/micrometer/issues/877
@nikunjy please see this comment: https://github.com/micrometer-metrics/micrometer/issues/877#issuecomment-425102772 and this one: https://github.com/micrometer-metrics/micrometer/issues/877#issuecomment-655598760

**Closed by jonatan-ivanov** 2021-03-31 00:13 UTC

**Comment by nikunjy** [comment] 2021-03-31 00:49
So @jonatan-ivanov  my problem is not the same because I am okay with the limitation that micrometer can't support multiple tags. However why is it even throwing that error because I am always registering same tags every single time.

**Comment by jonatan-ivanov** [comment] 2021-03-31 01:34
Are you sure you don't register the meter with the same name but different set of tags anywhere else?
Please double-check this (since the exception says otherwise): comment out this snippet and check if the meter is registered, null-check the fields, etc. If you are sure you don't have already an existing meter with the same name, please create a *minimal* (preferably Java) project that reproduces the issue and I will reopen this.
