### ISSUE TITLE
Using publishPercentileHistogram breaks histogram values

### ISSUE THREAD

**Issue by JonasKunz** [micrometer-metrics/micrometer#3904] opened 2023-06-14 08:44 UTC
**Describe the bug**

After upgrading from micrometer `1.10.6` to `1.11.0` we noticed test failures in our application regarding histograms.
Our application is the elastic APM Java Agent. While we do not use micrometer ourselves, we do provide instrumentations for capturing user defined metrics via micrometer. For these instrumentations we have unit tests, which are the ones which started to fail after upgrading to `1.11.0`. 

The failure we are seeing is that `DistributionSummaries` report invalid `CountAtBuckets` when also using `publishPercentileHistogram()`. See the test case and the comments for details.

**Environment**

 - Micrometer version `1.11.0`, same issue occurs with `1.11.1`
 - Micrometer registry `SimpleMeterRegistry`

**To Reproduce**

```java
    @Test
    void verifyHistogram() {
        SimpleMeterRegistry registry = new SimpleMeterRegistry();
        DistributionSummary meter = DistributionSummary
                .builder("my_histogram")
                .serviceLevelObjectives(5, 50, 95)
                .publishPercentileHistogram() //when commenting out this line, everything works fine on 1.11.0+
                .register(registry);

        for(int val : new int[]{22, 55, 66, 98}) {
            meter.record(val);
        }

        HistogramSnapshot snapshot = meter.takeSnapshot();
        CountAtBucket[] countAtBuckets = snapshot.histogramCounts();

        assertThat(countAtBuckets)
                .extracting(CountAtBucket::bucket)
                .containsExactly(5.0, 50.0, 95.0);

        //this assertion fails on 1.11.0+: The bucket values are [0.0, 0.0, 0.0]
        assertThat(countAtBuckets)
                .extracting(CountAtBucket::count)
                .containsExactly(0.0, 1.0, 3.0);
    }
```

**Expected behavior**

I would expect the bucket values to be as shown in the test and not depend on the presence/absence of `publishPercentileHistogram()`. If this is not a bug and instead caused by wrong usage from our side, please let me know.

**Comment by shakuzen** [comment] 2023-06-16 07:51
That is unexpected. Thank you for reporting the issue with a test case to reproduce it. We'll add a test case to make sure this stays fixed in the future. I found the cause of the regression to be https://github.com/micrometer-metrics/micrometer/pull/3581.

**Closed** 2023-06-22 03:55 UTC
Labels: regression, module: micrometer-core

**Comment by shakuzen** [comment] 2023-06-22 05:09
Thank you for catching this and reporting it to us with a test case. A fix is now available in the latest snapshots. If you have a chance to test that out and let us know if there is any remaining issue, it would be appreciated.
