### ISSUE TITLE
DatadogMeterRegistry: add support for publishing distributions

### ISSUE THREAD

**Issue by monosoul** [micrometer-metrics/micrometer#3243] opened 2022-06-22 14:59 UTC
**Please describe the feature request.**
At the moment `DatadogMeterRegistry` doesn't support publishing percentile histogram, while DD's API seems to support publishing distributions already: https://docs.datadoghq.com/api/latest/metrics/#submit-distribution-points .

**Rationale**
For `DatadogMeterRegistry` to reach feature parity with the statsd registry

**Comment by shakuzen** [comment] 2022-06-23 08:17
Thanks for letting us know an HTTP API is available for sending distributions now. We previously abandoned efforts to support this with the Datadog registry due to the lack of API. I do still have concerns about how we could/should best handle such a feature. See my previous comment on it https://github.com/micrometer-metrics/micrometer/issues/1056#issuecomment-625630327. Unlike the statsd registry, the datadog registry is a step meter registry, which pushes metrics at step intervals. However, to send the raw data that datadog expects for distributions, we would need to either separately publish distribution data in near-realtime with recording or buffer the raw data for publishing. This would add significant complexity. It may still be worth adding if it provides enough value for users.

**Comment by shakuzen** [comment] 2022-08-05 11:04
I realize we already had an open issue for this: #773. I'll close this as a duplicate of the older issue to keep things in one place.

**Comment by shakuzen** [comment] 2022-08-05 11:04
Duplicate of #773

**Closed by shakuzen** 2022-08-05 11:04 UTC
Labels: duplicate
