### ISSUE TITLE
Hazelcast Cache Metrics, put operation count incorrect

### ISSUE THREAD

**Issue by neilstevenson** [micrometer-metrics/micrometer#3555] opened 2022-12-04 14:18 UTC
**Describe the bug**
Hazelcast has two variations for

Hazelcast's Spring Cache uses the latter
(https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/java/com/hazelcast/spring/cache/HazelcastCache.java#L114)

Micrometer counts the former (https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/HazelcastCacheMetrics.java#L125)

It should use `localMapStats.getPutOperationCount() + localMapStats.getSetOperationCount()`

**Environment**
N/a

**To Reproduce**
I don't have code, but anything `@Cacheable` in Spring that saves to Hazelcast should be enough.

**Expected behavior**
Cache "_put_" counts should report as non-zero

**Additional context**
See also https://github.com/hazelcast/hazelcast/issues/23063, which may change the implement from IMap _set_ to IMap _put_

**Comment by izeye** [comment] 2022-12-08 14:48
This seems to be a duplicate of https://github.com/micrometer-metrics/micrometer/issues/3556.

**Comment by shakuzen** [comment] 2023-01-12 08:27
Duplicate of #3556

**Closed by shakuzen** 2023-01-12 08:27 UTC
Labels: waiting-for-triage
