### ISSUE TITLE
when i upgrade to 1.1.3, metric name  was changed

### ISSUE THREAD

**Issue by endink** [micrometer-metrics/micrometer#1267] opened 2019-03-08 14:34 UTC
for example:

old:
jvm_classes_loaded
new:
jvm_classes_loaded_classes

so grafana dashboard was not worked.

is there a changes log for release?

**Comment by izeye** [comment] 2019-03-08 17:06
Duplicate of #1063

**Closed by izeye** 2019-03-08 17:07 UTC

**Comment by izeye** [comment] 2019-03-08 17:11
@endink Thanks for the report but this seems duplicate of #1063. For entry in release notes, I updated the release notes for the 1.1.0 to include the change as follows:

> Add base units to several binders. (Breaking change for Prometheus. See #1063)

See https://github.com/micrometer-metrics/micrometer/releases/tag/v1.1.0

**Comment by shashwot** [comment] 2020-09-15 11:14
> for example:
> 
> old:
> jvm_classes_loaded
> new:
> jvm_classes_loaded_classes
> 
> so grafana dashboard was not worked.
> 
> is there a changes log for release?


Go to dashboard settings -> Variables -> change the name from jvm_classes_loaded to jvm_classes_loaded_classes.
