### ISSUE TITLE
ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by nithya11** [micrometer-metrics/micrometer#2140] opened 2020-06-05 19:46 UTC
Micrometer version: 1.1.2

Publishing metrics with statsD micrometer occasionally throws the following exception: 

```
i.m.s.i.n.u.ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
    io.micrometer.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
    io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
    io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
    io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
    io.micrometer.shaded.reactor.netty.NettyOutbound.lambda$sendString$5(NettyOutbound.java:300)
    io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
    io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.drain(FluxOnBackpressureLatest.java:176)
    io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.onNext(FluxOnBackpressureLatest.java:127)
    io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
    io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNextNewBuffer(FluxBufferPredicate.java:277)
    io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.tryOnNext(FluxBufferPredicate.java:224)
    io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNext(FluxBufferPredicate.java:194)
    io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:530)
    io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:972)
    io.micrometer.shaded.reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
    io.micrometer.shaded.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
    io.micrometer.shaded.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
    io.micrometer.shaded.reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
    io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153)
    io.micrometer.statsd.StatsdDistributionSummary.recordNonNegative(StatsdDistributionSummary.java:52)
    io.micrometer.core.instrument.AbstractDistributionSummary.record(AbstractDistributionSummary.java:49)
    io.micrometer.core.instrument.composite.CompositeDistributionSummary.lambda$record$0(CompositeDistributionSummary.java:38)
    java.base/java.lang.Iterable.forEach(Iterable.java:75)
    io.micrometer.core.instrument.composite.AbstractCompositeMeter.forEachChild(AbstractCompositeMeter.java:47)
    io.micrometer.core.instrument.composite.CompositeDistributionSummary.record(CompositeDistributionSummary.java:38)

**Comment by jkschneider** [comment] 2020-06-05 22:26
@nithya11 I can't remember which minor release it was, but ultimately this was a problem with reactor netty fixed by incorporating a later release of it in later versions of Micrometer. Can you try Micrometer 1.5.1 and see if you see the same?

**Comment by StephenHolmes14** [comment] 2020-06-08 09:04
Not OP but I'm having the same error on 1.5.1:

```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.micrometer.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
	io.micrometer.shaded.reactor.netty.NettyOutbound.lambda$sendString$5(NettyOutbound.java:300)
	io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.drain(FluxOnBackpressureLatest.java:176)
	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.onNext(FluxOnBackpressureLatest.java:127)
	io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNextNewBuffer(FluxBufferPredicate.java:269)
	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.tryOnNext(FluxBufferPredicate.java:216)
	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNext(FluxBufferPredicate.java:186)
	io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:535)
	io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:999)
	io.micrometer.shaded.reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
	io.micrometer.shaded.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
	io.micrometer.shaded.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
	io.micrometer.shaded.reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
	io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:248)
	io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:168)
	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.lambda$next$1(LogbackMetricsSuppressingFluxSink.java:49)
	io.micrometer.core.instrument.binder.logging.LogbackMetrics.ignoreMetrics(LogbackMetrics.java:113)
	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:49)
	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:25)
	io.micrometer.statsd.StatsdFunctionCounter.lambda$poll$0(StatsdFunctionCounter.java:46)
	java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(Unknown Source)
	io.micrometer.statsd.StatsdFunctionCounter.poll(StatsdFunctionCounter.java:44)
	io.micrometer.statsd.StatsdMeterRegistry.poll(StatsdMeterRegistry.java:175)
	io.micrometer.statsd.StatsdMeterRegistry.lambda$startPolling$13(StatsdMeterRegistry.java:282)
	io.micrometer.shaded.reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:140)
	io.micrometer.shaded.reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:123)
	io.micrometer.shaded.reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	io.micrometer.shaded.reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by shakuzen** [comment] 2020-06-10 08:14
@nithya11 @StephenHolmes14 do you have any ideas for how to reproduce this? When is it happening? Is it happening consistently?

**Comment by caspertradeshift** [comment] 2020-06-17 07:19
I am also experiencing this, aprox once a day for a service running a scheduled job every 5 sec, this started to happen after Spring Boot upgrade from `2.1.4.RELEASE` (micometer 1.1.4) to `2.3.1.RELEASE`(micormeter 1.5.1),

**Comment by cmayne-r7** [comment] 2020-06-19 19:27
Also experiencing this, in both deployed and local environments, Spring Boot version 2.3.0.RELEASE, micrometer 1.5.1

**Comment by cicilthomas** [comment] 2020-06-22 08:44
Started experiencing the same issue after upgrading to springboot `2.3.1.RELEASE` and micrometer `1.5.1`
@shakuzen for me this can be reproduced by just running the springboot app and doing nothing. This error will be thrown after sometime (˜10-15 mins)

**Comment by shakuzen** [comment] 2020-06-22 14:50
I'm having trouble reproducing this on OSX using Java 11.0.7 - I've had a demo application using the StatsdMeterRegistry running for over 2 hours.

On what OS and Java version is everyone seeing this happen on?

We'll try upgrading to the latest patch release of reactor-netty and reactor-core in 1.5.2 to see if that helps but we haven't been able to identify the cause yet.

**Comment by nithya11** [comment] 2020-06-22 20:26
> @nithya11 @StephenHolmes14 do you have any ideas for how to reproduce this? When is it happening? Is it happening consistently?

It is not consistent. Just like how others have mentioned it happens sporadically

**Comment by cicilthomas** [comment] 2020-06-23 17:16
@shakuzen I have created a sample springboot app which will throw this error. Here is the repo [link](https://github.com/cicilthomas/micrometer). The `error.txt` is the console log and if you check it, the error occurred after 1:30Hrs.

I'm on macOS `10.14.6` and Java `11.0.3`

**Comment by nefsir** [comment] 2020-06-25 05:13
Same here, after Spring Boot upgrade 2.2.6.RELEASE to 2.3.0.RELEASE I see this in logs for all our services. It eventually leads to OOM crash. Histogram:
![image](https://user-images.githubusercontent.com/12825757/85658098-2686ef80-b6b3-11ea-89d7-19ad7dea531a.png)
And leak suspect by MAT:
![image](https://user-images.githubusercontent.com/12825757/85658248-5209da00-b6b3-11ea-99bf-9b54a732c368.png)

**Comment by tha2015** [comment] 2020-06-30 22:40
> Not OP but I'm having the same error on 1.5.1:
> 
> ```
> LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
> Recent access records: 
> Created at:
> 	io.micrometer.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
> 	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
> 	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
> 	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
> 	io.micrometer.shaded.reactor.netty.NettyOutbound.lambda$sendString$5(NettyOutbound.java:300)
> 	io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
> 	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.drain(FluxOnBackpressureLatest.java:176)
> 	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.onNext(FluxOnBackpressureLatest.java:127)
> 	io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
> 	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNextNewBuffer(FluxBufferPredicate.java:269)
> 	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.tryOnNext(FluxBufferPredicate.java:216)
> 	io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.onNext(FluxBufferPredicate.java:186)
> 	io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:535)
> 	io.micrometer.shaded.reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:999)
> 	io.micrometer.shaded.reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
> 	io.micrometer.shaded.reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
> 	io.micrometer.shaded.reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
> 	io.micrometer.shaded.reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618)
> 	io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.drainLoop(FluxCreate.java:248)
> 	io.micrometer.shaded.reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:168)
> 	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.lambda$next$1(LogbackMetricsSuppressingFluxSink.java:49)
> 	io.micrometer.core.instrument.binder.logging.LogbackMetrics.ignoreMetrics(LogbackMetrics.java:113)
> 	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:49)
> 	io.micrometer.statsd.internal.LogbackMetricsSuppressingFluxSink.next(LogbackMetricsSuppressingFluxSink.java:25)
> 	io.micrometer.statsd.StatsdFunctionCounter.lambda$poll$0(StatsdFunctionCounter.java:46)
> 	java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(Unknown Source)
> 	io.micrometer.statsd.StatsdFunctionCounter.poll(StatsdFunctionCounter.java:44)
> 	io.micrometer.statsd.StatsdMeterRegistry.poll(StatsdMeterRegistry.java:175)
> 	io.micrometer.statsd.StatsdMeterRegistry.lambda$startPolling$13(StatsdMeterRegistry.java:282)
> 	io.micrometer.shaded.reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:140)
> 	io.micrometer.shaded.reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:123)
> 	io.micrometer.shaded.reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
> 	io.micrometer.shaded.reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
> 	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
> 	java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
> 	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	java.base/java.lang.Thread.run(Unknown Source)
> ```

Same issue here, happening since migrating to Spring Boot 2.3.1 (micrometer 1.5.1)

**Comment by leonhartX** [comment] 2020-07-12 03:41
I've updated to micormeter 1.5.2 but this issue still exists.
I'm using Java 8, both the local(macOS) and production(Amazon Linux) environment have this issue after running the app for a while.

**Comment by tha2015** [comment] 2020-07-12 03:57
I had the same exception when statsd UDP port was not open.

**Comment by cicilthomas** [comment] 2020-07-14 13:07
@shakuzen I updated `micrometer-registry-statsd` to `1.5.2` and I still get the same error.

**Comment by kyrylo-novotarskyi** [comment] 2020-07-17 11:11
Same as @cicilthomas -> all latest dependencies give the error

**Comment by jhigueras** [comment] 2020-07-17 18:20
Same problem here, with spring-boot 2.3.1 and micrometer 1.5.2 the problem raises eventually in our services. The worst part is that error causes an increase in cpu load :/

**Comment by shakuzen** [comment] 2020-07-22 17:36
I understand a lot of people are seeing this issue. The difficulty to reproduce this in a predictable and controlled way is making it difficult to track down its cause. It is possible that [this leak in reactor-netty](https://github.com/reactor/reactor-netty/pull/1172) is the cause. I've upgraded in snapshots (#2188) to the version of reactor-netty with the leak fix. I am wondering if that helps with this issue. I've run a sample application on the latest 1.5.3-SNAPSHOT version for a little while and haven't seen the issue so far, but I'm hoping some of you can try with the latest snapshot as well and let us know if you're still seeing it.

**Comment by ekennedy247** [comment] 2020-07-23 12:56
I had this exception stop happening when I fixed the statsd host address I had forgot in one of my sub-modules to the correct address. After doing that, went from seeing this ~6 times a day to 0 over the last 24 hours.

Thanks, https://github.com/micrometer-metrics/micrometer/issues/2140#issuecomment-657171510!

**Comment by kyrylo-novotarskyi** [comment] 2020-07-23 13:24
After upgrading to `1.5.3-SNAPSHOT` the issue exception stopped occurring, but started getting a bunch of warnings, such as:
```
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at io.micrometer.shaded.reactor.core.publisher.Operators.onDiscardMultiple(Operators.java:565)
	at io.micrometer.shaded.reactor.core.publisher.FluxBufferPredicate$BufferPredicateSubscriber.cancel(FluxBufferPredicate.java:174)
	at io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:160)
	at io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.cancel(FluxOnBackpressureLatest.java:99)
	at io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:160)
	at io.micrometer.shaded.reactor.core.publisher.Operators.terminate(Operators.java:1222)
	at io.micrometer.shaded.reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:264)
	at io.micrometer.shaded.reactor.netty.channel.MonoSendMany$SendManyInner.operationComplete(MonoSendMany.java:114)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.micrometer.shaded.io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.micrometer.shaded.io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.micrometer.shaded.io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158)
	at io.micrometer.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.micrometer.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.micrometer.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.micrometer.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.micrometer.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.micrometer.shaded.io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.micrometer.shaded.io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at io.micrometer.shaded.io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.micrometer.shaded.io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
	at io.micrometer.shaded.reactor.netty.DisposableChannel.dispose(DisposableChannel.java:76)
	at io.micrometer.shaded.reactor.netty.channel.ChannelOperations.dispose(ChannelOperations.java:168)
	at io.micrometer.shaded.reactor.core.Disposables.set(Disposables.java:421)
	at io.micrometer.shaded.reactor.core.Disposables$SwapDisposable.update(Disposables.java:317)
	at io.micrometer.statsd.StatsdMeterRegistry.lambda$retryReplaceClient$12(StatsdMeterRegistry.java:273)
	at io.micrometer.shaded.reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:168)
```
Which is likely coming from this commit (dated **13th of June**): 
https://github.com/micrometer-metrics/micrometer/commit/524da6968a85a5f2087aad273d18b4f3cea6257f

Since then, I have noticed that the DataDog sidecar container to the application was heavily resource-constrained. 
In the end: 
1. Upgraded the agents and relieved the backpressure constraints on the capacity end.
2. Noticed that Micrometer `1.5.1` is the one originally bundled in the latest Spring Boot `2.3.1.RELEASE` update dated **12th of June**. This is the version we have upgraded to recently, after which the original exception started happening. 
3. Downgraded Micrometer from `1.5.3-SNAPSHOT` back to version `1.5.1`.

After running around ~18 hours under nominal excepted peak capacity, both the original exception and the warnings coming from `1.5.3-SNAPSHOT` disappeared. 
The assumption is that the issue occurs under mixed conditions where both the significant backpressure is present over a period of time and the changes included in versions `1.5.1+` accumulate to the problem. Not sure whether the changes should be attributed to the diff from `StatsdMeterRegistry` though - might be that it is symptomatic and the underlying root cause is the one mentioned https://github.com/micrometer-metrics/micrometer/issues/2140#issuecomment-662588380 (thanks for helping to navigate by the way!).
So the issue got resolved in our particular case, although through a patch version downgrade. Thank you 👍

**Comment by kdamevin** [comment] 2020-07-24 02:35
Getting the issue as well with micrometer 1.5.2. 
However we encountered another issue in 1.5.1 with duplicate metrics being sent (https://github.com/micrometer-metrics/micrometer/issues/2138) so not easy for us to downgrade. Not sure what's better 😓

**Comment by shakuzen** [comment] 2020-07-28 03:13
I believe the last upgrade to reactor-netty containing the mentioned fix above https://github.com/micrometer-metrics/micrometer/issues/2140#issuecomment-662588380 has resolved the original issue here. Therefore I'd like to close this issue. We can reopen and investigate if anyone is still experiencing it on the latest 1.5.3 or later. As for the new exception mentioned by @kyrylo-novotarskyi, I'd like to track that in a separate issue if that's still happening after a fix for #2177.

**Closed by shakuzen** 2020-07-28 03:13 UTC
Labels: registry: statsd

**Comment by carl-pritchett** [comment] 2020-07-28 23:22
@shakuzen I'm seeing this on 1.5.3 
`LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.micrometer.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	io.micrometer.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
	io.micrometer.shaded.reactor.netty.NettyOutbound.lambda$sendString$5(NettyOutbound.java:302)
	io.micrometer.shaded.reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.drain(FluxOnBackpressureLatest.java:176)
	io.micrometer.shaded.reactor.core.publisher.FluxOnBackpressureLatest$LatestSubscriber.onNext(FluxOnBackpressureLatest.java:127)
....
`

**Comment by kdamevin** [comment] 2020-07-29 06:00
@shakuzen We are seeing the same issue @kyrylo-novotarskyi mentioned above since we bumped to 1.5.3. Is that tracked somewhere else?

```logger_name: io.micrometer.shaded.reactor.core.publisher.Operators
   message: Error while discarding collection, stopping
   stack_trace: java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at io.micrometer.shaded.reactor.core.publisher.Operators.onDiscardMultiple(Operators.java:565)...```

**Comment by shakuzen** [comment] 2024-08-30 01:40
@aygulsalahli that looks like a different issue to the one reported here, despite having the same exception message. From the stack trace you can see it contains the Grpc instrumentation and doesn't contain the statsd registry. Could you open a separate issue for it and provide a way to reproduce?
