### ISSUE TITLE
A fatal error has been detected libio_micrometer_shaded_netty_transport_native_epoll_x86_64

### ISSUE THREAD

**Issue by daniyar-artykov** [micrometer-metrics/micrometer#3177] opened 2022-05-13 18:25 UTC
**Describe the bug**
My app stops and become broken on the line Metrics.addRegistry(new StatsdMeterRegistry(configs, clock)

**Environment**
 - Micrometer version 1.8.2
 - Micrometer registry DataDog
 - Docker
 - Host: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz, 4 cores, 1G, Alpine Linux v3.14
 - JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-alpine-r0)
 - Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-alpine-r0, mixed mode, tiered, compressed oops, serial gc, linux-amd64)

**Expected behavior**
MeterRegistry should be successfully added.

I've attached full trace of the error. Might be some native libs are missing.

`A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x0000000000003fd6, pid=1, tid=8

JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-alpine-r0)
Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-alpine-r0, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
Problematic frame:
C  0x0000000000003fd6

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/core.1)

Can not save log file, dump to screen..

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x0000000000003fd6, pid=1, tid=8

JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-alpine-r0)
Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-alpine-r0, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
Problematic frame:
C  0x0000000000003fd6

Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/core.1)

If you would like to submit a bug report, please visit:
https://gitlab.alpinelinux.org/alpine/aports/issues
The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  S U M M A R Y ------------

Command Line: -javaagent:/home/dd-java-agent.jar -Ddd.profiling.enabled=true -Ddd.logs.injection=true -Ddd.trace.sample.rate=1 -Ddd.service=apa-engine -Ddd.env=poc /home/apa-engine-1.0.0-jar-with-dependencies.jar

Host: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz, 4 cores, 1G, Alpine Linux v3.14
Time: Fri May 13 17:48:03 2022 UTC elapsed time: 17.987608 seconds (0d 0h 0m 17s)

---------------  T H R E A D  ---------------

Current thread (0x00007f310b648800):  JavaThread "main" [_thread_in_native, id=8, stack(0x00007f310b6ef000,0x00007f310b7efad8)]

Stack: [0x00007f310b6ef000,0x00007f310b7efad8],  sp=0x00007f310b7ea468,  free space=1005k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000000003fd6
C  [libio_micrometer_shaded_netty_transport_native_epoll_x86_641883406040202622072.so+0xbd07]  netty_jni_util_JNI_OnLoad+0x67
C  [libjava.so+0xfc7a]  Java_java_lang_ClassLoader_00024NativeLibrary_load0+0xba
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;Z)Z+0 java.base@11.0.11
j  java.lang.ClassLoader$NativeLibrary.load()Z+53 java.base@11.0.11
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.11
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.11
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+70 java.base@11.0.11
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.11
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.11
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
V  [libjvm.so+0x817ee3]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;Z)Z+0 java.base@11.0.11
j  java.lang.ClassLoader$NativeLibrary.load()Z+53 java.base@11.0.11
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.11
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.11
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+70 java.base@11.0.11
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.11
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.11
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@11.0.11
J 3225 c1 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.11 (104 bytes) @ 0x00007f30f4e08d7c [0x00007f30f4e08a20+0x000000000000035c]
J 1059 c1 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.11 (10 bytes) @ 0x00007f30f4a19dbc [0x00007f30f4a19cc0+0x00000000000000fc]
J 1058 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@11.0.11 (65 bytes) @ 0x00007f30f4a1984c [0x00007f30f4a19520+0x000000000000032c]
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryLoader$1.run()Ljava/lang/Object;+53
v  ~StubRoutines::call_stub
J 1119  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.11 (0 bytes) @ 0x00007f30fbde988f [0x00007f30fbde9840+0x000000000000004f]
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(Ljava/lang/Class;Ljava/lang/String;Z)V+10
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(Ljava/lang/ClassLoader;Ljava/lang/String;Z)V+15
j  io.micrometer.shaded.io.netty.util.internal.NativeLibraryLoader.load(Ljava/lang/String;Ljava/lang/ClassLoader;)V+359
j  io.micrometer.shaded.io.netty.channel.epoll.Native.loadNativeLibrary()V+60
j  io.micrometer.shaded.io.netty.channel.epoll.Native.<clinit>()V+76
v  ~StubRoutines::call_stub
j  io.micrometer.shaded.io.netty.channel.epoll.Epoll.<clinit>()V+28
v  ~StubRoutines::call_stub
J 816  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class; java.base@11.0.11 (0 bytes) @ 0x00007f30fbdd253a [0x00007f30fbdd24c0+0x000000000000007a]
j  java.lang.Class.forName(Ljava/lang/String;)Ljava/lang/Class;+11 java.base@11.0.11
j  io.micrometer.shaded.reactor.netty.resources.DefaultLoopEpoll.<clinit>()V+12
v  ~StubRoutines::call_stub
j  io.micrometer.shaded.reactor.netty.resources.DefaultLoopNativeDetector.<clinit>()V+29
v  ~StubRoutines::call_stub
j  io.micrometer.shaded.reactor.netty.resources.LoopResources.hasNativeSupport()Z+0
j  io.micrometer.shaded.reactor.netty.resources.DefaultLoopResources.onClient(Z)Lio/micrometer/shaded/io/netty/channel/EventLoopGroup;+4
j  io.micrometer.shaded.reactor.netty.transport.NameResolverProvider.newNameResolverGroup(Lio/micrometer/shaded/reactor/netty/resources/LoopResources;Z)Lio/micrometer/shaded/io/netty/resolver/dns/DnsAddressResolverGroup;+18
j  io.micrometer.shaded.reactor.netty.udp.UdpResources.getOrCreateDefaultResolver()Lio/micrometer/shaded/io/netty/resolver/AddressResolverGroup;+25
j  io.micrometer.shaded.reactor.netty.udp.UdpClientConfig.defaultAddressResolverGroup()Lio/micrometer/shaded/io/netty/resolver/AddressResolverGroup;+3
j  io.micrometer.shaded.reactor.netty.transport.ClientTransportConfig.resolverInternal()Lio/micrometer/shaded/io/netty/resolver/AddressResolverGroup;+15
j  io.micrometer.shaded.reactor.netty.transport.ClientTransport.connect()Lio/micrometer/shaded/reactor/core/publisher/Mono;+23
j  io.micrometer.shaded.reactor.netty.udp.UdpClient.connect()Lio/micrometer/shaded/reactor/core/publisher/Mono;+1
j  io.micrometer.statsd.StatsdMeterRegistry.lambda$connectAndSubscribe$13(Lio/micrometer/shaded/reactor/netty/udp/UdpClient;)Lio/micrometer/shaded/reactor/core/publisher/Mono;+11
j  io.micrometer.statsd.StatsdMeterRegistry$$Lambda$202.get()Ljava/lang/Object;+8
j  io.micrometer.shaded.reactor.core.publisher.MonoDefer.subscribe(Lio/micrometer/shaded/reactor/core/CoreSubscriber;)V+4
j  io.micrometer.shaded.reactor.core.publisher.FluxRetryWhen.subscribe(Lio/micrometer/shaded/reactor/core/CoreSubscriber;Lio/micrometer/shaded/reactor/util/retry/Retry;Lio/micrometer/shaded/reactor/core/CorePublisher;)V+106
j  io.micrometer.shaded.reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(Lio/micrometer/shaded/reactor/core/CoreSubscriber;)Lio/micrometer/shaded/reactor/core/CoreSubscriber;+9
j  io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Lio/micrometer/shaded/org/reactorstreams/Subscriber;)V+26
j  io.micrometer.shaded.reactor.core.publisher.Mono.subscribeWith(Lio/micrometer/shaded/org/reactorstreams/Subscriber;)Lio/micrometer/shaded/org/reactorstreams/Subscriber;+2
j  io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Ljava/util/function/Consumer;Ljava/util/function/Consumer;Ljava/lang/Runnable;Lio/micrometer/shaded/reactor/util/context/Context;)Lio/micrometer/shaded/reactor/core/Disposable;+14
j  io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Ljava/util/function/Consumer;Ljava/util/function/Consumer;Ljava/lang/Runnable;)Lio/micrometer/shaded/reactor/core/Disposable;+8
j  io.micrometer.shaded.reactor.core.publisher.Mono.subscribe(Ljava/util/function/Consumer;)Lio/micrometer/shaded/reactor/core/Disposable;+12
j  io.micrometer.statsd.StatsdMeterRegistry.retryReplaceClient(Lio/micrometer/shaded/reactor/core/publisher/Mono;)V+27
j  io.micrometer.statsd.StatsdMeterRegistry.connectAndSubscribe(Lio/micrometer/shaded/reactor/netty/udp/UdpClient;)V+11
j  io.micrometer.statsd.StatsdMeterRegistry.prepareUdpClient(Lio/micrometer/shaded/org/reactorstreams/Publisher;Ljava/util/function/Supplier;)V+45
j  io.micrometer.statsd.StatsdMeterRegistry.start()V+122
j  io.micrometer.statsd.StatsdMeterRegistry.<init>(Lio/micrometer/statsd/StatsdConfig;Lio/micrometer/core/instrument/util/HierarchicalNameMapper;Lio/micrometer/core/instrument/config/NamingConvention;Lio/micrometer/core/instrument/Clock;Ljava/util/function/BiFunction;Ljava/util/function/Consumer;)V+167
j  io.micrometer.statsd.StatsdMeterRegistry.<init>(Lio/micrometer/statsd/StatsdConfig;Lio/micrometer/core/instrument/util/HierarchicalNameMapper;Lio/micrometer/core/instrument/Clock;)V+15
j  io.micrometer.statsd.StatsdMeterRegistry.<init>(Lio/micrometer/statsd/StatsdConfig;Lio/micrometer/core/instrument/Clock;)V+6
j  com.millenniumit.tradecho.engine.Engine.initMeterRegistry()V+66
j  com.millenniumit.tradecho.engine.Engine.start()V+94
j  com.millenniumit.tradecho.apaengine.Main.main([Ljava/lang/String;)V+37
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000003fd6`

**Comment by shakuzen** [comment] 2022-05-16 01:02
This sounds like a duplicate of #2776. Could you try with a 1.8.7 snapshot of micrometer dependencies to see if it is fixed with the upgrade to Netty 4.1.77?

**Comment by daniyar-bidgely** [comment] 2022-05-20 15:55
@shakuzen I updated micrometer version to 1.9.0 and netty-all version to 4.1.77 - and it solved the problem! Thank you very much!

**Closed** 2022-05-20 22:45 UTC
Labels: invalid, registry: statsd

**Comment by shakuzen** [comment] 2022-05-23 04:14
@daniyar-bidgely Thank you for trying the upgrade and reporting back. Just as a note, the version of netty you put on your classpath doesn't affect the version of netty used by the statsd module because we shade the netty dependencies it uses.
