### ISSUE TITLE
Breaking change on @Deprecated TimeStep constructor

### ISSUE THREAD

**Issue by Brutus5000** [micrometer-metrics/micrometer#873] opened 2018-09-24 15:43 UTC
Hey guys,

from v1.0.5 to v1.0.6 the @Deprecated constructor was extended from 5 to 6 arguments.

[see v1.0.6](https://github.com/micrometer-metrics/micrometer/blob/v1.0.6/micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepTimer.java#L36)
[see v1.0.5](https://github.com/micrometer-metrics/micrometer/blob/v1.0.5/micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepTimer.java#L36)

Unfortunately this breaks upstream applications. Can this change be reverted inside the 1.0.x release series? Otherwise the method could be remove as well.

**Comment by jkschneider** [comment] 2018-09-24 19:47
Thanks @Brutus5000. This is a duplicate of #791 which has already been fixed for the pending 1.0.7 release.

**Closed by jkschneider** 2018-09-24 19:47 UTC
