### ISSUE TITLE
Stackdriver Registry documentation

### ISSUE THREAD

**Issue by saturnism** [micrometer-metrics/micrometer#1659] opened 2019-10-24 01:40 UTC
I _just_ noticed that Micrometer has a Stackdriver metrics registry. But I did not find any documentation on setting up in http://micrometer.io/docs

Any pointers on how this is to be used, and where I can contribute docs to? Thanks!

**Comment by izeye** [comment] 2019-10-24 03:18
Duplicate of https://github.com/micrometer-metrics/micrometer-docs/issues/77

**Closed by izeye** 2019-10-24 03:18 UTC

**Comment by izeye** [comment] 2019-10-24 03:20
@saturnism Thanks for opening an issue! It'd be nice if you contribute docs for it in the referenced issue.

**Comment by saturnism** [comment] 2019-10-25 16:18
I'd love to contribute - but I need to know how to use it first ;) Any snippets on how to start configuring this would be useful before I can start contributing to the doc :)

**Comment by izeye** [comment] 2019-10-25 23:13
@saturnism [This sample](url) is what I used for testing before. I updated it to the latest versions and it seems to work as follows:

```
...
2019-10-26 08:02:00.611 DEBUG 86157 --- [trics-publisher] i.m.s.StackdriverMeterRegistry           : successfully sent 58 TimeSeries to Stackdriver
2019-10-26 08:02:47.592 DEBUG 86157 --- [trics-publisher] i.m.s.StackdriverMeterRegistry           : successfully sent 61 TimeSeries to Stackdriver
2019-10-26 08:03:49.589 DEBUG 86157 --- [trics-publisher] i.m.s.StackdriverMeterRegistry           : successfully sent 61 TimeSeries to Stackdriver
...
```

Hope that helps.

**Comment by saturnism** [comment] 2019-11-01 19:08
This is great!  Thanks for the pointer. I'll help w/ the doc.
