### ISSUE TITLE
v 1.15 fails to work with elastic 5.6.7 while checking version

### ISSUE THREAD

**Issue by mrkk** [micrometer-metrics/micrometer#1479] opened 2019-06-28 21:00 UTC
V 1.10 seems to work

   2019-06-28T14:27:40.03-0500 [APP/PROC/WEB/1] OUT 28-06-2019 19:27:40.036 [elastic-metrics-publisher] WARN  io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely:50 - Unexpected exception thrown while publishing metrics for ElasticMeterRegistry java.lang.IllegalArgumentException: Unexpected response body: No handler found for uri [/] and method [POST]
 at io.micrometer.elastic.ElasticMeterRegistry.getMajorVersion(ElasticMeterRegistry.java:253) ~[micrometer-registry-elastic-1.1.5.jar!/:1.1.5]
    at io.micrometer.elastic.ElasticMeterRegistry.determineMajorVersionIfNeeded(ElasticMeterRegistry.java:243) ~[micrometer-registry-elastic-1.1.5.jar!/:1.1.5]
      ... 9 common frames omitted
Wrapped by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Unexpected response body: No handler found for uri [/] and method [POST]
        at io.micrometer.elastic.ElasticMeterRegistry.determineMajorVersionIfNeeded(ElasticMeterRegistry.java:245) ~[micrometer-registry-elastic-1.1.5.jar!/:1.1.5]
   at io.micrometer.elastic.ElasticMeterRegistry.publish(ElasticMeterRegistry.java:187) ~[micrometer-registry-elastic-1.1.5.jar!/:1.1.5]
    at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48) ~[micrometer-core-1.1.4.jar!/:1.1.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
       at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

**Comment by mrkk** [comment] 2019-06-28 21:02
Basically it looked like it was doing a POST instead of GET to my server at http://10.126.171.176:9200

**Comment by izeye** [comment] 2019-06-28 22:56
@mrkk I can see the mixed versions of Micrometer dependencies in your stack trace: `micrometer-core-1.1.4.jar` vs. `micrometer-registry-elastic-1.1.5.jar`. I think #1427 which has been fixed in 1.1.5 is the cause, so if you also use 1.1.5 for `micrometer-core`, it should work.

Closing as this seems a problem of mixed versions of dependencies which has been affected by a fixed bug.

**Closed by izeye** 2019-06-28 22:56 UTC
