### ISSUE TITLE
GraphiteMeterRegistry prints stacktrace at shutdown time.

### ISSUE THREAD

**Issue by ekdxhrl0096** [micrometer-metrics/micrometer#1531] opened 2019-07-25 11:39 UTC
I experienced stacktrace every time I quit the spring application. 
It seems that when trying to close a non-Singleton value, an error occurs. 
How can I fix it?

*application.yml*
```
management:
  metrics:
    export:
      graphite:
        host: 127.0.0.1
        enabled: true
        port: 2003
        step: 20s
        protocol: plaintext
        prefix: "prefix"
```

*Stacktrace*
```
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'nullChannel': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:606)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:594)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1226)
	at org.springframework.integration.config.IntegrationManagementConfigurer.lambda$registerComponentGauges$1(IntegrationManagementConfigurer.java:407)
	at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.lambda$newGauge$0(DropwizardMeterRegistry.java:79)
	at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:368)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:268)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
	at io.micrometer.graphite.GraphiteMeterRegistry.close(GraphiteMeterRegistry.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1036)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1029)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945)
```

Has anyone experienced this experience?

**Comment by izeye** [comment] 2019-07-25 15:38
@ekdxhrl0096 Looking at the stack trace, `GraphiteMeterRegistry.close()` is calling `ScheduledReporter.report()` and along the way, some code from Spring Integration is calling `AbstractApplicationContext.getBeansOfType()` which triggers the exception. Looking into `IntegrationManagementConfigurer`, it uses `AbstractApplicationContext.getBeansOfType()` in gauge value functions, so it seems to be inevitable in the Micrometer point of view.

I tried to reproduce this stack trace and it required to enable debug level logging. Also the log level has been changed from warn to info recently, so it seems benign. There might be some room for enhancement in the side of Spring Integration, so you might want to raise an issue [there](https://github.com/spring-projects/spring-integration).

**Comment by izeye** [comment] 2019-07-25 15:44
> Also the log level has been changed from warn to info recently, so it seems benign.

Regardless of the log level, the metrics from on-close publishing will be lost, so it'd be good to be resolved somehow there.

**Comment by izeye** [comment] 2019-07-25 16:26
I created #1532 to publish other metrics although there's any exception from gauge value functions and the metric(s) couldn't be handled properly.

**Comment by ekdxhrl0096** [comment] 2019-07-31 00:28
> I tried to reproduce this stack trace and it required to enable debug level logging. Also the log level has been changed from warn to info recently, so it seems benign. There might be some room for enhancement in the side of Spring Integration, so you might want to raise an issue [there](https://github.com/spring-projects/spring-integration).

When Spring manages the life cycle, it is working based on a spring bean, which seems to be a non-singleton issue. I will take a closer look at this part and send a request to the Spring side.

Thanks for kind reply for me.

**Comment by ekdxhrl0096** [comment] 2019-07-31 00:29
> > Also the log level has been changed from warn to info recently, so it seems benign.
> 
> Regardless of the log level, the metrics from on-close publishing will be lost, so it'd be good to be resolved somehow there.

LGTM. Thanks :)

**Comment by shakuzen** [comment] 2021-03-31 07:06
If this is still an issue using the latest versions, please provide a minimal sample project that reproduces the issue. I'm closing as I believe there are no additional changes to be made in Micrometer.

**Closed by shakuzen** 2021-03-31 07:06 UTC
Labels: for: external-project
