### ISSUE TITLE
Meters garbage collection and memory footprint

### ISSUE THREAD

**Issue by boyan-velinov** [micrometer-metrics/micrometer#2193] opened 2020-07-16 12:36 UTC
Hello,

We would like to use micrometer with DynatraceMeterRegistry in our service but we are concerned about our approach of doing that. We are not sure how to handle with multiple registered meters with the same name and the consequent increased memory.

Basically our service performs some business processes. Each process can take for several seconds up to several hours.
We want to measure execution time of each process and also some more info about it, like who started the process, what is the process type and so on.

This is a simple stripped-down code that is executed every time when a process is finished:

```
Set<Tag> tags = new HashSet<>();
tags.add(Tag.of("process.id", id));
tags.add(Tag.of("process.type", type));
tags.add(Tag.of("process.namespace", namespace));
tags.add(Tag.of("user", user));
Timer timer = dynatraceMeterRegistry.timer("overall.duration", tags);
timer.record(duration, TimeUnit.MILLISECONDS);
```

In this way, the memory and  `dynatraceMeterRegistry.getMeters().size()`  is increasing after each finished process.
I expected that meter name is unique in `dynatraceMeterRegistry `and newly registered meter will replace previous one with the same name.
However this is not the case.

Initially, I considered is to have only one meter and change its tags for every process then record the new duration period. But seems tags of one meter are unmodifiable.

Last thing which I considered is to remove one meter after it is recorded. This is not working because the meter is removed at all and nothing is recorded in Dynatrace.

Can you give me advice how to proceed?

Best Regards,
Boyan

**Comment by checketts** [comment] 2020-07-16 22:06
See https://micrometer.io/docs/concepts#_tag_values

Metrics are best used for tracking aggregate behaviors. So a rule of thumb is to keep tag cardinality low. Process ID and User seems like they could be very open ended and cause a 'tag explosion', and as you noted will not ever be garbage collected.

I would recommend using the timer to record the duration, but then also log out the duration (perhaps as a debug level). That way if the timer metric is indicating unexpected behavior then it would lead you to check the logs to find the details.

**Comment by boyan-velinov** [comment] 2020-07-22 12:00
Thanks for the suggestion but I am afraid that this is not very sensible for our use case because we have to drill down in two different systems for root cause analysis.

Now we are considering some approach to handle the lifecycle of meters on our own. 
Are you aware of some option to check whether one meter has already been updated. Or for example if one meter is not been updated recently.
In this way, we can proceed with some regular job that will remove obsolete meters from the registry.

**Comment by marcingrzejszczak** [comment] 2023-12-20 11:51
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Closed by marcingrzejszczak** 2023-12-20 11:51 UTC
