### ISSUE TITLE
Only the first meter of meters with mixed tags gets exposed to Prometheus

### ISSUE THREAD

**Issue by Davio** [micrometer-metrics/micrometer#2678] opened 2021-07-01 12:56 UTC
This could be a Spring Boot issue, I'm not quite sure, if so I might post it there.

**Describe the bug**
When you have 2 meters (for instance counters) with the same id, but with mixed tags, for instance tags that are in the first meter which are not in the second or vice verse, only the first registered meter gets exposed to Prometheus.

**Environment**
 - Spring Boot 2.5.2
 - Micrometer 1.7.1
 - prometheus registry
 - OS: Linux
 - Java version: 11

**To Reproduce**
How to reproduce the bug:
Register 2 meters, such as:

    Counter.builder("test").tag("tag1", "test1").tag("tag2", "test2").register(meterRegistry).increment();
    Counter.builder("test").tag("tag1", "test1").tag("tag3", "test3").register(meterRegistry).increment();

Looking at the actuator endpoint, only the first one is shown: `test_total{tag1="test1",tag2="test2",} 1.0`

**Expected behavior**
Both meters are present for Prometheus and can be seen in the actuator endpoint.

**Additional context**
When using the Micrometer actuator endpoint `/metrics/test?tag=tag1%3Atest1&tag=tag3%3Atest3` we can actually see that the second meter is properly registered and has the correct count.

Maybe this is a misunderstanding on my part about how tags/labels work, but my expectation was that any set of different tags would just create a new entry for Prometheus.

**Comment by gviczai** [comment] 2021-08-17 18:07
I'm maybe wrong, but I think it is a REQUIREMENT by Prometheus, that under the same name ("test" in your case) only metrics with the same tag KEYS can be registered. So if you registered one with "tag1" and "tag2", you must stick to it. So these are valid:
```
Counter.builder("test").tag("tag1", "test1").tag("tag2", "test2").register(meterRegistry).increment();
Counter.builder("test").tag("tag1", "test1").tag("tag2", "test3").register(meterRegistry).increment();
```
See: https://github.com/micrometer-metrics/micrometer/blob/1.7.x/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L488

**Comment by jonatan-ivanov** [comment] 2021-08-20 19:30
Seems like a duplicate of #877

**Closed by jonatan-ivanov** 2021-08-20 19:30 UTC
Labels: duplicate
