### ISSUE TITLE
out of memory in MpscLinkedQueue

### ISSUE THREAD

**Issue by abadurczyk** [micrometer-metrics/micrometer#1172] opened 2019-01-21 07:52 UTC
Hi,

my application is crashing randomly with out of memory errors. The heap dump shows many entries in MpscLinkedQueue. The keys are the same but the value is different.

For example:

![screenshot_20190117_142346](https://user-images.githubusercontent.com/16633510/51459608-74c6ef00-1d59-11e9-97e3-67e8bd2d58c5.png)

as you can see, the next value in the linkedQueue has the same key. This continues until an oom error.

This is hard to reproduce, it happens randomly on some application host. Sometimes the application is under load, sometimes it's idle.

Using 
micrometer-core
micrometer-registry-prometheus
micrometer-registry-statsd

in version 1.1.1

micrometer sends the data telegraf. Telegraf is running on localhost.

management:
  metrics:
    export:
      statsd:
        flavor: telegraf
        host: localhost

Thanks

**Comment by honnel** [comment] 2019-01-29 09:38
Is there a need for any additional information?
We have this oom issue currently in production environment.

**Comment by kshazeb26** [comment] 2019-02-17 05:52
I am facing the same issue while using datadog. It just doesn't release memory.

**Comment by izeye** [comment] 2019-02-18 11:00
The `StatsdMeterRegistry` uses an unbounded queue, so it seems an OOM could happen theoretically if one of subscribers blocked in its `onNext()` method. [A `lineSink` can be provided for an additional custom line sink](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L423), so I wonder whether the `lineSink` is involved or not here. Can anyone who reported this confirm that the `lineSink` is being used or not? We could reduce the scope of the cause for this with the answer.

If anyone could provide a sample reproducing this, it would be very helpful.

**Comment by jkschneider** [comment] 2019-02-27 04:10
Current theory is the UdpClient is actually erroring in a silent way, causing the queue to just fill up. Can anybody tell us whether metrics have not been delivered at all for some period of time prior to the OOM?

**Comment by abadurczyk** [comment] 2019-03-04 22:01
As far as I can see, metrics stopped arriving about 2 minutes prior to the OOM.

**Comment by nfw999** [comment] 2019-03-06 08:02
I also encountered the same problem.
![image](https://user-images.githubusercontent.com/33611490/53864600-dd2b1080-4027-11e9-98fc-395de250e1dd.png)

Pv data is abnormal，Usually around 2300/min, when the problem occurs, increase to 11702094/min, by querying the nginx log, the pv of that time is the same as usual.

![image](https://user-images.githubusercontent.com/33611490/53864718-28452380-4028-11e9-85fd-fb096ec766e6.png)
![image](https://user-images.githubusercontent.com/33611490/53864847-7ce89e80-4028-11e9-9fba-b26b9d961088.png)

**Comment by abadurczyk** [comment] 2019-04-17 14:05
Any news about this issue?

**Comment by ianynchen** [comment] 2019-12-17 03:51
I have the same issue, might be network related. Is there a fix to this? Rather than quickly filling up the queue and kill the service, can we instruct micrometer to discard previously accumulated messages?

**Comment by nfw999** [comment] 2019-12-19 01:55
The default pause detector causes this exception，
you can configure it like follows：
```
registry.config().pauseDetector(new NoPauseDetector());
```
or upgrade to version [v1.0.10](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.0.10) or above

**Comment by jkschneider** [comment] 2020-05-08 15:12
I believe this is now resolved in 1.0.10+? Please feel free to reopen if there is any recurrence of this observed.

**Closed by jkschneider** 2020-05-08 15:12 UTC
